
  CREATE OR REPLACE SYNONYM "C_ITX"."ACT_I_PRC_ANALYTICAL_IMPUTATION" FOR "C_ITX"."ACT_PRC_ANALYTICAL_IMPUTATION"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACI_I_PRC_BLEED" FOR "C_ITX"."ACI_PRC_BLEED"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACI_I_PRC_STOCK_MOVEMENT" FOR "C_ITX"."ACI_PRC_STOCK_MOVEMENT"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACR_I_LIB_GL_EXPORT" FOR "C_ITX"."ACR_LIB_GL_EXPORT"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACR_I_LIB_GL_EXPORT_FILE" FOR "C_ITX"."ACR_LIB_GL_EXPORT_FILE"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACS_I_LIB_ALTERNATIVE" FOR "C_ITX"."ACS_LIB_ALTERNATIVE"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACS_I_LIB_LOGISTIC_FINANCIAL" FOR "C_ITX"."ACS_LIB_LOGISTIC_FINANCIAL"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACS_I_LIB_LOOKUP" FOR "C_ITX"."ACS_LIB_LOOKUP"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACS_I_PRC_FINANCIAL_YEAR" FOR "C_ITX"."ACS_PRC_FINANCIAL_YEAR"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACT_I_LIB_DEFERRAL" FOR "C_ITX"."ACT_LIB_DEFERRAL"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACT_I_MGT_MGM_TOT_BY_PERIOD" FOR "C_ITX"."ACT_MGT_MGM_TOT_BY_PERIOD"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACT_I_PRC_DEFERRAL" FOR "C_ITX"."ACT_PRC_DEFERRAL"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACT_I_PRC_DOCUMENT" FOR "C_ITX"."ACT_PRC_DOCUMENT"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACT_I_PRC_FINANCIAL_IMPUTATION" FOR "C_ITX"."ACT_PRC_FINANCIAL_IMPUTATION"


  CREATE OR REPLACE SYNONYM "C_ITX"."ACT_I_PRC_MGM_TOT_BY_PERIOD" FOR "C_ITX"."ACT_PRC_MGM_TOT_BY_PERIOD"


  CREATE OR REPLACE SYNONYM "C_ITX"."ASA_I_LIB_RECORD" FOR "C_ITX"."ASA_LIB_RECORD"


  CREATE OR REPLACE SYNONYM "C_ITX"."ASA_I_LIB_RECORD_COMP" FOR "C_ITX"."ASA_LIB_RECORD_COMP"


  CREATE OR REPLACE SYNONYM "C_ITX"."ASA_I_LIB_RECORD_TASK" FOR "C_ITX"."ASA_LIB_RECORD_TASK"


  CREATE OR REPLACE SYNONYM "C_ITX"."ASA_I_PRC_GUARANTY_CARDS" FOR "C_ITX"."ASA_PRC_GUARANTY_CARDS"


  CREATE OR REPLACE SYNONYM "C_ITX"."ASA_I_PRC_RECORD" FOR "C_ITX"."ASA_PRC_RECORD"


  CREATE OR REPLACE SYNONYM "C_ITX"."ASA_I_PRC_RECORD_COMP" FOR "C_ITX"."ASA_PRC_RECORD_COMP"


  CREATE OR REPLACE SYNONYM "C_ITX"."ASA_I_PRC_RECORD_DELAY" FOR "C_ITX"."ASA_PRC_RECORD_DELAY"


  CREATE OR REPLACE SYNONYM "C_ITX"."ASA_I_PRC_RECORD_EVENTS" FOR "C_ITX"."ASA_PRC_RECORD_EVENTS"


  CREATE OR REPLACE SYNONYM "C_ITX"."ASA_I_PRC_RECORD_SERIAL" FOR "C_ITX"."ASA_PRC_RECORD_SERIAL"


  CREATE OR REPLACE SYNONYM "C_ITX"."ASA_I_PRC_RECORD_TASK" FOR "C_ITX"."ASA_PRC_RECORD_TASK"


  CREATE OR REPLACE SYNONYM "C_ITX"."ASA_I_PRC_STOCK_MOVEMENTS" FOR "C_ITX"."ASA_PRC_STOCK_MOVEMENTS"


  CREATE OR REPLACE SYNONYM "C_ITX"."COM_I_COM_PRC_CONFIG" FOR "C_ITX"."COM_PRC_CONFIG"


  CREATE OR REPLACE SYNONYM "C_ITX"."COM_I_LIB_ECC_COMPARISON" FOR "C_ITX"."COM_LIB_ECC_COMPARISON"


  CREATE OR REPLACE SYNONYM "C_ITX"."COM_I_LIB_ECM" FOR "C_ITX"."COM_LIB_ECM"


  CREATE OR REPLACE SYNONYM "C_ITX"."COM_I_LIB_FILES" FOR "C_ITX"."COM_LIB_FILES"


  CREATE OR REPLACE SYNONYM "C_ITX"."COM_I_LIB_LIST_ID_TEMP" FOR "C_ITX"."COM_LIB_LIST_ID_TEMP"


  CREATE OR REPLACE SYNONYM "C_ITX"."COM_I_LIB_UAC" FOR "C_ITX"."COM_LIB_UAC"


  CREATE OR REPLACE SYNONYM "C_ITX"."COM_I_PRC_EBANKING" FOR "C_ITX"."COM_PRC_EBANKING"


  CREATE OR REPLACE SYNONYM "C_ITX"."COM_I_PRC_EBANKING_DET" FOR "C_ITX"."COM_PRC_EBANKING_DET"


  CREATE OR REPLACE SYNONYM "C_ITX"."COM_I_PRC_EBANKING_FILES" FOR "C_ITX"."COM_PRC_EBANKING_FILES"


  CREATE OR REPLACE SYNONYM "C_ITX"."COM_I_PRC_ECC_COMPARISON" FOR "C_ITX"."COM_PRC_ECC_COMPARISON"


  CREATE OR REPLACE SYNONYM "C_ITX"."COM_I_PRC_LIST_ID_TEMP" FOR "C_ITX"."COM_PRC_LIST_ID_TEMP"


  CREATE OR REPLACE SYNONYM "C_ITX"."COM_I_PRC_UAC" FOR "C_ITX"."COM_PRC_UAC"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_ALLOY" FOR "C_ITX"."DOC_LIB_ALLOY"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_CONSTANT" FOR "C_ITX"."DOC_LIB_CONSTANT"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_DISCOUNT_CHARGE" FOR "C_ITX"."DOC_LIB_DISCOUNT_CHARGE"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_DOCUMENT" FOR "C_ITX"."DOC_LIB_DOCUMENT"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_ESTIMATE" FOR "C_ITX"."DOC_LIB_ESTIMATE"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_ESTIMATE_ELEM_COST" FOR "C_ITX"."DOC_LIB_ESTIMATE_ELEM_COST"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_ESTIMATE_POS" FOR "C_ITX"."DOC_LIB_ESTIMATE_POS"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_GAUGE" FOR "C_ITX"."DOC_LIB_GAUGE"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_GAUGE_WARNINGS" FOR "C_ITX"."DOC_LIB_GAUGE_WARNINGS"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_POSITION" FOR "C_ITX"."DOC_LIB_POSITION"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_POSITION_DETAIL" FOR "C_ITX"."DOC_LIB_POSITION_DETAIL"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_PRINTING" FOR "C_ITX"."DOC_LIB_PRINTING"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_SAFT" FOR "C_ITX"."DOC_LIB_SAFT"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_SUBCONTRACT" FOR "C_ITX"."DOC_LIB_SUBCONTRACT"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_SUBCONTRACTO" FOR "C_ITX"."DOC_LIB_SUBCONTRACTO"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_SUBCONTRACTP" FOR "C_ITX"."DOC_LIB_SUBCONTRACTP"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_LIB_VAT" FOR "C_ITX"."DOC_LIB_VAT"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_DOCUMENT" FOR "C_ITX"."DOC_PRC_DOCUMENT"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_DOCUMENT_NUMBER" FOR "C_ITX"."DOC_PRC_DOCUMENT_NUMBER"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_ESTIMATE" FOR "C_ITX"."DOC_PRC_ESTIMATE"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_ESTIMATE_ELEM_COST" FOR "C_ITX"."DOC_PRC_ESTIMATE_ELEM_COST"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_ESTIMATE_POS" FOR "C_ITX"."DOC_PRC_ESTIMATE_POS"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_FLOW_WARNINGS" FOR "C_ITX"."DOC_PRC_FLOW_WARNINGS"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_FOOT_PAYMENT" FOR "C_ITX"."DOC_PRC_FOOT_PAYMENT"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_INTERFACE" FOR "C_ITX"."DOC_PRC_INTERFACE"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_MOVEMENT" FOR "C_ITX"."DOC_PRC_MOVEMENT"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_PALLET" FOR "C_ITX"."DOC_PRC_PALLET"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_POSITION" FOR "C_ITX"."DOC_PRC_POSITION"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_POSITION_DETAIL" FOR "C_ITX"."DOC_PRC_POSITION_DETAIL"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_SAFT" FOR "C_ITX"."DOC_PRC_SAFT"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_SUBCONTRACT" FOR "C_ITX"."DOC_PRC_SUBCONTRACT"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_SUBCONTRACTO" FOR "C_ITX"."DOC_PRC_SUBCONTRACTO"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_SUBCONTRACTP" FOR "C_ITX"."DOC_PRC_SUBCONTRACTP"


  CREATE OR REPLACE SYNONYM "C_ITX"."DOC_I_PRC_VAT" FOR "C_ITX"."DOC_PRC_VAT"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_ADV_POSTCALCULATION" FOR "C_ITX"."FAL_LIB_ADV_POSTCALCULATION"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_ALLOY_INVENTORY" FOR "C_ITX"."FAL_LIB_ALLOY_INVENTORY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_ASSEMBLY" FOR "C_ITX"."FAL_LIB_ASSEMBLY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_ATTRIB" FOR "C_ITX"."FAL_LIB_ATTRIB"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_BATCH" FOR "C_ITX"."FAL_LIB_BATCH"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_CALCULATION" FOR "C_ITX"."FAL_LIB_CALCULATION"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_COMPONENT_LINK" FOR "C_ITX"."FAL_LIB_COMPONENT_LINK"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_CONSTANT" FOR "C_ITX"."FAL_LIB_CONSTANT"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_DRP" FOR "C_ITX"."FAL_LIB_DRP"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_FACTORY_FLOOR" FOR "C_ITX"."FAL_LIB_FACTORY_FLOOR"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_GANTT" FOR "C_ITX"."FAL_LIB_GANTT"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_LINE_INVENTORY" FOR "C_ITX"."FAL_LIB_LINE_INVENTORY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_LOT_MATERIAL_LINK" FOR "C_ITX"."FAL_LIB_LOT_MATERIAL_LINK"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_LOT_PROGRESS" FOR "C_ITX"."FAL_LIB_LOT_PROGRESS"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_LOT_PROGRESS_FOG" FOR "C_ITX"."FAL_LIB_LOT_PROGRESS_FOG"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_LOT_PROP" FOR "C_ITX"."FAL_LIB_LOT_PROP"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_MASTER_PLAN" FOR "C_ITX"."FAL_LIB_MASTER_PLAN"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_MOVEMENT" FOR "C_ITX"."FAL_LIB_MOVEMENT"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_MRP_CALCULATION" FOR "C_ITX"."FAL_LIB_MRP_CALCULATION"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_ORDER" FOR "C_ITX"."FAL_LIB_ORDER"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_PAIRING" FOR "C_ITX"."FAL_LIB_PAIRING"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_POSITION" FOR "C_ITX"."FAL_LIB_POSITION"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_POSITION_INIT_QTY" FOR "C_ITX"."FAL_LIB_POSITION_INIT_QTY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_PROGRAM" FOR "C_ITX"."FAL_LIB_PROGRAM"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_SUBCONTRACTO" FOR "C_ITX"."FAL_LIB_SUBCONTRACTO"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_SUBCONTRACTP" FOR "C_ITX"."FAL_LIB_SUBCONTRACTP"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_TASK_CHIP" FOR "C_ITX"."FAL_LIB_TASK_CHIP"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_TASK_LINK" FOR "C_ITX"."FAL_LIB_TASK_LINK"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_TASK_LINK_PROP" FOR "C_ITX"."FAL_LIB_TASK_LINK_PROP"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_LIB_WEIGH" FOR "C_ITX"."FAL_LIB_WEIGH"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_MGT_ADV_CALCULATION" FOR "C_ITX"."FAL_MGT_ADV_CALCULATION"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_MGT_INVENTORY" FOR "C_ITX"."FAL_MGT_INVENTORY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_MGT_TASK_CHIP" FOR "C_ITX"."FAL_MGT_TASK_CHIP"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_ALLOY_INVENTORY" FOR "C_ITX"."FAL_PRC_ALLOY_INVENTORY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_ASSEMBLY" FOR "C_ITX"."FAL_PRC_ASSEMBLY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_ATTRIB" FOR "C_ITX"."FAL_PRC_ATTRIB"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_BATCH" FOR "C_ITX"."FAL_PRC_BATCH"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_DRP" FOR "C_ITX"."FAL_PRC_DRP"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_FAL_DOC_PROP" FOR "C_ITX"."FAL_PRC_FAL_DOC_PROP"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_FAL_LOT_PROP" FOR "C_ITX"."FAL_PRC_FAL_LOT_PROP"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_FAL_PROP_COMMON" FOR "C_ITX"."FAL_PRC_FAL_PROP_COMMON"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_LINE_INVENTORY" FOR "C_ITX"."FAL_PRC_LINE_INVENTORY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_MASTER_PLAN" FOR "C_ITX"."FAL_PRC_MASTER_PLAN"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_PAIRING" FOR "C_ITX"."FAL_PRC_PAIRING"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_POSITION" FOR "C_ITX"."FAL_PRC_POSITION"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_POSITION_INIT_QTY" FOR "C_ITX"."FAL_PRC_POSITION_INIT_QTY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_POST_CALCULATION" FOR "C_ITX"."FAL_PRC_POST_CALCULATION"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_REPORT_ATTRIB" FOR "C_ITX"."FAL_PRC_REPORT_ATTRIB"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_RETRIEVE_MANUF_PROP" FOR "C_ITX"."FAL_PRC_RETRIEVE_MANUF_PROP"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_RETRIEVE_SUBCP_PROP" FOR "C_ITX"."FAL_PRC_RETRIEVE_SUBCP_PROP"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_SCHEDULE_PLAN" FOR "C_ITX"."FAL_PRC_SCHEDULE_PLAN"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_SUBCONTRACTO" FOR "C_ITX"."FAL_PRC_SUBCONTRACTO"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_SUBCONTRACTP" FOR "C_ITX"."FAL_PRC_SUBCONTRACTP"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_TASK" FOR "C_ITX"."FAL_PRC_TASK"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_TASK_CHIP" FOR "C_ITX"."FAL_PRC_TASK_CHIP"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_TASK_LINK" FOR "C_ITX"."FAL_PRC_TASK_LINK"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_WEIGH" FOR "C_ITX"."FAL_PRC_WEIGH"


  CREATE OR REPLACE SYNONYM "C_ITX"."FAL_I_PRC_WIP_CALCULATION" FOR "C_ITX"."FAL_PRC_WIP_CALCULATION"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_ACB_ENTITY" FOR "C_ITX"."FWK_TYP_ACB_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_ACI_ENTITY" FOR "C_ITX"."FWK_TYP_ACI_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_ACJ_ENTITY" FOR "C_ITX"."FWK_TYP_ACJ_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_ACR_ENTITY" FOR "C_ITX"."FWK_TYP_ACR_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_ACS_ENTITY" FOR "C_ITX"."FWK_TYP_ACS_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_ACT_ENTITY" FOR "C_ITX"."FWK_TYP_ACT_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_ASA_ENTITY" FOR "C_ITX"."FWK_TYP_ASA_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_CLA_ENTITY" FOR "C_ITX"."FWK_TYP_CLA_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_CML_ENTITY" FOR "C_ITX"."FWK_TYP_CML_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_COM_ENTITY" FOR "C_ITX"."FWK_TYP_COM_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_DOC_ENTITY" FOR "C_ITX"."FWK_TYP_DOC_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_DWH_ENTITY" FOR "C_ITX"."FWK_TYP_DWH_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_FAL_ENTITY" FOR "C_ITX"."FWK_TYP_FAL_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_FAM_ENTITY" FOR "C_ITX"."FWK_TYP_FAM_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_GAL_ENTITY" FOR "C_ITX"."FWK_TYP_GAL_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_GCO_ENTITY" FOR "C_ITX"."FWK_TYP_GCO_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_HRM_ENTITY" FOR "C_ITX"."FWK_TYP_HRM_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_IMP_ENTITY" FOR "C_ITX"."FWK_TYP_IMP_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_LPM_ENTITY" FOR "C_ITX"."FWK_TYP_LPM_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_LTM_ENTITY" FOR "C_ITX"."FWK_TYP_LTM_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_MGM_ENTITY" FOR "C_ITX"."FWK_TYP_MGM_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_PAC_ENTITY" FOR "C_ITX"."FWK_TYP_PAC_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_PC_ENTITY" FOR "C_ITX"."FWK_TYP_PC_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_PC_KM_ENTITY" FOR "C_ITX"."FWK_TYP_PC_KM_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_PPS_ENTITY" FOR "C_ITX"."FWK_TYP_PPS_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_PTC_ENTITY" FOR "C_ITX"."FWK_TYP_PTC_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_REP_ENTITY" FOR "C_ITX"."FWK_TYP_REP_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_SCH_ENTITY" FOR "C_ITX"."FWK_TYP_SCH_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_SHP_ENTITY" FOR "C_ITX"."FWK_TYP_SHP_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_SQM_ENTITY" FOR "C_ITX"."FWK_TYP_SQM_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_STM_ENTITY" FOR "C_ITX"."FWK_TYP_STM_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_WEB_ENTITY" FOR "C_ITX"."FWK_TYP_WEB_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_WFL_ENTITY" FOR "C_ITX"."FWK_TYP_WFL_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."FWK_I_TYP_XTL_ENTITY" FOR "C_ITX"."FWK_TYP_XTL_ENTITY"


  CREATE OR REPLACE SYNONYM "C_ITX"."GAL_I_LIB_CURRENCY_RISK" FOR "C_ITX"."GAL_LIB_CURRENCY_RISK"


  CREATE OR REPLACE SYNONYM "C_ITX"."GAL_I_LIB_PROJECT" FOR "C_ITX"."GAL_LIB_PROJECT"


  CREATE OR REPLACE SYNONYM "C_ITX"."GAL_I_PRC_CURRENCY_RISK" FOR "C_ITX"."GAL_PRC_CURRENCY_RISK"


  CREATE OR REPLACE SYNONYM "C_ITX"."GAL_I_PRC_PROJECT" FOR "C_ITX"."GAL_PRC_PROJECT"


  CREATE OR REPLACE SYNONYM "C_ITX"."GAL_I_PRC_SNAPSHOT" FOR "C_ITX"."GAL_PRC_SNAPSHOT"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_LIB_ALLOY" FOR "C_ITX"."GCO_LIB_ALLOY"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_LIB_CDA_MANUFACTURE" FOR "C_ITX"."GCO_LIB_CDA_MANUFACTURE"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_LIB_CHARACTERIZATION" FOR "C_ITX"."GCO_LIB_CHARACTERIZATION"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_LIB_COMPL_DATA" FOR "C_ITX"."GCO_LIB_COMPL_DATA"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_LIB_CONSTANT" FOR "C_ITX"."GCO_LIB_CONSTANT"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_LIB_FUNCTIONS" FOR "C_ITX"."GCO_LIB_FUNCTIONS"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_LIB_PRECIOUS_MAT" FOR "C_ITX"."GCO_LIB_PRECIOUS_MAT"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_LIB_PRICE" FOR "C_ITX"."GCO_LIB_PRICE"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_LIB_QUALITY_STATUS" FOR "C_ITX"."GCO_LIB_QUALITY_STATUS"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_LIB_VERSION" FOR "C_ITX"."GCO_LIB_VERSION"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_PRC_CDA_MANUFACTURE" FOR "C_ITX"."GCO_PRC_CDA_MANUFACTURE"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_PRC_CHARACTERIZATION" FOR "C_ITX"."GCO_PRC_CHARACTERIZATION"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_PRC_COMPL_DATA" FOR "C_ITX"."GCO_PRC_COMPL_DATA"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_PRC_GOOD" FOR "C_ITX"."GCO_PRC_GOOD"


  CREATE OR REPLACE SYNONYM "C_ITX"."GCO_I_PRC_VERSION" FOR "C_ITX"."GCO_PRC_VERSION"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_ELM_TAXSOURCE_XML" FOR "C_ITX"."HRM_ELM_TAXSOURCE_XML"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_LIB_CONSTANT" FOR "C_ITX"."HRM_LIB_CONSTANT"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_LIB_ELM" FOR "C_ITX"."HRM_LIB_ELM"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_LIB_ESTABLISHMENT" FOR "C_ITX"."HRM_LIB_ESTABLISHMENT"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_LIB_HISTORY" FOR "C_ITX"."HRM_PRC_HISTORY"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_LIB_PERSON" FOR "C_ITX"."HRM_LIB_PERSON"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_LIB_TAXSOURCE" FOR "C_ITX"."HRM_LIB_TAXSOURCE"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_LIB_TAXSOURCE_LEDGER" FOR "C_ITX"."HRM_LIB_TAXSOURCE_LEDGER"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_PRC_CONTRACT" FOR "C_ITX"."HRM_PRC_CONTRACT"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_PRC_ELM" FOR "C_ITX"."HRM_PRC_ELM"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_PRC_HISTORY" FOR "C_ITX"."HRM_PRC_HISTORY"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_PRC_PERSON_TAX" FOR "C_ITX"."HRM_PRC_PERSON_TAX"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_PRC_REP_LIST" FOR "C_ITX"."HRM_PRC_REP_LIST"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_PRC_TAXSOURCE" FOR "C_ITX"."HRM_PRC_TAXSOURCE"


  CREATE OR REPLACE SYNONYM "C_ITX"."HRM_I_PRC_TAXSOURCE_LEDGER" FOR "C_ITX"."HRM_PRC_TAXSOURCE_LEDGER"


  CREATE OR REPLACE SYNONYM "C_ITX"."LPM_I_LIB_CONTRACT" FOR "C_ITX"."LPM_LIB_CONTRACT"


  CREATE OR REPLACE SYNONYM "C_ITX"."LPM_I_LIB_REFERENTS" FOR "C_ITX"."LPM_LIB_REFERENTS"


  CREATE OR REPLACE SYNONYM "C_ITX"."LPM_I_LIB_WEEK_TEMPLATE" FOR "C_ITX"."LPM_LIB_WEEK_TEMPLATE"


  CREATE OR REPLACE SYNONYM "C_ITX"."LPM_I_PRC_CONTRACT" FOR "C_ITX"."LPM_PRC_CONTRACT"


  CREATE OR REPLACE SYNONYM "C_ITX"."LPM_I_PRC_WEEK_TEMPLATE" FOR "C_ITX"."LPM_PRC_WEEK_TEMPLATE"


  CREATE OR REPLACE SYNONYM "C_ITX"."MOB_I_LIB_VIEW_PAC" FOR "C_ITX"."MOB_LIB_VIEW_PAC"


  CREATE OR REPLACE SYNONYM "C_ITX"."MOB_I_PRC_VIEW_PAC" FOR "C_ITX"."MOB_PRC_VIEW_PAC"


  CREATE OR REPLACE SYNONYM "C_ITX"."PAC_I_LIB_LOOKUP" FOR "C_ITX"."PAC_LIB_LOOKUP"


  CREATE OR REPLACE SYNONYM "C_ITX"."PAC_I_LIB_PAYMENT" FOR "C_ITX"."PAC_LIB_PAYMENT"


  CREATE OR REPLACE SYNONYM "C_ITX"."PAC_I_LIB_SCHEDULE" FOR "C_ITX"."PAC_LIB_SCHEDULE"


  CREATE OR REPLACE SYNONYM "C_ITX"."PAC_I_LIB_THIRD" FOR "C_ITX"."PAC_LIB_THIRD"


  CREATE OR REPLACE SYNONYM "C_ITX"."PAC_I_PRC_SCHEDULE" FOR "C_ITX"."PAC_PRC_SCHEDULE"


  CREATE OR REPLACE SYNONYM "C_ITX"."PPS_I_LIB_FUNCTIONS" FOR "C_ITX"."PPS_LIB_FUNCTIONS"


  CREATE OR REPLACE SYNONYM "C_ITX"."PPS_I_LIB_INTERRO" FOR "C_ITX"."PPS_LIB_INTERRO"


  CREATE OR REPLACE SYNONYM "C_ITX"."PPS_I_LIB_OPERATION_PROCEDURE" FOR "C_ITX"."PPS_LIB_OPERATION_PROCEDURE"


  CREATE OR REPLACE SYNONYM "C_ITX"."PPS_I_PRC_INTERRO" FOR "C_ITX"."PPS_PRC_INTERRO"


  CREATE OR REPLACE SYNONYM "C_ITX"."PPS_I_PRC_NOMENCLATURE" FOR "C_ITX"."PPS_PRC_NOMENCLATURE"


  CREATE OR REPLACE SYNONYM "C_ITX"."PPS_I_PRC_OPERATION_PROCEDURE" FOR "C_ITX"."PPS_PRC_OPERATION_PROCEDURE"


  CREATE OR REPLACE SYNONYM "C_ITX"."PTC_I_LIB_PRICE" FOR "C_ITX"."PTC_LIB_PRICE"


  CREATE OR REPLACE SYNONYM "C_ITX"."PTC_I_LIB_SAMPLE" FOR "C_ITX"."PTC_LIB_SAMPLE"


  CREATE OR REPLACE SYNONYM "C_ITX"."PTC_I_PRC_PRICE" FOR "C_ITX"."PTC_PRC_PRICE"


  CREATE OR REPLACE SYNONYM "C_ITX"."PTC_I_PRC_SAMPLE" FOR "C_ITX"."PTC_PRC_SAMPLE"


  CREATE OR REPLACE SYNONYM "C_ITX"."REP_I_LIB_CONSTANT" FOR "C_ITX"."REP_LIB_CONSTANT"


  CREATE OR REPLACE SYNONYM "C_ITX"."REP_I_LIB_ECC_XML" FOR "C_ITX"."REP_LIB_ECC_XML"


  CREATE OR REPLACE SYNONYM "C_ITX"."REP_I_LIB_GCO_ECC_XML" FOR "C_ITX"."REP_LIB_GCO_ECC_XML"


  CREATE OR REPLACE SYNONYM "C_ITX"."REP_I_PRC_ECC" FOR "C_ITX"."REP_PRC_ECC"


  CREATE OR REPLACE SYNONYM "C_ITX"."SCH_I_PRC_LPM_INTERFACE" FOR "C_ITX"."SCH_PRC_LPM_INTERFACE"


  CREATE OR REPLACE SYNONYM "C_ITX"."SCH_I_PRC_STUDENT" FOR "C_ITX"."SCH_PRC_STUDENT"


  CREATE OR REPLACE SYNONYM "C_ITX"."SHP_I_LIB_DATASOURCES" FOR "C_ITX"."SHP_LIB_DATASOURCES"


  CREATE OR REPLACE SYNONYM "C_ITX"."SHP_I_LIB_PRODUCT" FOR "C_ITX"."SHP_LIB_PRODUCT"


  CREATE OR REPLACE SYNONYM "C_ITX"."SHP_I_LIB_STOCK" FOR "C_ITX"."SHP_LIB_STOCK"


  CREATE OR REPLACE SYNONYM "C_ITX"."SHP_I_LIB_TYPES" FOR "C_ITX"."SHP_LIB_TYPES"


  CREATE OR REPLACE SYNONYM "C_ITX"."SHP_I_LIB_USER" FOR "C_ITX"."SHP_LIB_USER"


  CREATE OR REPLACE SYNONYM "C_ITX"."SHP_I_MGT_DATA_EXPORT" FOR "C_ITX"."SHP_MGT_DATA_EXPORT"


  CREATE OR REPLACE SYNONYM "C_ITX"."SHP_I_MGT_IMPORT_XML" FOR "C_ITX"."SHP_MGT_IMPORT_XML"


  CREATE OR REPLACE SYNONYM "C_ITX"."SHP_I_PRC_IMPORT" FOR "C_ITX"."SHP_PRC_IMPORT"


  CREATE OR REPLACE SYNONYM "C_ITX"."SHP_I_PRC_PUBLISH" FOR "C_ITX"."SHP_PRC_PUBLISH"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_LIB_CHARACTERIZATION" FOR "C_ITX"."STM_LIB_CHARACTERIZATION"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_LIB_CONSTANT" FOR "C_ITX"."STM_LIB_CONSTANT"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_LIB_ELEMENT_NUMBER" FOR "C_ITX"."STM_LIB_ELEMENT_NUMBER"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_LIB_EXERCISE" FOR "C_ITX"."STM_LIB_EXERCISE"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_LIB_MOVEMENT" FOR "C_ITX"."STM_LIB_MOVEMENT"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_LIB_STOCK" FOR "C_ITX"."STM_LIB_STOCK"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_LIB_STOCK_POSITION" FOR "C_ITX"."STM_LIB_STOCK_POSITION"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_PRC_COSTPRICE" FOR "C_ITX"."STM_PRC_COSTPRICE"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_PRC_ELEMENT_NUMBER" FOR "C_ITX"."STM_PRC_ELEMENT_NUMBER"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_PRC_KLS" FOR "C_ITX"."STM_PRC_KLS"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_PRC_MOVEMENT" FOR "C_ITX"."STM_PRC_MOVEMENT"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_PRC_STOCK" FOR "C_ITX"."STM_PRC_STOCK"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_PRC_STOCK_EVOLUTION" FOR "C_ITX"."STM_PRC_STOCK_EVOLUTION"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_PRC_STOCK_POSITION" FOR "C_ITX"."STM_PRC_STOCK_POSITION"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_I_PRC_TRESHOLD" FOR "C_ITX"."STM_PRC_TRESHOLD"


  CREATE OR REPLACE SYNONYM "C_ITX"."STM_MOVEMENT" FOR "C_ITX"."STM_PRC_MOVEMENT"


  CREATE OR REPLACE SYNONYM "C_ITX"."WEB_I_LIB_CATEG" FOR "C_ITX"."WEB_LIB_CATEG"


  CREATE OR REPLACE SYNONYM "C_ITX"."WEB_I_PRC_CATEG" FOR "C_ITX"."WEB_PRC_CATEG"


  CREATE OR REPLACE SYNONYM "C_ITX"."WEB_USER" FOR "C_ITX"."V_WEB_USER_IO"

