--------------------------------------------------------
--  DDL for Procedure RPT_ACS_INTEREST_METHOD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACS_INTEREST_METHOD" (
   arefcursor       IN OUT   crystal_cursor_types.dualcursortyp,
   parameter_0      IN       VARCHAR2,
   parameter_1      IN       VARCHAR2,
   procuser_lanid   IN       pcs.pc_lang.lanid%TYPE
)
IS
/**
*DESCRIPTION
USED FOR REPORT ACT_INTEREST_METHOD
*author JLI
*lastUpdate July 4 2009
*public
*@param PARAMETER_0:  ICM_DESCRIPTION
*@param PARAMETER_1:  ICM_DESCRIPTION
*/

tmp           NUMBER;
vpc_lang_id   pcs.pc_lang.pc_lang_id%TYPE;

BEGIN
   pcs.PC_I_LIB_SESSION.setlanid (procuser_lanid);
   vpc_lang_id := pcs.PC_I_LIB_SESSION.getuserlangid;

OPEN arefcursor FOR
SELECT
MED.ACS_INT_CALC_METHOD_ID,
MED.ACS_INTEREST_ACC_ID,
MED.ACS_ASSETS_INT_ACC_ID,
MED.ACS_LIABIL_INT_ACC_ID,
MED.ACS_ADV_TAX_ACC_ID,
MED.ICM_DESCRIPTION,
MED.ICM_COMMENT,
MED.C_METHOD,
MED.C_INT_DOC_GENERATION,
MED.C_ROUND_TYPE,
MED.ICM_ASSETS_INT_LBL,
MED.ICM_LIABIL_INT_LBL,
MED.ICM_ROUND_AMOUNT,
ELE.ACS_INTEREST_CATEG_ID,
ELE.ACS_DIVISION_ACCOUNT_ID,
ELE.ACS_FINANCIAL_ACCOUNT_ID,
ELE.ACS_INTEREST_ACC_ID,
ELE.ACS_ASSETS_INT_ACC_ID,
ELE.ACS_LIABIL_INT_ACC_ID,
ELE.ACS_ADV_TAX_ACC_ID,
ELE.MEL_ADV_TAX_SUBJECT,
ELE.MEL_ADV_TAX_EXEMPTION,
CUR.CURRENCY,
ACS_FUNCTION.GetAccountNumber(ELE.ACS_DIVISION_ACCOUNT_ID) DIV_ACC,
ACS_FUNCTION.GetAccountNumber(ELE.ACS_FINANCIAL_ACCOUNT_ID) FIN_ACC
FROM
ACS_INT_CALC_METHOD MED,
ACS_METHOD_ELEM  ELE,
ACS_FINANCIAL_CURRENCY FUR,
PCS.PC_CURR CUR
WHERE
MED.ACS_INT_CALC_METHOD_ID = ELE.ACS_INT_CALC_METHOD_ID(+)
AND ((parameter_0 IS NULL AND parameter_1 IS NULL)
    OR (parameter_0 IS NULL AND parameter_1 IS NOT NULL AND MED.ICM_DESCRIPTION <= parameter_1)
    OR (parameter_1 IS NULL AND parameter_0 IS NOT NULL AND MED.ICM_DESCRIPTION >= parameter_0)
    OR (parameter_1 IS NOT NULL AND parameter_0 IS NOT NULL AND MED.ICM_DESCRIPTION >= parameter_0 AND MED.ICM_DESCRIPTION <= parameter_1))
AND ELE.ACS_FINANCIAL_CURRENCY_ID = FUR.ACS_FINANCIAL_CURRENCY_ID(+)
AND FUR.PC_CURR_ID = CUR.PC_CURR_ID(+)
;
END RPT_ACS_INTEREST_METHOD;
