--------------------------------------------------------
--  DDL for Procedure RPT_FAM_AMORTIZATION_METHOD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_FAM_AMORTIZATION_METHOD" (
 aRefCursor       in out CRYSTAL_CURSOR_TYPES.DualCursorTyp,
 PROCUSER_LANID   in     pcs.pc_lang.lanid%type
)
IS

/**
*Description
Used for report FAM_AMORTIZATION_METHOD

*author JLI
*lastUpdate July 23 2009
* @public
*/

VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;


BEGIN


pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;



open aRefCursor for

SELECT
JSC.ACJ_CATALOGUE_DOCUMENT_ID,
JSC_INT.ACJ_CATALOGUE_DOCUMENT_ID ACJ_CATALOGUE_DOCUMENT_ID_INT,
MTD.FAM_AMORTIZATION_METHOD_ID,
MTD.C_AMORTIZATION_TYP,
MTD.C_AMORTIZATION_PERIOD,
MTD.FAM_CATALOGUE_ID,
MTD.AMO_DESCR,
MTD.C_ROUND_TYPE,
MTD.AMO_ROUNDED_AMOUNT,
MTD.FAM_FAM_CATALOGUE_ID,
MTD.C_INTEREST_CALC_RULES,
MTD.C_ROUND_TYPE_INT,
MTD.AMO_ROUNDED_AMOUNT_INT,
CVL.CMV_AMOUNTS_PILOT_FORMULA,
CVL_INT.CMV_AMOUNTS_PILOT_FORMULA CMV_AMOUNTS_PILOT_FORMULA_INT,
CAT.C_FAM_TRANSACTION_TYP,
CAT_INT.C_FAM_TRANSACTION_TYP C_FAM_TRANSACTION_TYP_INT,
MVL.VAL_KEY,
MVL.VAL_DESCR,
MVL_INT.VAL_KEY VAL_KEY_INT,
MVL_INT.VAL_DESCR VAL_DESCR_INT
FROM
ACJ_JOB_TYPE_S_CATALOGUE JSC,
ACJ_JOB_TYPE_S_CATALOGUE JSC_INT,
FAM_AMORTIZATION_METHOD MTD,
FAM_CAT_MANAGED_VALUE CVL,
FAM_CAT_MANAGED_VALUE CVL_INT,
FAM_CATALOGUE CAT,
FAM_CATALOGUE CAT_INT,
FAM_MANAGED_VALUE MVL,
FAM_MANAGED_VALUE MVL_INT
WHERE
MTD.FAM_CATALOGUE_ID = CAT.FAM_CATALOGUE_ID(+)
AND CAT.FAM_CATALOGUE_ID = CVL.FAM_CATALOGUE_ID(+)
AND CVL.FAM_MANAGED_VALUE_ID = MVL.FAM_MANAGED_VALUE_ID(+)
AND CAT.ACJ_JOB_TYPE_S_CATALOGUE2_ID = JSC.ACJ_JOB_TYPE_S_CATALOGUE_ID(+)
AND MTD.FAM_FAM_CATALOGUE_ID = CAT_INT.FAM_CATALOGUE_ID(+)
AND CAT_INT.FAM_CATALOGUE_ID = CVL_INT.FAM_CATALOGUE_ID(+)
AND CVL_INT.FAM_MANAGED_VALUE_ID = MVL_INT.FAM_MANAGED_VALUE_ID(+)
AND CAT_INT.ACJ_JOB_TYPE_S_CATALOGUE2_ID = JSC_INT.ACJ_JOB_TYPE_S_CATALOGUE_ID(+)
;

END RPT_FAM_AMORTIZATION_METHOD;
