--------------------------------------------------------
--  DDL for Procedure RPT_ACT_INTEREST_BALANCE_SUB
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACT_INTEREST_BALANCE_SUB" (
  aRefCursor            in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, PARAMETER_0           in     varchar2
, PARAMETER_1           in     varchar2
, PARAMETER_2           in     varchar2
, PARAMETER_3           in     varchar2
, PROCUSER_LANID        in     pcs.pc_lang.lanid%type
)
IS

/**
*DESCRIPTION
USED FOR SUB REPORT OF ACT_INTEREST_BALANCE
*author JLI
*lastUpdate 2009-4-7
*public
*@param PARAMETER_0:  MAX_ACT_JOB_ID
*@param PARAMETER_1:  MAX_ACS_PERIOD_ID
*@param PARAMETER_2:  ACS_ACCOUNT_ID
*@param PARAMETER_3:  ACS_DIVISION_ACCOUNT_ID
*/

TMP NUMBER;
VPC_LANG_ID       pcs.pc_lang.pc_lang_id%type;
FinancialYearId   ACS_FINANCIAL_YEAR.ACS_FINANCIAL_YEAR_ID%type;
PerNumber         ACS_PERIOD.PER_NO_PERIOD%type;
DivisionAccountId ACS_ACCOUNT.ACS_ACCOUNT_ID%type;
SubSet            ACS_SUB_SET.C_SUB_SET%type;

BEGIN

pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID        := pcs.PC_I_LIB_SESSION.GetUserLangId;
PerNumber          := RPT_FUNCTIONS.GetPerNumber;
FinancialYearId    := ACS_FUNCTION.GetMaxNoExerciceId;
SubSet             := ACS_FUNCTION.GetSubSetOfAccount(PARAMETER_2);

OPEN aRefCursor FOR

SELECT
'1' UNION_NO,/*Accounting balance*/
DECODE(SubSet,'ACC',TOT.ACS_FINANCIAL_ACCOUNT_ID
             ,'REC',TOT.ACS_AUXILIARY_ACCOUNT_ID
             ,'PAY',TOT.ACS_AUXILIARY_ACCOUNT_ID,TOT.ACS_FINANCIAL_ACCOUNT_ID) ACS_FINANCIAL_ACCOUNT_ID,
TOT.ACS_DIVISION_ACCOUNT_ID ACS_DIVISION_ACCOUNT_ID,
CURRENCY,
0 AMOUNT_IDE,
SUM(TOT_DEBIT_FC - TOT_CREDIT_FC) TOT_AMOUNT_FC,
0 IMF_AMOUNT_FC
FROM
ACT_TOTAL_BY_PERIOD TOT,
ACS_PERIOD PER,
ACS_FINANCIAL_CURRENCY FUR,
PCS.PC_CURR CUR
WHERE
TOT.ACS_PERIOD_ID = PER.ACS_PERIOD_ID
AND TOT.ACS_DIVISION_ACCOUNT_ID = PARAMETER_3
AND PER.ACS_FINANCIAL_YEAR_ID = FinancialYearId
AND PER.PER_NO_PERIOD <= PerNumber
AND TOT.C_TYPE_CUMUL = 'EXT'
AND (((SubSet = 'ACC' AND TOT.ACS_FINANCIAL_ACCOUNT_ID = PARAMETER_2) AND TOT.ACS_AUXILIARY_ACCOUNT_ID is null)
     OR ( SubSet in('REC','PAY') AND TOT.ACS_AUXILIARY_ACCOUNT_ID = PARAMETER_2))
AND ((PARAMETER_3 is null and TOT.ACS_DIVISION_ACCOUNT_ID is null)
     or (PARAMETER_3 is not null and TOT.ACS_DIVISION_ACCOUNT_ID = PARAMETER_3)
    )
AND TOT.ACS_ACS_FINANCIAL_CURRENCY_ID <>(SELECT FUR.ACS_FINANCIAL_CURRENCY_ID FROM ACS_FINANCIAL_CURRENCY FUR WHERE FUR.FIN_LOCAL_CURRENCY = 1 )
AND TOT.ACS_ACS_FINANCIAL_CURRENCY_ID = FUR.ACS_FINANCIAL_CURRENCY_ID
AND FUR.PC_CURR_ID = CUR.PC_CURR_ID
GROUP BY
DECODE(SubSet,'ACC',TOT.ACS_FINANCIAL_ACCOUNT_ID
             ,'REC',TOT.ACS_AUXILIARY_ACCOUNT_ID
             ,'PAY',TOT.ACS_AUXILIARY_ACCOUNT_ID,TOT.ACS_FINANCIAL_ACCOUNT_ID),
TOT.ACS_DIVISION_ACCOUNT_ID,
CURRENCY
UNION ALL
SELECT
'2' UNION_NO,/*WITH INTEREST BREAKDOWN -last balance before calculating interest*/
ACS_FINANCIAL_ACCOUNT_ID,
ACS_DIVISION_ACCOUNT_ID,
CURRENCY,
IDE_BALANCE_AMOUNT AMOUNT_IDE,
0 TOT_AMOUNT_FC,
0 IMF_AMOUNT_FC
FROM
ACT_INTEREST_DETAIL DET,
ACS_FINANCIAL_CURRENCY FUR,
PCS.PC_CURR CUR
WHERE
ACT_JOB_ID = PARAMETER_0
AND ACS_FINANCIAL_ACCOUNT_ID = PARAMETER_2
AND (ACS_DIVISION_ACCOUNT_ID = PARAMETER_3 or PARAMETER_3 is null)
AND DET.ACS_FINANCIAL_CURRENCY_ID <>(SELECT FUR.ACS_FINANCIAL_CURRENCY_ID FROM ACS_FINANCIAL_CURRENCY FUR WHERE FUR.FIN_LOCAL_CURRENCY = 1 )
AND DET.ACS_FINANCIAL_CURRENCY_ID =FUR.ACS_FINANCIAL_CURRENCY_ID
AND FUR.PC_CURR_ID = CUR.PC_CURR_ID
UNION ALL
SELECT
'3' UNION_NO,/*WITH INTEREST BREAKDOWN -total interest charges*/
ACS_FINANCIAL_ACCOUNT_ID,
ACS_DIVISION_ACCOUNT_ID,
CURRENCY,
0 AMOUNT_IDE,
0 TOT_AMOUNT_FC,
sum(IMF_AMOUNT_FC_D - IMF_AMOUNT_FC_C) IMF_AMOUNT_FC
FROM
V_ACT_INTEREST_DOCUMENT_FC VFC,
ACS_FINANCIAL_CURRENCY FUR,
PCS.PC_CURR CUR
WHERE
ACT_JOB_ID = PARAMETER_0
AND ACS_FINANCIAL_ACCOUNT_ID = PARAMETER_2
AND (ACS_DIVISION_ACCOUNT_ID = PARAMETER_3 or PARAMETER_3 is null)
AND VFC.ACS_FINANCIAL_CURRENCY_ID <>(SELECT FUR.ACS_FINANCIAL_CURRENCY_ID FROM ACS_FINANCIAL_CURRENCY FUR WHERE FUR.FIN_LOCAL_CURRENCY = 1 )
AND VFC.ACS_FINANCIAL_CURRENCY_ID = FUR.ACS_FINANCIAL_CURRENCY_ID
AND FUR.PC_CURR_ID = CUR.PC_CURR_ID
GROUP BY
ACS_FINANCIAL_ACCOUNT_ID ,
ACS_DIVISION_ACCOUNT_ID ,
CURRENCY

;
END RPT_ACT_INTEREST_BALANCE_SUB;
