--------------------------------------------------------
--  DDL for Procedure RPT_ACR_VAT_PROVISION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACR_VAT_PROVISION" (
  aRefCursor  in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, PROCPARAM_0 in     varchar2
, PROCUSER_LANID in  pcs.pc_lang.lanid%type
)

is
/**
* Proc¨¦dure stock¨¦e utilis¨¦e pour le rapport ACR_VAT_PROVISION (Justificatif des comptes de
* provisions TVA
*
* @author SDO
* @lastUpdate
* @version 2003
* @public
* @param PROCPARAM_0    Date jusqu'au 'yyyyMMdd'
*/
begin

pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);

open aRefCursor for
 select
  TAX.TAX_VAT_AMOUNT_LC,
  TAX.TAX_VAT_AMOUNT_FC,
  TAX.TAX_VAT_AMOUNT_EUR,
  TAX.ACT_DET_TAX_ID,
  TAX.ACT_FINANCIAL_IMPUTATION_ID,
  TAX.ACT_ACT_FINANCIAL_IMPUTATION,
  TAX.ACT2_ACT_FINANCIAL_IMPUTATION,
  NVL(IMT.ACS_FINANCIAL_ACCOUNT_ID, IMF.ACS_FINANCIAL_ACCOUNT_ID) ACS_FINANCIAL_ACCOUNT_ID,
  NVL(ACS_FUNCTION.GetAccountNumber(IMT.ACS_FINANCIAL_ACCOUNT_ID),ACS_FUNCTION.GetAccountNumber(IMF.ACS_FINANCIAL_ACCOUNT_ID)) ACCOUNT_NUMBER,
  NVL(ACS_FUNCTION.GetAccountDescriptionSummary(IMT.ACS_FINANCIAL_ACCOUNT_ID),ACS_FUNCTION.GetAccountDescriptionSummary(IMF.ACS_FINANCIAL_ACCOUNT_ID)) ACCOUNT_DESCR,
  IMF.IMF_TRANSACTION_DATE IMF_TRANSACTION_DATE_IMP,
  IMF.IMF_VALUE_DATE,
  IMF.IMF_DESCRIPTION,
  IMT.IMF_TRANSACTION_DATE IMF_TRANSACTION_DATE_TAX,
  DOC.ACT_DOCUMENT_ID,
  DOC.DOC_DOCUMENT_DATE,
  DOC.DOC_NUMBER,
  ACT_FUNCTIONS.GetProvTaxAmountDoc(DOC.ACT_DOCUMENT_ID,PROCPARAM_0) PROV_TAX_AMOUNT_DOC,
  ACT_FUNCTIONS.GetProvTaxAmountDet(TAX.ACT_DET_TAX_ID,PROCPARAM_0) PROV_TAX_AMOUNT_TAX,
  IMF.ACT_PART_IMPUTATION_ID,
  IMF.ACS_AUXILIARY_ACCOUNT_ID,
  DOC.ACT_JOURNAL_ID,
  JOU.JOU_NUMBER,
  JOU.JOU_DESCRIPTION,
  ACS_FUNCTION.GetAccountNumber(ACT_FUNCTIONS.AuxAccountFromImputation(IMF.ACT_FINANCIAL_IMPUTATION_ID)) AUXILIARY_ACCOUNT,
  ACS_FUNCTION.GetAuxAccOwnerName(ACT_FUNCTIONS.AuxAccountFromImputation(IMF.ACT_FINANCIAL_IMPUTATION_ID)) AUXILIARY_DESCR
FROM
  ACT_JOURNAL JOU,
  ACT_FINANCIAL_IMPUTATION IMT,
  ACT_DOCUMENT DOC,
  ACT_FINANCIAL_IMPUTATION IMF,
  ACT_DET_TAX TAX
WHERE
  TAX.ACT_ACT_FINANCIAL_IMPUTATION = IMT.ACT_FINANCIAL_IMPUTATION_ID(+) AND
  TAX.ACT_FINANCIAL_IMPUTATION_ID = IMF.ACT_FINANCIAL_IMPUTATION_ID AND
  IMF.ACT_DOCUMENT_ID = DOC.ACT_DOCUMENT_ID AND
  TAX.TAX_TMP_VAT_ENCASHMENT = '1' AND
  TAX.TAX_INCLUDED_EXCLUDED <> 'R' AND
  DOC.ACT_JOURNAL_ID = JOU.ACT_JOURNAL_ID AND
  NVL(trunc(IMF.IMF_TRANSACTION_DATE),TRUNC(IMT.IMF_TRANSACTION_DATE))<= trunc(to_date(PROCPARAM_0,'YYYYMMDD')) AND
  ACT_FUNCTIONS.GetProvTaxAmountDet(TAX.ACT_DET_TAX_ID,PROCPARAM_0) <>0;
end RPT_ACR_VAT_PROVISION;
