--------------------------------------------------------
--  DDL for Procedure RPT_FAM_INSURANCE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_FAM_INSURANCE" (
 aRefCursor       IN OUT CRYSTAL_CURSOR_TYPES.DualCursorTyp,
 PROCUSER_LANID   IN     pcs.pc_lang.lanid%type,
 PARAMETER_0      IN     VARCHAR2,
 PARAMETER_1      IN     VARCHAR2,
 PARAMETER_2      IN     VARCHAR2,
 PARAMETER_3      IN     VARCHAR2
)
IS

/**
*Description
Used for report FAM_INSURANCE

*author JLI
*lastUpdate 3 feb 2010
* @public
* @param PARAMETER_0          POLICY_NUMBER(FROM)
* @param PARAMETER_1          POLICY_NUMBER(TO)
* @param PARAMETER_2          Regroupement : 0 = sans, 1= Division, 2= CDA
* @param PARAMETER_3          FIX ASSET STATUS LIST
*/

VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;


BEGIN


pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;



open aRefCursor for

SELECT
CDA.ACS_ACCOUNT_ID,
CDA.ACC_NUMBER,
DIV.ACS_ACCOUNT_ID ACS_ACCOUNT_ID_DIV,
DIV.ACC_NUMBER ACC_NUMBER_DIV,
FIX.FIX_NUMBER,
FIX.FIX_SHORT_DESCR,
FIX.FIX_PURCHASE_DATE,
FIX.C_FIXED_ASSETS_STATUS,
SUR.INS_DECLARED_VALUE,
SUR.INS_EFFECTIVE_VALUE,
SUR.INS_NEW_VALUE,
SUR.INS_PREMIUM,
SUR.INS_PREMIUM_RATE,
POL.POL_NUMBER,
POL.POL_PREMIUM,
POL.POL_INDEX,
POL.POL_DESIGNATION,
ACS_FUNCTION.GetAccountDescriptionSummary(DECODE(PARAMETER_2,0,0
                                                 ,1,DECODE(DIV.ACS_ACCOUNT_ID,NULL,0,DIV.ACS_ACCOUNT_ID)
                                                 ,DECODE(CDA.ACS_ACCOUNT_ID,NULL,0,CDA.ACS_ACCOUNT_ID))) ACC_DES
FROM
ACS_ACCOUNT CDA,
ACS_ACCOUNT DIV,
FAM_FIXED_ASSETS FIX,
FAM_INSURANCE SUR,
FAM_INSURANCE_POLICY POL
WHERE
POL.FAM_INSURANCE_POLICY_ID = SUR.FAM_INSURANCE_POLICY_ID
AND SUR.FAM_FIXED_ASSETS_ID = FIX.FAM_FIXED_ASSETS_ID
AND FIX.ACS_DIVISION_ACCOUNT_ID = DIV.ACS_ACCOUNT_ID(+)
AND FIX.ACS_CDA_ACCOUNT_ID = CDA.ACS_ACCOUNT_ID(+)
AND ((PARAMETER_0 IS NULL AND PARAMETER_1 IS NULL)
    OR (PARAMETER_0 IS NOT NULL AND PARAMETER_1 IS NULL AND POL.POL_NUMBER >= PARAMETER_0)
    OR (PARAMETER_1 IS NOT NULL AND PARAMETER_0 IS NULL AND POL.POL_NUMBER <= PARAMETER_1)
    OR (PARAMETER_0 IS NOT NULL AND PARAMETER_1 IS NOT NULL AND POL.POL_NUMBER >= PARAMETER_0 AND POL.POL_NUMBER <= PARAMETER_1))
AND instr( ',' || PARAMETER_3 || ',' ,  ',' || FIX.C_FIXED_ASSETS_STATUS ||',' ) > 0 ;


END RPT_FAM_INSURANCE;
