--------------------------------------------------------
--  DDL for Procedure RPT_ACS_ACCOUNTING_PLAN_STR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACS_ACCOUNTING_PLAN_STR" (
   arefcursor       IN OUT   crystal_cursor_types.dualcursortyp,
   procuser_lanid   IN       pcs.pc_lang.lanid%TYPE,
   PARAMETER_1      IN       VARCHAR2,
   PARAMETER_2      IN       VARCHAR2,
   PARAMETER_3      IN       VARCHAR2
)
/**
*Description

 Used for report ACS_ACCOUNTING_PLAN_STR
*@created JLIU 30.JULY.2009
*@lastUpdate MAY 2010
*@public
*@PARAM PARAMETER_1    CLASSIFICATION ID LIST
*@PARAM PARAMETER_2    ACCCOUNT NUMBER (FROM)
*@PARAM PARAMETER_3    ACCCOUNT NUMBER (TO)
*/

IS

   vpc_lang_id   pcs.pc_lang.pc_lang_id%TYPE;              --user language id
BEGIN
   pcs.PC_I_LIB_SESSION.setlanid (procuser_lanid);
   vpc_lang_id := pcs.PC_I_LIB_SESSION.getuserlangid;


  OPEN arefcursor FOR
  SELECT
    ACC_DES.ACC_NUMBER,
    ACC_DES.ACC_BLOCKED,
    ACC_DES.ACC_VALID_TO,
    ACC_DES.ACC_VALID_SINCE,
    ACC_DES.ACS_FINANCIAL_ACCOUNT_ID,
    ACC_DES.FIN_COLLECTIVE,
    ACC_DES.DES_DESCRIPTION_SUMMARY,
    ACC_DES.DES_DESCRIPTION_LARGE,
    CLN_DES.DES_DESCR NODE_DESCR,
    FLA.NODE01,
    FLA.NODE02,
    FLA.NODE03,
    FLA.NODE04,
    FLA.NODE05,
    FLA.NODE06,
    FLA.NODE07,
    FLA.NODE08,
    FLA.NODE09,
    FLA.NODE10,
    FLA.PC_LANG_ID,
    FLA.LEAF_DESCR,
    CLA.CLASSIFICATION_ID
   FROM
    CLASSIF_FLAT FLA,
    CLASSIFICATION CLA,
    (SELECT
    CLN.CLASSIF_NODE_ID,
    DES.DES_DESCR
    FROM
    CLASSIF_NODE CLN,
    CLASSIF_NODE_DESCR DES
    WHERE
    CLN.CLASSIF_NODE_ID = DES.CLASSIF_NODE_ID
    AND DES.PC_LANG_ID = vpc_lang_id) CLN_DES,
    (
    SELECT
    ACS.ACS_ACCOUNT_ID,
    ACS.ACC_NUMBER,
    ACS.ACC_BLOCKED,
    ACS.ACC_VALID_TO,
    ACS.ACC_VALID_SINCE,
    FCC.ACS_FINANCIAL_ACCOUNT_ID,
    FCC.FIN_COLLECTIVE,
    DES.DES_DESCRIPTION_SUMMARY,
    DES.DES_DESCRIPTION_LARGE
    FROM
    ACS_ACCOUNT ACS,
    ACS_DESCRIPTION DES,
    ACS_FINANCIAL_ACCOUNT FCC
    WHERE
    ACS.ACS_ACCOUNT_ID = FCC.ACS_FINANCIAL_ACCOUNT_ID
    AND ACS.ACS_ACCOUNT_ID = DES.ACS_ACCOUNT_ID
    AND DES.PC_LANG_ID = vpc_lang_id
    ) ACC_DES
   WHERE
    CLA.CLASSIFICATION_ID = FLA.CLASSIFICATION_ID
    AND FLA.CFL_NODE_ID = CLN_DES.CLASSIF_NODE_ID(+)
    AND FLA.CLASSIF_LEAF_ID = ACC_DES.ACS_ACCOUNT_ID(+)
    AND FLA.PC_LANG_ID = vpc_lang_id
    AND INSTR(';' || PARAMETER_1 ||';', ';' || CLA.CLASSIFICATION_ID ||';' ) > 0
    AND ACC_DES.ACC_NUMBER >= NVL(PARAMETER_2,'00000')
    AND ACC_DES.ACC_NUMBER <= NVL(PARAMETER_3,'ZZZZZ')
   ORDER BY
   FLA.NODE01 NULLS FIRST,
    FLA.NODE02 NULLS FIRST,
    FLA.NODE03 NULLS FIRST,
    FLA.NODE04 NULLS FIRST,
    FLA.NODE05 NULLS FIRST,
    FLA.NODE06 NULLS FIRST,
    FLA.NODE07 NULLS FIRST,
    FLA.NODE08 NULLS FIRST,
    FLA.NODE09 NULLS FIRST,
    FLA.NODE10 NULLS FIRST
    ;

END RPT_ACS_ACCOUNTING_PLAN_STR ;
