--------------------------------------------------------
--  DDL for Procedure RPT_ACT_JOURNAL_GEN_SUB
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACT_JOURNAL_GEN_SUB" (
  aRefCursor             in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
--, PARAMETER_1            in     VARCHAR2
, PARAMETER_2            in     VARCHAR2
, PROCUSER_LANID         in     pcs.pc_lang.lanid%type
)

/**
* description used for report act_journal_gen.rpt

* @author jliu 18 nov 2008
* @lastupdate 12 Feb 2009
* @public
--* @PARAM PARAMETER_1    PC_USELANG_ID
* @PARAM PARAMETER_2    ACT_JOURNAL_ID
*/

is

VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;


begin

pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;

open aRefCursor for
SELECT
ACC_DIV.ACC_NUMBER DIV_NUMBER,
ACC_FIN.ACC_NUMBER FIN_NUMBER,
DES_DIV.PC_LANG_ID DIV_PC_LAN_ID,
DES_DIV.DES_DESCRIPTION_SUMMARY DIV_DESCRIPTION_SUMMARY,
DES_FIN.PC_LANG_ID FIN_PC_LAN_ID,
DES_FIN.DES_DESCRIPTION_SUMMARY FIN_DESCRIPTION_SUMMARY,
FUR_MB.PC_CURR_ID MB_CURR_ID,
FUR_ME.PC_CURR_ID ME_CURR_ID,
IMP.IMF_AMOUNT_LC_D,
IMP.IMF_AMOUNT_LC_C,
IMP.IMF_AMOUNT_FC_D,
IMP.IMF_AMOUNT_FC_C,
CUR_MB.CURRENCY CURRENCY_MB,
CUR_ME.CURRENCY CURRENCY_ME,
JOU.ACT_JOURNAL_ID,
JOU.C_SUB_SET
FROM
ACT_FINANCIAL_IMPUTATION IMP,
ACT_FINANCIAL_DISTRIBUTION DIS,
ACS_ACCOUNT ACC_DIV,
ACS_DESCRIPTION DES_DIV,
ACT_DOCUMENT ATD,
V_ACT_JOURNAL JOU,
ACS_ACCOUNT ACC_FIN,
ACS_DESCRIPTION DES_FIN,
ACS_FINANCIAL_CURRENCY FUR_MB,
ACS_FINANCIAL_CURRENCY FUR_ME,
PCS.PC_CURR CUR_MB,
PCS.PC_CURR CUR_ME
WHERE
IMP.ACT_FINANCIAL_IMPUTATION_ID = DIS.ACT_FINANCIAL_IMPUTATION_ID(+)
AND DIS.ACS_DIVISION_ACCOUNT_ID = ACC_DIV.ACS_ACCOUNT_ID(+)
AND ACC_DIV.ACS_ACCOUNT_ID = DES_DIV.ACS_ACCOUNT_ID(+)
AND IMP.ACT_DOCUMENT_ID = ATD.ACT_DOCUMENT_ID
AND ATD.ACT_JOURNAL_ID = JOU.ACT_JOURNAL_ID
AND IMP.ACS_FINANCIAL_ACCOUNT_ID = ACC_FIN.ACS_ACCOUNT_ID
AND ACC_FIN.ACS_ACCOUNT_ID = DES_FIN.ACS_ACCOUNT_ID(+)
AND IMP.ACS_FINANCIAL_CURRENCY_ID = FUR_ME.ACS_FINANCIAL_CURRENCY_ID(+)
AND IMP.ACS_ACS_FINANCIAL_CURRENCY_ID = FUR_MB.ACS_FINANCIAL_CURRENCY_ID(+)
AND FUR_ME.PC_CURR_ID = CUR_ME.PC_CURR_ID(+)
AND FUR_MB.PC_CURR_ID = CUR_MB.PC_CURR_ID(+)
AND JOU.C_SUB_SET = 'ACC'
AND JOU.ACT_JOURNAL_ID = TO_NUMBER(PARAMETER_2)
AND DES_FIN.PC_LANG_ID = VPC_LANG_ID
AND ((DES_DIV.PC_LANG_ID IS NULL )OR (DES_DIV.PC_LANG_ID IS NOT NULL AND DES_DIV.PC_LANG_ID = VPC_LANG_ID))
;
END RPT_ACT_JOURNAL_GEN_SUB;
