--------------------------------------------------------
--  DDL for Procedure RPT_FAM_CATALOGUE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_FAM_CATALOGUE" (
 aRefCursor       in out CRYSTAL_CURSOR_TYPES.DualCursorTyp,
 PROCUSER_LANID   in     pcs.pc_lang.lanid%type
)
IS

/**
*Description
Used for the report FAM_CATALOGUE

*author JLI
*lastUpdate July 23 2009
* @public
*/

VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;


BEGIN


pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;



open aRefCursor for

SELECT
TSC.ACJ_JOB_TYPE_ID,
TSC.ACJ_CATALOGUE_DOCUMENT_ID,
TSC_2.ACJ_JOB_TYPE_ID ACJ_JOB_TYPE_ID_2,
TSC_2.ACJ_CATALOGUE_DOCUMENT_ID ACJ_CATALOGUE_DOCUMENT_ID_2,
MVL.FAM_MANAGED_VALUE_ID,
MVL.CMV_AMOUNTS_PILOT_FORMULA,
FCG.FAM_CATALOGUE_ID,
FCG.C_FAM_TRANSACTION_TYP,
FCG.FCA_KEY,
FCG.FCA_DESCR,
FCG.FCA_AVAILABLE,
FCG.FCA_DEBIT,
FCG.ACJ_NUMBER_METHOD_ID,
FCG.DIC_FAM_FCA_FREECOD1_ID,
FCG.DIC_FAM_FCA_FREECOD2_ID,
FCG.DIC_FAM_FCA_FREECOD3_ID,
FCG.DIC_FAM_FCA_FREECOD4_ID,
FCG.DIC_FAM_FCA_FREECOD5_ID,
FCG.DIC_FAM_FCA_FREECOD6_ID,
FCG.DIC_FAM_FCA_FREECOD7_ID,
FCG.DIC_FAM_FCA_FREECOD8_ID,
FCG.DIC_FAM_FCA_FREECOD9_ID,
FCG.DIC_FAM_FCA_FREECOD10_ID,
VAL.VAL_DESCR
FROM
FAM_CATALOGUE FCG,
ACJ_JOB_TYPE_S_CATALOGUE TSC,
ACJ_JOB_TYPE_S_CATALOGUE TSC_2,
FAM_CAT_MANAGED_VALUE MVL,
FAM_MANAGED_VALUE VAL
WHERE
FCG.ACJ_JOB_TYPE_S_CATALOGUE_ID = TSC.ACJ_JOB_TYPE_S_CATALOGUE_ID(+)
AND FCG.ACJ_JOB_TYPE_S_CATALOGUE2_ID = TSC_2.ACJ_JOB_TYPE_S_CATALOGUE_ID(+)
AND FCG.FAM_CATALOGUE_ID = MVL.FAM_CATALOGUE_ID(+)
AND MVL.FAM_MANAGED_VALUE_ID = VAL.FAM_MANAGED_VALUE_ID(+);

END RPT_FAM_CATALOGUE;
