--------------------------------------------------------
--  DDL for Procedure RPT_DOC_STD_2
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_DOC_STD_2" (
  aRefCursor  in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, PARAMETER_0 in     DOC_DOCUMENT.DMT_NUMBER%type
)
is
/**
* procedure RPT_DOC_STD_2
* Description
*   Procédure stockée utilisée pour le rapport DOC_STD_2.RPT (Document standard)
*  replace the procedure DOC_STD_2_RPT
* @created David Saadé 18.01.2007
* @param PARAMETER_0    Numéro de document    (DMT_NUMBER)
*/
begin
  open aRefCursor
   for
     select    DMT.DOC_DOCUMENT_ID
          , DMT.DMT_NUMBER DOCNUMBER
          , DETAIL.DMT_NUMBER
          , DMT.DMT_DATE_DOCUMENT
          , DMT.DMT_DATE_VALUE
          , DMT.DMT_DATE_FALLING_DUE
          , DMT.DMT_DATE_DELIVERY
          , DMT.C_DOCUMENT_STATUS
          , DMT.DMT_PARTNER_NUMBER
          , DMT.DMT_PARTNER_REFERENCE
          , DMT.DMT_DATE_PARTNER_DOCUMENT
          , DMT.DMT_REFERENCE
          , DMT.DMT_TITLE_TEXT
          , DMT.DMT_HEADING_TEXT
          , DMT.DMT_DOCUMENT_TEXT
          , DMT.DIC_DOC_FREE_1_ID
          , DMT.DIC_DOC_FREE_2_ID
          , DMT.DIC_DOC_FREE_3_ID
          , DMT.DIC_TYPE_SUBMISSION_ID
          , DMT.DIC_POS_FREE_TABLE_1_ID DOC_DIC_POS_FREE_TABLE_1_ID
          , DMT.DIC_POS_FREE_TABLE_2_ID DOC_DIC_POS_FREE_TABLE_2_ID
          , DMT.DIC_POS_FREE_TABLE_3_ID DOC_DIC_POS_FREE_TABLE_3_ID
          , DMT.DMT_DECIMAL_1
          , DMT.DMT_DECIMAL_2
          , DMT.DMT_DECIMAL_3
          , DMT.DMT_TEXT_1
          , DMT.DMT_TEXT_2
          , DMT.DMT_TEXT_3
          , DMT.DMT_DATE_1
          , DMT.DMT_DATE_2
          , DMT.DMT_DATE_3
          , DMT.DIC_GAUGE_FREE_CODE_1_ID
          , DMT.DIC_GAUGE_FREE_CODE_2_ID
          , DMT.DIC_GAUGE_FREE_CODE_3_ID
          , DMT.DMT_GAU_FREE_NUMBER1
          , DMT.DMT_GAU_FREE_NUMBER2
          , DMT.DMT_GAU_FREE_DATE1
          , DMT.DMT_GAU_FREE_DATE2
          , DMT.DMT_GAU_FREE_TEXT_LONG
          , DMT.DMT_GAU_FREE_TEXT_SHORT
          , DMT.DMT_GAU_FREE_BOOL1
          , DMT.DMT_GAU_FREE_BOOL2
          , DMT.DIC_TARIFF_ID
          , DMT.C_INCOTERMS
          , DMT.DMT_INCOTERMS_PLACE
          , REP.PAC_REPRESENTATIVE_ID
          , REP.REP_DESCR
          , REC.DIC_ACCOUNTABLE_GROUP_ID
          , REC.RCO_TITLE
          , REC.RCO_DESCRIPTION
          , DMT.PAC_THIRD_ID
          , THI.DIC_THIRD_ACTIVITY_ID
          , THI.DIC_THIRD_AREA_ID
          , THI.THI_NO_INTRA
          , THI.THI_NO_TVA
          , THI.THI_NO_SIREN
          , THI.THI_NO_SIRET
          , THI.THI_NO_FORMAT
          , CUS.C_DELIVERY_TYP
          , CUS.CUS_SUPPLIER_NUMBER
          , CUS.CUS_FREE_ZONE1
          , CUS.CUS_FREE_ZONE2
          , CUS.CUS_FREE_ZONE3
          , CUS.CUS_FREE_ZONE4
          , CUS.CUS_FREE_ZONE5
          , CUS.DIC_STATISTIC_1_ID
          , CUS.DIC_STATISTIC_2_ID
          , CUS.DIC_STATISTIC_3_ID
          , CUS.DIC_STATISTIC_4_ID
          , CUS.DIC_STATISTIC_5_ID
          , CUS.DIC_TYPE_PARTNER_ID
          , SUP.CRE_CUSTOMER_NUMBER
          , SUP.CRE_FREE_ZONE1
          , SUP.CRE_FREE_ZONE2
          , SUP.CRE_FREE_ZONE3
          , SUP.CRE_FREE_ZONE4
          , SUP.CRE_FREE_ZONE5
          , SUP.DIC_STATISTIC_F1_ID
          , SUP.DIC_STATISTIC_F2_ID
          , SUP.DIC_STATISTIC_F3_ID
          , SUP.DIC_STATISTIC_F4_ID
          , SUP.DIC_STATISTIC_F5_ID
          , SUP.DIC_TYPE_PARTNER_F_ID
          , PSC.PAC_SENDING_CONDITION_ID
          , PSC.PAC_ADDRESS_ID SENDING_ADDRESS_ID
          , PER_SEN.PER_NAME SEN_PER_NAME
          , PER_SEN.PER_FORENAME SEN_PER_FORENAME
          , PER_SEN.PER_ACTIVITY SEN_PER_ACTIVITY
          , PER_SEN.PER_COMMENT SEN_PER_COMMENT
          , PER_SEN.PER_KEY1 SEN_PER_KEY1
          , PER_SEN.PER_KEY2 SEN_PER_KEY2
          , ADR_SEN.ADD_ADDRESS1 SEN_ADD_ADDRESS1
          , ADR_SEN.ADD_FORMAT SEN_ADD_FORMAT
          , APM.ACS_PAYMENT_METHOD_ID
          , ACCC.ACC_NUMBER CUSTOMER_ACCOUNT
          , ACCS.ACC_NUMBER SUPPLIER_ACCOUNT
          , DMT.PC_LANG_ID
          , PMT.PAC_PAYMENT_CONDITION_ID
          , PMT.PCO_DESCR
          , PMT.PC_APPLTXT_ID PMT_PC_APPLTXT_ID
          , AFC.ACS_FINANCIAL_CURRENCY_ID
          , CUR.CURRENCY
          , CUR.CURRNAME
          , LANG.LANID
          , DMT.PAC_ADDRESS_ID ADDRESS_ID
          , nvl(DMT.DMT_NAME1,PER.PER_NAME) PER_NAME
          , nvl(DMT.DMT_FORENAME1,PER.PER_FORENAME) PER_FORENAME
          , nvl(DMT.DMT_ACTIVITY1,PER.PER_ACTIVITY) PER_ACTIVITY
          , PER.PER_COMMENT
          , PER.PER_KEY1
          , PER.PER_KEY2
          , DMT.DMT_ADDRESS1
          , DMT.DMT_FORMAT_CITY1
          , DMT.DMT_TOWN1
          , CNT.CNTID
          , CNT.CNTNAME
          , CNT.DIC_PC_CNTRY_GRP_ID
          , CNT.CNT_CE_CODE
          , CNT.CNT_CE_MEMBER
          , DMT.PAC_PAC_ADDRESS_ID ADDRESS2_ID
          , nvl(DMT.DMT_NAME2,PER2.PER_NAME) PER2_NAME
          , nvl(DMT.DMT_FORENAME2,PER2.PER_FORENAME) PER2_FORENAME
          , nvl(DMT.DMT_ACTIVITY2,PER2.PER_ACTIVITY) PER2_ACTIVITY
          , PER2.PER_COMMENT PER2_COMMENT
          , PER2.PER_KEY1 PER2_KEY1
          , PER2.PER_KEY2 PER2_KEY2
          , DMT.DMT_ADDRESS2
          , DMT.DMT_FORMAT_CITY2
          , DMT.DMT_TOWN2
          , CNT2.CNTID CNTID2
          , CNT2.CNTNAME CNTNAME2
          , CNT2.DIC_PC_CNTRY_GRP_ID DIC_PC_CNTRY_GRP_ID2
          , CNT2.CNT_CE_CODE CNT_CE_CODE2
          , CNT2.CNT_CE_MEMBER CNT_CE_MEMBER2
          , DMT.PAC2_PAC_ADDRESS_ID ADDRESS3_ID
          , nvl(DMT.DMT_NAME3,PER3.PER_NAME) PER3_NAME
          , nvl(DMT.DMT_FORENAME3,PER3.PER_FORENAME) PER3_FORENAME
          , nvl(DMT.DMT_ACTIVITY3,PER3.PER_ACTIVITY) PER3_ACTIVITY
          , PER3.PER_COMMENT PER3_COMMENT
          , PER3.PER_KEY1 PER3_KEY1
          , PER3.PER_KEY2 PER3_KEY2
          , DMT.DMT_ADDRESS3
          , DMT.DMT_FORMAT_CITY3
          , DMT.DMT_TOWN3
          , CNT3.CNTID CNTID3
          , CNT3.CNTNAME CNTNAME3
          , CNT3.DIC_PC_CNTRY_GRP_ID DIC_PC_CNTRY_GRP_ID3
          , CNT3.CNT_CE_CODE CNT_CE_CODE3
          , CNT3.CNT_CE_MEMBER CNT_CE_MEMBER3
          , GAU.C_GAUGE_TYPE
          , GST.C_GAUGE_TITLE
          , GST.GAS_FINANCIAL_CHARGE
          , GAU.C_ADMIN_DOMAIN
          , GAU.DIC_GAUGE_TYPE_DOC_ID
          , DFD.DIC_DOC_FREE_TABLE_1_ID
          , DFD.DIC_DOC_FREE_TABLE_2_ID
          , DFD.DIC_DOC_FREE_TABLE_3_ID
          , DFD.DIC_DOC_FREE_TABLE_4_ID
          , DFD.DIC_DOC_FREE_TABLE_5_ID
          , DFD.FRD_ALPHA_SHORT_1
          , DFD.FRD_ALPHA_SHORT_2
          , DFD.FRD_ALPHA_SHORT_3
          , DFD.FRD_ALPHA_SHORT_4
          , DFD.FRD_ALPHA_SHORT_5
          , DFD.FRD_ALPHA_LONG_1
          , DFD.FRD_ALPHA_LONG_2
          , DFD.FRD_ALPHA_LONG_3
          , DFD.FRD_ALPHA_LONG_4
          , DFD.FRD_ALPHA_LONG_5
          , DFD.FRD_INTEGER_1
          , DFD.FRD_INTEGER_2
          , DFD.FRD_INTEGER_3
          , DFD.FRD_INTEGER_4
          , DFD.FRD_INTEGER_5
          , DFD.FRD_DECIMAL_1
          , DFD.FRD_DECIMAL_2
          , DFD.FRD_DECIMAL_3
          , DFD.FRD_DECIMAL_4
          , DFD.FRD_DECIMAL_5
          , DFD.FRD_BOOLEAN_1
          , DFD.FRD_BOOLEAN_2
          , DFD.FRD_BOOLEAN_3
          , DFD.FRD_BOOLEAN_4
          , DFD.FRD_BOOLEAN_5
          , FOO.DOC_FOOT_ID
          , FOO.DOC_GAUGE_SIGNATORY_ID
          , DGS.GAG_NAME
          , DGS.GAG_FUNCTION
          , FOO.DOC_DOC_GAUGE_SIGNATORY_ID
          , DGS2.GAG_NAME GAG2_NAME
          , DGS2.GAG_FUNCTION GAG2_FUNCTION
          , FOO.FOO_FOOT_TEXT
          , FOO.FOO_FOOT_TEXT2
          , FOO.FOO_FOOT_TEXT3
          , FOO.FOO_FOOT_TEXT4
          , FOO.FOO_FOOT_TEXT5
          , FOO.FOO_DOCUMENT_TOTAL_AMOUNT
          , FOO.FOO_GOOD_TOTAL_AMOUNT
          , FOO.FOO_TOTAL_VAT_AMOUNT
          , FOO.FOO_CHARGE_TOTAL_AMOUNT
          , FOO.FOO_DISCOUNT_TOTAL_AMOUNT
          , FOO.FOO_COST_TOTAL_AMOUNT
          , FOO.FOO_GOOD_TOT_AMOUNT_EXCL
          , FOO.FOO_CHARG_TOT_AMOUNT_EXCL
          , FOO.FOO_DISC_TOT_AMOUNT_EXCL
          , FOO.FOO_COST_TOT_AMOUNT_EXCL
          , FOO.FOO_TOTAL_NET_WEIGHT
          , FOO.FOO_TOTAL_GROSS_WEIGHT
          , FOO.FOO_TOTAL_BASIS_QUANTITY
          , FOO.FOO_TOTAL_INTERM_QUANTITY
          , FOO.FOO_TOTAL_FINAL_QUANTITY
          , FOO.C_BVR_GENERATION_METHOD
          , FOO.FOO_GENERATE_BVR_NUMBER
          , FOO.FOO_REF_BVR_NUMBER
          , FOO.FOO_DOCUMENT_TOT_AMOUNT_B
          , FOO.FOO_DOCUMENT_TOT_AMOUNT_E
          , FOO.FOO_PAID_AMOUNT
          , FOO.FOO_RETURN_AMOUNT
          , FOO.FOO_PACKAGING
          , FOO.FOO_MARKING
          , FOO.FOO_MEASURE
          , FOO.DIC_TYPE_DOC_CUSTOM_ID
          , FOO.C_DIRECTION_NUMBER
          , FOO.FOO_TOT_VAT_AMOUNT_V
          , FOO.FOO_RECEIVED_AMOUNT
          , FOO.FOO_PAID_BALANCED_AMOUNT
          , POS.DOC_POSITION_ID
          , POS.POS_NUMBER
          , POS.C_DOC_POS_STATUS
          , POS.C_GAUGE_TYPE_POS
          , GOO.GCO_GOOD_ID
          , GOO.GOO_MAJOR_REFERENCE
          , GOO.GOO_SECONDARY_REFERENCE
          , GOO.GOO_NUMBER_OF_DECIMAL GOOD_NUMBER_OF_DECIMAL
          , case GAU.C_ADMIN_DOMAIN
              when '1' then GCO_FUNCTIONS.GETCDADECIMAL(POS.GCO_GOOD_ID, 'PURCHASE', THI.PAC_THIRD_ID)
              when '2' then GCO_FUNCTIONS.GETCDADECIMAL(POS.GCO_GOOD_ID, 'SALE', THI.PAC_THIRD_ID)
              else GCO_FUNCTIONS.GETCDADECIMAL(POS.GCO_GOOD_ID, ' ', THI.PAC_THIRD_ID)
            end GOO_NUMBER_OF_DECIMAL
          , GOO.DIC_GOOD_LINE_ID
          , GOO.DIC_GOOD_FAMILY_ID
          , GOO.DIC_GOOD_MODEL_ID
          , GOO.DIC_GOOD_GROUP_ID
          , PDT.PDT_STOCK_MANAGEMENT
          , DGP.C_GAUGE_SHOW_DELAY
          , DGP.GAP_POS_DELAY
          , POS.POS_REFERENCE
          , POS.POS_SHORT_DESCRIPTION
          , POS.POS_LONG_DESCRIPTION
          , POS.POS_FREE_DESCRIPTION
          , POS.POS_BODY_TEXT
          , POS.ASA_RECORD_ID
          , POS.ASA_RECORD_TASK_ID
          , POS.ASA_RECORD_COMP_ID
          , TVA.ACC_NUMBER TVA_ACC_NUMBER
          , REC_POS.RCO_TITLE POS_RCO_TITLE
          , REC_POS.DIC_ACCOUNTABLE_GROUP_ID POS_DIC_ACCOUNTABLE_GROUP_ID
          , REC_POS.RCO_DESCRIPTION POS_RCO_DESCRIPTION
          , REP_POS.PAC_REPRESENTATIVE_ID POS_PAC_REPRESENTATIVE_ID
          , REP_POS.REP_DESCR POS_REP_DESCR
          , GCE.CUS_CUSTONS_POSITION
          , GCE.CUS_KEY_TARIFF
          , GCE.CUS_LICENCE_NUMBER
          , GCE.CUS_RATE_FOR_VALUE
          , GCE.CUS_TRANSPORT_INFORMATION
          , GCE.DIC_REPAYMENT_CODE_ID
          , GCE.DIC_SUBJUGATED_LICENCE_ID
          , CNT_CUSTOMS.CNTID CNTID_CUSTOMS
          , CNT_CUSTOMS.CNTNAME CNTNAME_CUSTOMS
          , CNT_CUSTOMS.DIC_PC_CNTRY_GRP_ID DIC_PC_CNTRY_GRP_ID_CUSTOMS
          , CNT_CUSTOMS.CNT_CE_CODE CNT_CE_CODE_CUSTOMS
          , CNT_CUSTOMS.CNT_CE_MEMBER CNT_CE_MEMBER_CUSTOMS
          , CNT_ORIGIN.CNTID CNTID_ORIGIN
          , CNT_ORIGIN.CNTNAME CNTNAME_ORIGIN
          , CNT_ORIGIN.DIC_PC_CNTRY_GRP_ID DIC_PC_CNTRY_GRP_ID_ORIGIN
          , CNT_ORIGIN.CNT_CE_CODE CNT_CE_CODE_ORIGIN
          , CNT_ORIGIN.CNT_CE_MEMBER CNT_CE_MEMBER_ORIGIN
          , GFD.DATA_UNIT_PRICE_SALE
          , GFD.DIC_FREE_TABLE_1_ID
          , GFD.DIC_FREE_TABLE_2_ID
          , GFD.DIC_FREE_TABLE_3_ID
          , GFD.DIC_FREE_TABLE_4_ID
          , GFD.DIC_FREE_TABLE_5_ID
          , POS.POS_DISCOUNT_AMOUNT
          , POS.POS_CHARGE_AMOUNT
          , POS.POS_VAT_AMOUNT
          , POS.POS_VAT_BASE_AMOUNT
          , POS.POS_GROSS_UNIT_VALUE
          , POS.POS_GROSS_UNIT_VALUE_SU
          , POS.POS_NET_UNIT_VALUE
          , POS.POS_NET_UNIT_VALUE_INCL
          , POS.POS_REF_UNIT_VALUE
          , POS.POS_GROSS_VALUE
          , POS.POS_NET_VALUE_EXCL
          , POS.POS_NET_VALUE_INCL
          , POS.POS_BASIS_QUANTITY
          , POS.POS_INTERMEDIATE_QUANTITY
          , POS.POS_FINAL_QUANTITY
          , case
              when(DMT.DMT_ADDENDUM_INDEX is not null)
              and (POS.C_DOC_POS_STATUS = '04') then POS.POS_ADDENDUM_QTY_BALANCED
              else POS.POS_BALANCE_QUANTITY
            end POS_BALANCE_QUANTITY
          , POS.POS_RATE_FACTOR
          , POS.POS_NET_WEIGHT
          , POS.POS_GROSS_WEIGHT
          , POS.DIC_UNIT_OF_MEASURE_ID
          , POS.POS_NOM_TEXT
          , POS.POS_UNIT_COST_PRICE
          , POS.POS_EAN_CODE
          , POS.POS_EAN_UCC14_CODE
          , POS.POS_HIBC_PRIMARY_CODE
          , POS.DIC_POS_FREE_TABLE_1_ID
          , POS.DIC_POS_FREE_TABLE_2_ID
          , POS.DIC_POS_FREE_TABLE_3_ID
          , POS.POS_DECIMAL_1
          , POS.POS_DECIMAL_2
          , POS.POS_DECIMAL_3
          , POS.POS_TEXT_1
          , POS.POS_TEXT_2
          , POS.POS_TEXT_3
          , POS.POS_DATE_1
          , POS.POS_DATE_2
          , POS.POS_DATE_3
          , POS.POS_DISCOUNT_UNIT_VALUE
          , POS.POS_DISCOUNT_RATE
          , POS.POS_VALUE_QUANTITY
          , POS.POS_INCLUDE_TAX_TARIFF
          , POS.POS_GROSS_UNIT_VALUE_INCL
          , POS.POS_GROSS_UNIT_VALUE_INCL_SU
          , POS.POS_GROSS_VALUE_INCL
          , POS.POS_BALANCE_QTY_VALUE
          , POS.POS_UTIL_COEFF
          , POS.POS_GROSS_UNIT_VALUE2
          , POS.DIC_DIC_UNIT_OF_MEASURE_ID
          , POS.POS_CONVERT_FACTOR2
          , POS.POS_VAT_AMOUNT_V
          , POS.POS_NET_TARIFF
          , POS.POS_SPECIAL_TARIFF
          , POS.POS_FLAT_RATE
          , POS.POS_BASIS_QUANTITY_SU
          , POS.POS_INTERMEDIATE_QUANTITY_SU
          , POS.POS_FINAL_QUANTITY_SU
          , POS.C_POS_DELIVERY_TYP
          , POS.POS_BALANCED
          , DETAIL.DOC_POSITION_DETAIL_ID
          , DETAIL.PERE_DOC_POSITION_DETAIL_ID
          , DETAIL.PERE_DMT_NUMBER
          , DETAIL.PERE_DMT_DATE_DOCUMENT
          , DETAIL.PERE_C_GAUGE_TITLE
          , DETAIL.PERE_DMT_PARTNER_NUMBER
          , DETAIL.PERE_DMT_PARTNTER_REFERENCE
          , DETAIL.PERE_DATE_PARTNER_DOCUMENT
          , DETAIL.G_PERE_DOC_POSITION_DETAIL_ID
          , DETAIL.G_PERE_DMT_NUMBER
          , DETAIL.G_PERE_DMT_DATE_DOCUMENT
          , DETAIL.G_PERE_C_GAUGE_TITLE
          , DETAIL.G_PERE_DMT_PARTNER_NUMBER
          , DETAIL.G_PERE_DMT_PARTNTER_REFERENCE
          , DETAIL.G_PERE_DATE_PARTNER_DOCUMENT
          , DETAIL.STM_LOCATION_ID
          , LOC.LOC_DESCRIPTION
          , STM.STO_DESCRIPTION
          , DETAIL.STM_STM_LOCATION_ID
          , LOC_LOC.LOC_DESCRIPTION LOC_LOC_DESCRIPTION
          , STM_STM.STO_DESCRIPTION STO_STO_DESCRIPTION
          , DETAIL.DIC_DELAY_UPDATE_TYPE_ID
          , DETAIL.PDE_DELAY_UPDATE_TEXT
          , DETAIL.GCO1_CHARACTERIZATION_ID
          , DETAIL.GCO2_CHARACTERIZATION_ID
          , DETAIL.GCO3_CHARACTERIZATION_ID
          , DETAIL.GCO4_CHARACTERIZATION_ID
          , DETAIL.GCO5_CHARACTERIZATION_ID
          , substr(GCO_FUNCTIONS.GetCharacDescr(DETAIL.GCO1_CHARACTERIZATION_ID, DMT.PC_LANG_ID), 1, 30)
                                                                                                      GCO1_CHARAC_DESCR
          , substr(GCO_FUNCTIONS.GetCharacDescr(DETAIL.GCO2_CHARACTERIZATION_ID, DMT.PC_LANG_ID), 1, 30)
                                                                                                      GCO2_CHARAC_DESCR
          , substr(GCO_FUNCTIONS.GetCharacDescr(DETAIL.GCO3_CHARACTERIZATION_ID, DMT.PC_LANG_ID), 1, 30)
                                                                                                      GCO3_CHARAC_DESCR
          , substr(GCO_FUNCTIONS.GetCharacDescr(DETAIL.GCO4_CHARACTERIZATION_ID, DMT.PC_LANG_ID), 1, 30)
                                                                                                      GCO4_CHARAC_DESCR
          , substr(GCO_FUNCTIONS.GetCharacDescr(DETAIL.GCO5_CHARACTERIZATION_ID, DMT.PC_LANG_ID), 1, 30)
                                                                                                      GCO5_CHARAC_DESCR
          , DETAIL.PDE_CHARACTERIZATION_VALUE_1
          , DETAIL.PDE_CHARACTERIZATION_VALUE_2
          , DETAIL.PDE_CHARACTERIZATION_VALUE_3
          , DETAIL.PDE_CHARACTERIZATION_VALUE_4
          , DETAIL.PDE_CHARACTERIZATION_VALUE_5
          , DETAIL.PDE_PIECE
          , DETAIL.PDE_SET
          , DETAIL.PDE_VERSION
          , DETAIL.PDE_CHRONOLOGICAL
          , DETAIL.PDE_STD_CHAR_1
          , DETAIL.PDE_STD_CHAR_2
          , DETAIL.PDE_STD_CHAR_3
          , DETAIL.PDE_STD_CHAR_4
          , DETAIL.PDE_STD_CHAR_5
          , DETAIL.PDE_BASIS_DELAY
          , DETAIL.PDE_BASIS_DELAY_M
          , DETAIL.PDE_BASIS_DELAY_W
          , DETAIL.PDE_BASIS_QUANTITY
          , DETAIL.PDE_BASIS_QUANTITY_SU
          , DETAIL.PDE_INTERMEDIATE_DELAY
          , DETAIL.PDE_INTERMEDIATE_DELAY_M
          , DETAIL.PDE_INTERMEDIATE_DELAY_W
          , DETAIL.PDE_INTERMEDIATE_QUANTITY
          , DETAIL.PDE_INTERMEDIATE_QUANTITY_SU
          , DETAIL.PDE_FINAL_DELAY
          , DETAIL.PDE_FINAL_DELAY_M
          , DETAIL.PDE_FINAL_DELAY_W
          , DETAIL.PDE_FINAL_QUANTITY
          , DETAIL.PDE_FINAL_QUANTITY_SU
          , DETAIL.PDE_BALANCE_QUANTITY
          , DETAIL.P_PDE_BALANCE_QUANTITY
          , DETAIL.P_PDE_BALANCE_QUANTITY_PARENT
          , DETAIL.P_PDE_BASIS_QUANTITY
          , DETAIL.P_PDE_BASIS_QUANTITY_SU
          , DETAIL.P_PDE_INTERMEDIATE_QUANTITY
          , DETAIL.P_PDE_INTERMEDIATE_QUANTITY_SU
          , DETAIL.P_PDE_FINAL_QUANTITY
          , DETAIL.P_PDE_FINAL_QUANTITY_SU
          , DETAIL.NEED_FAN_EXCEED_QTY
          , DETAIL.NEED_FAN_FREE_QTY
          , DETAIL.NEED_FAN_FULL_QTY
          , DETAIL.NEED_FAN_NETW_QTY
          , DETAIL.NEED_FAN_PREV_QTY
          , DETAIL.NEED_FAN_REALIZE_QTY
          , DETAIL.NEED_FAN_RETURN_QTY
          , DETAIL.NEED_FAN_STK_QTY
          , DETAIL.NEED_FAL_NETWORK_NEED_ID
          , DETAIL.SUPPLY_FAN_EXCEED_QTY
          , DETAIL.SUPPLY_FAN_FREE_QTY
          , DETAIL.SUPPLY_FAN_FULL_QTY
          , DETAIL.SUPPLY_FAN_NETW_QTY
          , DETAIL.SUPPLY_FAN_PREV_QTY
          , DETAIL.SUPPLY_FAN_REALIZE_QTY
          , DETAIL.SUPPLY_FAN_RETURN_QTY
          , DETAIL.SUPPLY_FAN_STK_QTY
          , DETAIL.SUPPLY_FAL_NETWORK_SUPPLY_ID
          , DETAIL.LOT_REFCOMPL
          , DETAIL.GOO_MAJOR_REFERENCE COMP_MAJOR_REFERENCE
          , DETAIL.SCS_SHORT_DESCR
          , DETAIL.SCS_LONG_DESCR
          , DETAIL.SCS_FREE_DESCR
          , FOO.FOO_TOTAL_NET_WEIGHT_MEAS
          , FOO.FOO_TOTAL_GROSS_WEIGHT_MEAS
          , POS.POS_TARIFF_SET
          , DMT.DOC_RECORD_ID
          , REC.RCO_SUPPLIER_SERIAL_NUMBER
          , DMT.PAC_THIRD_ACI_ID
          , DMT.PAC_THIRD_DELIVERY_ID
          , DMT.PAC_THIRD_TARIFF_ID
          , DMT.PAC_REPR_ACI_ID
          , DMT.PAC_REPR_DELIVERY_ID
          , DMT.PC_LANG_ACI_ID
          , DMT.PC_LANG_DELIVERY_ID
          , DMT.DMT_NAME1
          , DMT.DMT_FORENAME1
          , DMT.DMT_ACTIVITY1
          , DMT.DMT_CARE_OF1
          , DMT.DMT_PO_BOX1
          , DMT.DMT_PO_BOX_NBR1
          , DMT.DMT_COUNTY1
          , DMT.DMT_CONTACT1
          , DMT.DMT_NAME2
          , DMT.DMT_FORENAME2
          , DMT.DMT_ACTIVITY2
          , DMT.DMT_CARE_OF2
          , DMT.DMT_PO_BOX2
          , DMT.DMT_PO_BOX_NBR2
          , DMT.DMT_COUNTY2
          , DMT.DMT_CONTACT2
          , DMT.DMT_NAME3
          , DMT.DMT_FORENAME3
          , DMT.DMT_ACTIVITY3
          , DMT.DMT_CARE_OF3
          , DMT.DMT_PO_BOX3
          , DMT.DMT_PO_BOX_NBR3
          , DMT.DMT_COUNTY3
          , DMT.DMT_CONTACT3
          , case
              when nvl(DMT.DMT_PO_BOX2,nvl(DMT.DMT_PO_BOX1,0)) = nvl(DMT.DMT_PO_BOX1,0)
               and nvl(DMT.DMT_PO_BOX_NBR2,nvl(DMT.DMT_PO_BOX_NBR1,0)) = nvl(DMT.DMT_PO_BOX_NBR1,0)
               and nvl(DMT.DMT_COUNTY2,nvl(DMT.DMT_COUNTY1,0)) = nvl(DMT.DMT_COUNTY1,0)
               and nvl(DMT.DMT_ADDRESS2,nvl(DMT.DMT_ADDRESS1,0)) = nvl(DMT.DMT_ADDRESS1,0)
               and nvl(DMT.DMT_FORMAT_CITY2,nvl(DMT.DMT_FORMAT_CITY1,0)) = nvl(DMT.DMT_FORMAT_CITY1,0)
               and nvl(DMT.DMT_TOWN2,nvl(DMT.DMT_TOWN1,0)) = nvl(DMT.DMT_TOWN1,0)
               and nvl(CNT2.CNTID,nvl(CNT.CNTID,0)) = nvl(CNT.CNTID,0)
              then 1
              else 0
            end ADR_DO_LIKE_LIVR
          , case
              when nvl(DMT.DMT_PO_BOX3,nvl(DMT.DMT_PO_BOX1,0)) = nvl(DMT.DMT_PO_BOX1,0)
               and nvl(DMT.DMT_PO_BOX_NBR3,nvl(DMT.DMT_PO_BOX_NBR1,0)) = nvl(DMT.DMT_PO_BOX_NBR1,0)
               and nvl(DMT.DMT_COUNTY3,nvl(DMT.DMT_COUNTY1,0)) = nvl(DMT.DMT_COUNTY1,0)
               and nvl(DMT.DMT_ADDRESS3,nvl(DMT.DMT_ADDRESS1,0)) = nvl(DMT.DMT_ADDRESS1,0)
               and nvl(DMT.DMT_FORMAT_CITY3,nvl(DMT.DMT_FORMAT_CITY1,0)) = nvl(DMT.DMT_FORMAT_CITY1,0)
               and nvl(DMT.DMT_TOWN3,nvl(DMT.DMT_TOWN1,0)) = nvl(DMT.DMT_TOWN1,0)
               and nvl(CNT3.CNTID,nvl(CNT.CNTID,0)) = nvl(CNT.CNTID,0)
              then 1
              else 0
            end ADR_DO_LIKE_FACT
          , REC_PDE.RCO_TITLE PDE_RCO_TITLE
          , REC_PDE.RCO_SUPPLIER_SERIAL_NUMBER PDE_RCO_SUPPLIER_SERIAL_NUMBER
          , POS.CML_EVENTS_ID
          , CEV.ASA_COUNTER_STATEMENT_ID
          , CEV.CML_POSITION_SERVICE_DETAIL_ID
          , CEV.CML_POSITION_MACHINE_DETAIL_ID
          , CEV.CEV_COUNTER_BEGIN_QTY
          , CEV.CEV_COUNTER_END_QTY
          , CEV.CEV_COUNTER_BEGIN_DATE
          , CEV.CEV_COUNTER_END_DATE
          , CEV.CEV_FREE_QTY
          , CEV.CEV_GROSS_CONSUMED_QTY
          , CEV.CEV_NET_CONSUMED_QTY
          , CEV.CEV_BALANCE_QTY
          , CEV.CEV_INVOICING_QTY
          , CEV.CEV_GLOBAL_EVENT
          , CEV.CEV_RENEWAL_GENERATED
          , CPO.CML_POSITION_ID
          , CPO.CPO_SEQUENCE
          , CCO.CCO_NUMBER
          , case
              when POS.POS_ADDENDUM_SRC_POS_ID is null then 1
              else 0
            end POS_NEW
          , case
              when DETAIL.PDE_ADDENDUM_SRC_PDE_ID is null then 1
              else 0
            end PDE_NEW
          , case
              when POS_ADD.POS_BASIS_QUANTITY <> POS.POS_BASIS_QUANTITY then 1
              else 0
            end POS_BASIS_QTY_UPDATED
          , case
              when POS_ADD.POS_INTERMEDIATE_QUANTITY <> POS.POS_INTERMEDIATE_QUANTITY then 1
              else 0
            end POS_INTER_QTY_UPDATED
          , case
              when POS_ADD.POS_FINAL_QUANTITY <> POS.POS_FINAL_QUANTITY then 1
              else 0
            end POS_FINAL_QTY_UPDATED
          , case
              when POS_ADD.POS_NET_UNIT_VALUE <> POS.POS_NET_UNIT_VALUE then 1
              else 0
            end POS_PRICE_UPDATED
          , case
              when POS_ADD.POS_REFERENCE <> POS.POS_REFERENCE then 1
              else 0
            end POS_REF_UPDATED
          , case
              when POS_ADD.POS_SHORT_DESCRIPTION <> POS.POS_SHORT_DESCRIPTION then 1
              else 0
            end POS_SHORT_DES_UPDATED
          , case
              when POS_ADD.POS_LONG_DESCRIPTION <> POS.POS_LONG_DESCRIPTION then 1
              else 0
            end POS_LONG_DES_UPDATED
          , case
              when POS_ADD.POS_FREE_DESCRIPTION <> POS.POS_FREE_DESCRIPTION then 1
              else 0
            end POS_FREE_DES_UPDATED
          , case
              when PDE_ADD.PDE_BASIS_DELAY <> DETAIL.PDE_BASIS_DELAY then 1
              else 0
            end PDE_BASIS_DELAY_UPDATED
          , case
              when PDE_ADD.PDE_INTERMEDIATE_DELAY <> DETAIL.PDE_INTERMEDIATE_DELAY then 1
              else 0
            end PDE_INTER_DELAY_UPDATED
          , case
              when PDE_ADD.PDE_FINAL_DELAY <> DETAIL.PDE_FINAL_DELAY then 1
              else 0
            end PDE_FINAL_DELAY_UPDATED
       from PCS.PC_LANG LANG
          , STM_LOCATION LOC
          , STM_LOCATION LOC_LOC
          , ACS_FIN_ACC_S_PAYMENT AFA
          , ACS_PAYMENT_METHOD APM
          , ACS_ACCOUNT TVA
          , DOC_RECORD REC
          , DOC_RECORD REC_POS
          , DOC_RECORD REC_PDE
          , DOC_FOOT FOO
          , GCO_FREE_DATA GFD
          , GCO_CUSTOMS_ELEMENT GCE
          , PCS.PC_CNTRY CNT_CUSTOMS
          , PCS.PC_CNTRY CNT_ORIGIN
          , PAC_SENDING_CONDITION PSC
          , PAC_PAYMENT_CONDITION PMT
          , ACS_FINANCIAL_CURRENCY AFC
          , DOC_FREE_DATA DFD
          , DOC_GAUGE_SIGNATORY DGS
          , DOC_GAUGE_SIGNATORY DGS2
          , DOC_GAUGE_POSITION DGP
          , PAC_CUSTOM_PARTNER CUS
          , ACS_ACCOUNT ACCC
          , PAC_ADDRESS ADR
          , PAC_ADDRESS ADR2
          , PAC_ADDRESS ADR3
          , PAC_REPRESENTATIVE REP
          , PAC_REPRESENTATIVE REP_POS
          , PAC_ADDRESS ADR_SEN
          , PAC_PERSON PER_SEN
          , PAC_PERSON PER
          , PAC_PERSON PER2
          , PAC_PERSON PER3
          , PAC_SUPPLIER_PARTNER SUP
          , ACS_ACCOUNT ACCS
          , PAC_THIRD THI
          , ACS_TAX_CODE ATC
          , PCS.PC_CURR CUR
          , PCS.PC_CNTRY CNT
          , PCS.PC_CNTRY CNT2
          , PCS.PC_CNTRY CNT3
          , DOC_GAUGE GAU
          , DOC_GAUGE_STRUCTURED GST
          , STM_STOCK STM
          , STM_STOCK STM_STM
          , GCO_GOOD GOO
          , GCO_PRODUCT PDT
          , DOC_POSITION POS
          , DOC_DOCUMENT DMT
          , CML_EVENTS CEV
          , CML_POSITION CPO
          , CML_DOCUMENT CCO
          , DOC_POSITION POS_ADD
          , DOC_POSITION_DETAIL PDE_ADD
          , (select DMT.DMT_NUMBER
                  , POS.DOC_POSITION_ID POSITIONID
                  , PDE.DOC_POSITION_DETAIL_ID
                  , (PDE.FAL_SCHEDULE_STEP_ID) FAL_SCHEDULE_STEP_ID
                  , (DMT_PERE.DMT_NUMBER) PERE_DMT_NUMBER
                  , (DMT_PERE.DMT_DATE_DOCUMENT) PERE_DMT_DATE_DOCUMENT
                  , (GAU_PERE.C_GAUGE_TITLE) PERE_C_GAUGE_TITLE
                  , (DMT_PERE.DMT_PARTNER_NUMBER) PERE_DMT_PARTNER_NUMBER
                  , (DMT_PERE.DMT_PARTNER_REFERENCE) PERE_DMT_PARTNTER_REFERENCE
                  , (DMT_PERE.DMT_DATE_PARTNER_DOCUMENT) PERE_DATE_PARTNER_DOCUMENT
                  , (DMT_G_PERE.DMT_NUMBER) G_PERE_DMT_NUMBER
                  , (DMT_G_PERE.DMT_DATE_DOCUMENT) G_PERE_DMT_DATE_DOCUMENT
                  , (GAU_G_PERE.C_GAUGE_TITLE) G_PERE_C_GAUGE_TITLE
                  , (DMT_G_PERE.DMT_PARTNER_NUMBER) G_PERE_DMT_PARTNER_NUMBER
                  , (DMT_G_PERE.DMT_PARTNER_REFERENCE) G_PERE_DMT_PARTNTER_REFERENCE
                  , (DMT_G_PERE.DMT_DATE_PARTNER_DOCUMENT) G_PERE_DATE_PARTNER_DOCUMENT
                  , (PDE.STM_LOCATION_ID) STM_LOCATION_ID
                  , (PDE.STM_STM_LOCATION_ID) STM_STM_LOCATION_ID
                  , (PDE.DIC_DELAY_UPDATE_TYPE_ID) DIC_DELAY_UPDATE_TYPE_ID
                  , (PDE.PDE_DELAY_UPDATE_TEXT) PDE_DELAY_UPDATE_TEXT
                  , PDE.GCO_CHARACTERIZATION_ID GCO1_CHARACTERIZATION_ID
                  , PDE.GCO_GCO_CHARACTERIZATION_ID GCO2_CHARACTERIZATION_ID
                  , PDE.GCO2_GCO_CHARACTERIZATION_ID GCO3_CHARACTERIZATION_ID
                  , PDE.GCO3_GCO_CHARACTERIZATION_ID GCO4_CHARACTERIZATION_ID
                  , PDE.GCO4_GCO_CHARACTERIZATION_ID GCO5_CHARACTERIZATION_ID
                  , (PDE.PDE_CHARACTERIZATION_VALUE_1) PDE_CHARACTERIZATION_VALUE_1
                  , (PDE.PDE_CHARACTERIZATION_VALUE_2) PDE_CHARACTERIZATION_VALUE_2
                  , (PDE.PDE_CHARACTERIZATION_VALUE_3) PDE_CHARACTERIZATION_VALUE_3
                  , (PDE.PDE_CHARACTERIZATION_VALUE_4) PDE_CHARACTERIZATION_VALUE_4
                  , (PDE.PDE_CHARACTERIZATION_VALUE_5) PDE_CHARACTERIZATION_VALUE_5
                  , PDE.PDE_PIECE
                  , PDE.PDE_SET
                  , PDE.PDE_VERSION
                  , PDE.PDE_CHRONOLOGICAL
                  , PDE.PDE_STD_CHAR_1
                  , PDE.PDE_STD_CHAR_2
                  , PDE.PDE_STD_CHAR_3
                  , PDE.PDE_STD_CHAR_4
                  , PDE.PDE_STD_CHAR_5
                  , (PDE.PDE_BASIS_DELAY) PDE_BASIS_DELAY
                  , (PDE.PDE_BASIS_DELAY_M) PDE_BASIS_DELAY_M
                  , (PDE.PDE_BASIS_DELAY_W) PDE_BASIS_DELAY_W
                  , (PDE.PDE_BASIS_QUANTITY) PDE_BASIS_QUANTITY
                  , (PDE.PDE_BASIS_QUANTITY_SU) PDE_BASIS_QUANTITY_SU
                  , (PDE.PDE_INTERMEDIATE_DELAY) PDE_INTERMEDIATE_DELAY
                  , (PDE.PDE_INTERMEDIATE_DELAY_M) PDE_INTERMEDIATE_DELAY_M
                  , (PDE.PDE_INTERMEDIATE_DELAY_W) PDE_INTERMEDIATE_DELAY_W
                  , (PDE.PDE_INTERMEDIATE_QUANTITY) PDE_INTERMEDIATE_QUANTITY
                  , (PDE.PDE_INTERMEDIATE_QUANTITY_SU) PDE_INTERMEDIATE_QUANTITY_SU
                  , (PDE.PDE_FINAL_DELAY) PDE_FINAL_DELAY
                  , (PDE.PDE_FINAL_DELAY_M) PDE_FINAL_DELAY_M
                  , (PDE.PDE_FINAL_DELAY_W) PDE_FINAL_DELAY_W
                  , (PDE.PDE_FINAL_QUANTITY) PDE_FINAL_QUANTITY
                  , (PDE.PDE_FINAL_QUANTITY_SU) PDE_FINAL_QUANTITY_SU
                  , case
                      when(DMT.DMT_ADDENDUM_INDEX is not null)
                      and (POS.C_DOC_POS_STATUS = '04') then PDE.PDE_ADDENDUM_QTY_BALANCED
                      else PDE.PDE_BALANCE_QUANTITY
                    end PDE_BALANCE_QUANTITY
                  , (PERE.DOC_POSITION_DETAIL_ID) PERE_DOC_POSITION_DETAIL_ID
                  , (PERE.PDE_BALANCE_QUANTITY) P_PDE_BALANCE_QUANTITY
                  , (PERE.PDE_BALANCE_QUANTITY_PARENT) P_PDE_BALANCE_QUANTITY_PARENT
                  , (PERE.PDE_BASIS_QUANTITY) P_PDE_BASIS_QUANTITY
                  , (PERE.PDE_BASIS_QUANTITY_SU) P_PDE_BASIS_QUANTITY_SU
                  , (PERE.PDE_INTERMEDIATE_QUANTITY) P_PDE_INTERMEDIATE_QUANTITY
                  , (PERE.PDE_INTERMEDIATE_QUANTITY_SU) P_PDE_INTERMEDIATE_QUANTITY_SU
                  , (PERE.PDE_FINAL_QUANTITY) P_PDE_FINAL_QUANTITY
                  , (PERE.PDE_FINAL_QUANTITY_SU) P_PDE_FINAL_QUANTITY_SU
                  , (G_PERE.DOC_POSITION_DETAIL_ID) G_PERE_DOC_POSITION_DETAIL_ID
                  , (NEE.FAN_EXCEED_QTY) NEED_FAN_EXCEED_QTY
                  , (NEE.FAN_FREE_QTY) NEED_FAN_FREE_QTY
                  , (NEE.FAN_FULL_QTY) NEED_FAN_FULL_QTY
                  , (NEE.FAN_NETW_QTY) NEED_FAN_NETW_QTY
                  , (NEE.FAN_PREV_QTY) NEED_FAN_PREV_QTY
                  , (NEE.FAN_REALIZE_QTY) NEED_FAN_REALIZE_QTY
                  , (NEE.FAN_RETURN_QTY) NEED_FAN_RETURN_QTY
                  , (NEE.FAN_STK_QTY) NEED_FAN_STK_QTY
                  , (NEE.FAL_NETWORK_NEED_ID) NEED_FAL_NETWORK_NEED_ID
                  , (SUPP.FAN_EXCEED_QTY) SUPPLY_FAN_EXCEED_QTY
                  , (SUPP.FAN_FREE_QTY) SUPPLY_FAN_FREE_QTY
                  , (SUPP.FAN_FULL_QTY) SUPPLY_FAN_FULL_QTY
                  , (SUPP.FAN_NETW_QTY) SUPPLY_FAN_NETW_QTY
                  , (SUPP.FAN_PREV_QTY) SUPPLY_FAN_PREV_QTY
                  , (SUPP.FAN_REALIZE_QTY) SUPPLY_FAN_REALIZE_QTY
                  , (SUPP.FAN_RETURN_QTY) SUPPLY_FAN_RETURN_QTY
                  , (SUPP.FAN_STK_QTY) SUPPLY_FAN_STK_QTY
                  , (SUPP.FAL_NETWORK_SUPPLY_ID) SUPPLY_FAL_NETWORK_SUPPLY_ID
                  , (LOT.LOT_REFCOMPL) LOT_REFCOMPL
                  , (COMP.GOO_MAJOR_REFERENCE) GOO_MAJOR_REFERENCE
                  , (LNK.SCS_SHORT_DESCR) SCS_SHORT_DESCR
                  , (LNK.SCS_LONG_DESCR) SCS_LONG_DESCR
                  , (LNK.SCS_FREE_DESCR) SCS_FREE_DESCR
                  , PDE.DOC_RECORD_ID
                  , PDE.PDE_ADDENDUM_SRC_PDE_ID
               from FAL_NETWORK_NEED NEE
                  , FAL_NETWORK_SUPPLY SUPP
                  , FAL_TASK_LINK LNK
                  , FAL_LOT LOT
                  , GCO_GOOD COMP
                  , DOC_GAUGE_STRUCTURED GAU_G_PERE
                  , DOC_GAUGE_STRUCTURED GAU_PERE
                  , DOC_POSITION_DETAIL G_PERE
                  , DOC_POSITION_DETAIL PERE
                  , DOC_POSITION_DETAIL PDE
                  , DOC_DOCUMENT DMT_G_PERE
                  , DOC_DOCUMENT DMT_PERE
                  , DOC_POSITION POS
                  , DOC_DOCUMENT DMT
              where DMT.DOC_DOCUMENT_ID = POS.DOC_DOCUMENT_ID
                and POS.DOC_POSITION_ID = PDE.DOC_POSITION_ID (+)
                and PDE.DOC_DOC_POSITION_DETAIL_ID = PERE.DOC_POSITION_DETAIL_ID(+)
                and PERE.DOC_DOCUMENT_ID = DMT_PERE.DOC_DOCUMENT_ID(+)
                and PERE.DOC_DOC_POSITION_DETAIL_ID = G_PERE.DOC_POSITION_DETAIL_ID(+)
                and PDE.FAL_SCHEDULE_STEP_ID = LNK.FAL_SCHEDULE_STEP_ID(+)
                and LNK.FAL_LOT_ID = LOT.FAL_LOT_ID(+)
                and LOT.GCO_GOOD_ID = COMP.GCO_GOOD_ID(+)
                and PERE.DOC_GAUGE_ID = GAU_PERE.DOC_GAUGE_ID(+)
                and G_PERE.DOC_DOCUMENT_ID = DMT_G_PERE.DOC_DOCUMENT_ID(+)
                and G_PERE.DOC_GAUGE_ID = GAU_G_PERE.DOC_GAUGE_ID(+)
                and PDE.DOC_POSITION_DETAIL_ID = NEE.DOC_POSITION_DETAIL_ID(+)
                and PDE.DOC_POSITION_DETAIL_ID = SUPP.DOC_POSITION_DETAIL_ID(+)) DETAIL
      where DMT.DOC_DOCUMENT_ID = POS.DOC_DOCUMENT_ID
        and POS.DOC_POSITION_ID = DETAIL.POSITIONID (+)
        and DMT.DOC_GAUGE_ID = GAU.DOC_GAUGE_ID
        and GAU.DOC_GAUGE_ID = GST.DOC_GAUGE_ID
        and POS.DOC_GAUGE_POSITION_ID = DGP.DOC_GAUGE_POSITION_ID
        and DMT.PC_LANG_ID = LANG.PC_LANG_ID
        and POS.ACS_TAX_CODE_ID = TVA.ACS_ACCOUNT_ID(+)
        and DMT.ACS_FIN_ACC_S_PAYMENT_ID = AFA.ACS_FIN_ACC_S_PAYMENT_ID(+)
        and AFA.ACS_PAYMENT_METHOD_ID = APM.ACS_PAYMENT_METHOD_ID(+)
        and DMT.PAC_REPRESENTATIVE_ID = REP.PAC_REPRESENTATIVE_ID(+)
        and DMT.DOC_DOCUMENT_ID = DFD.DOC_DOCUMENT_ID(+)
        and DMT.DOC_DOCUMENT_ID = FOO.DOC_DOCUMENT_ID(+)
        and POS.ACS_TAX_CODE_ID = ATC.ACS_TAX_CODE_ID(+)
        and POS.GCO_GOOD_ID = GCE.GCO_GOOD_ID(+)
        and GCE.PC_CNTRY_ID = CNT_CUSTOMS.PC_CNTRY_ID(+)
        and GCE.PC_ORIGIN_PC_CNTRY_ID = CNT_ORIGIN.PC_CNTRY_ID(+)
        and GCE.C_CUSTOMS_ELEMENT_TYPE(+) = 'EXPORT'
        and POS.PAC_REPRESENTATIVE_ID = REP_POS.PAC_REPRESENTATIVE_ID(+)
        and FOO.DOC_GAUGE_SIGNATORY_ID = DGS.DOC_GAUGE_SIGNATORY_ID(+)
        and FOO.DOC_DOC_GAUGE_SIGNATORY_ID = DGS2.DOC_GAUGE_SIGNATORY_ID(+)
        and DMT.DOC_RECORD_ID = REC.DOC_RECORD_ID(+)
        and POS.DOC_RECORD_ID = REC_POS.DOC_RECORD_ID(+)
        and DETAIL.DOC_RECORD_ID = REC_PDE.DOC_RECORD_ID(+)
        and DMT.PAC_SENDING_CONDITION_ID = PSC.PAC_SENDING_CONDITION_ID(+)
        and PSC.PAC_ADDRESS_ID = ADR_SEN.PAC_ADDRESS_ID(+)
        and ADR_SEN.PAC_PERSON_ID = PER_SEN.PAC_PERSON_ID(+)
        and DMT.PAC_THIRD_ID = THI.PAC_THIRD_ID(+)
        and DMT.PAC_THIRD_ID = CUS.PAC_CUSTOM_PARTNER_ID(+)
        and CUS.ACS_AUXILIARY_ACCOUNT_ID = ACCC.ACS_ACCOUNT_ID(+)
        and SUP.ACS_AUXILIARY_ACCOUNT_ID = ACCS.ACS_ACCOUNT_ID(+)
        and DMT.PAC_THIRD_ID = SUP.PAC_SUPPLIER_PARTNER_ID(+)
        and DMT.PAC_ADDRESS_ID = ADR.PAC_ADDRESS_ID(+)
        and ADR.PAC_PERSON_ID = PER.PAC_PERSON_ID(+)
        and DMT.PAC_PAC_ADDRESS_ID = ADR2.PAC_ADDRESS_ID(+)
        and ADR2.PAC_PERSON_ID = PER2.PAC_PERSON_ID(+)
        and DMT.PAC2_PAC_ADDRESS_ID = ADR3.PAC_ADDRESS_ID(+)
        and ADR3.PAC_PERSON_ID = PER3.PAC_PERSON_ID(+)
        and DMT.PC_CNTRY_ID = CNT.PC_CNTRY_ID(+)
        and DMT.PC__PC_CNTRY_ID = CNT2.PC_CNTRY_ID(+)
        and DMT.PC_2_PC_CNTRY_ID = CNT3.PC_CNTRY_ID(+)
        and DMT.ACS_FINANCIAL_CURRENCY_ID = AFC.ACS_FINANCIAL_CURRENCY_ID(+)
        and AFC.PC_CURR_ID = CUR.PC_CURR_ID(+)
        and DMT.PAC_PAYMENT_CONDITION_ID = PMT.PAC_PAYMENT_CONDITION_ID(+)
        and DETAIL.STM_LOCATION_ID = LOC.STM_LOCATION_ID(+)
        and DETAIL.STM_STM_LOCATION_ID = LOC_LOC.STM_LOCATION_ID(+)
        and LOC.STM_STOCK_ID = STM.STM_STOCK_ID(+)
        and LOC_LOC.STM_STOCK_ID = STM_STM.STM_STOCK_ID(+)
        and POS.GCO_GOOD_ID = GOO.GCO_GOOD_ID(+)
        and GOO.GCO_GOOD_ID = PDT.GCO_GOOD_ID(+)
        and GOO.GCO_GOOD_ID = GFD.GCO_GOOD_ID(+)
        and POS.CML_EVENTS_ID = CEV.CML_EVENTS_ID(+)
        and DMT.DMT_NUMBER = PARAMETER_0
        and POS.CML_POSITION_ID = CPO.CML_POSITION_ID(+)
        and CPO.CML_DOCUMENT_ID = CCO.CML_DOCUMENT_ID(+)
        and POS.POS_ADDENDUM_SRC_POS_ID = POS_ADD.DOC_POSITION_ID(+)
        and PDE_ADD.DOC_POSITION_DETAIL_ID(+) = DETAIL.PDE_ADDENDUM_SRC_PDE_ID;
end RPT_DOC_STD_2;
