--------------------------------------------------------
--  DDL for Procedure RPT_GAL_SPENDING_GENERATE_FOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_GAL_SPENDING_GENERATE_FOR" (
  aRefCursor     in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, procparam_0    in     varchar2
, procuser_lanid in     pcs.pc_lang.lanid%type
, pc_user_id     in     PCS.PC_USER.PC_USER_ID%type
, pc_comp_id     in     PCS.PC_COMP.PC_COMP_ID%type
, pc_conli_id    in     PCS.PC_CONLI.PC_CONLI_ID%type
)
is
/**
* description used for report GAL_PROJECT_FINANCIAL_BALANCE.
* Replace the procedure GAL_SPENDING_GENERATE_FOR_RPT
* @lastUpdate VHA 26 JUNE 2013
* @public
*/
  s_sql_gal_project varchar2(32762);
  vpc_lang_id       PCS.PC_LANG.PC_LANG_ID%type := null;
  vpc_user_id       PCS.PC_USER.PC_USER_ID%type := null;
  vpc_comp_id       PCS.PC_COMP.PC_COMP_ID%type := null;
  vpc_conli_id      PCS.PC_CONLI.PC_CONLI_ID%type := null;
begin
  if (procparam_0 is not null) then
    PCS.PC_LIB_SESSION.setLanUserId(iLanId => procuser_lanid
                                  , iPcUserId => pc_user_id
                                  , iPcCompId => pc_comp_id
                                  , iConliId => pc_conli_id);
      vpc_lang_id        := PCS.PC_I_LIB_SESSION.getUserlangId;
      vpc_user_id        := PCS.PC_I_LIB_SESSION.getUserId;
      vpc_comp_id        := PCS.PC_I_LIB_SESSION.getCompanyId;
      vpc_conli_id       := PCS.PC_I_LIB_SESSION.getConliId;
  end if;

  -- GENERATION DES TABLES DE DEPENSES --
  s_sql_gal_project  := 'select GAL_PROJECT_ID from GAL_PROJECT where 1=1 ';

  if procparam_0 is not null then
    s_sql_gal_project  := s_sql_gal_project || procparam_0;
  end if;

  if ((s_sql_gal_project is not null) and ( procparam_0 is not null)) then
    GAL_PROJECT_CONSOLIDATION.GAL_SPENDING_GENERATE_WITH_SEL(s_sql_gal_project);
  end if;

  -- GENERATION DU CURSEUR POUR CRYSTAL --
  s_sql_gal_project  :=
    'select ' ||
    'GAL_PROJECT.GAL_PROJECT_ID, ' ||
    'GAL_PROJECT.PRJ_CODE, ' ||
    'GAL_PROJECT.PRJ_WORDING, ' ||
    'GAL_PROJECT.PRJ_DESCRIPTION, ' ||
    'GAL_PROJECT.PRJ_COMMENT, ' ||
    'COM_DIC_FUNCTIONS.GETDICODESCR(''DIC_GAL_PRJ_CATEGORY'',GAL_PROJECT.DIC_GAL_PRJ_CATEGORY_ID) DIC_GAL_PRJ_CATEGORY_ID, ' ||
    'COM_DIC_FUNCTIONS.GETDICODESCR(''DIC_GAL_DIVISION'',GAL_PROJECT.DIC_GAL_DIVISION_ID) DIC_GAL_DIVISION_ID, ' ||
    'COM_DIC_FUNCTIONS.GETDICODESCR(''DIC_GAL_PRODUCT_LINE'',GAL_PROJECT.DIC_GAL_PRODUCT_LINE_ID) DIC_GAL_PRODUCT_LINE_ID, ' ||
    'COM_DIC_FUNCTIONS.GETDICODESCR(''DIC_GAL_LOCATION'',GAL_PROJECT.DIC_GAL_LOCATION_ID) DIC_GAL_LOCATION_ID, ' ||
    'HRM_PERSON.PER_LAST_NAME HRM_PROJECT_PERSON_ID, ' ||
    'PAC_PERSON.PER_NAME PAC_CUSTOM_PARTNER_ID, ' ||
    'COM_FUNCTIONS.GETDESCODEDESCR(''C_PRJ_STATE'',GAL_PROJECT.C_PRJ_STATE) C_PRJ_STATE, ' ||
    'GAL_PROJECT.A_DATECRE, ' ||
    'GAL_PROJECT.PRJ_LAUNCHING_DATE, ' ||
    'GAL_PROJECT.PRJ_DELIVERY_DATE, ' ||
    'GAL_PROJECT.PRJ_BALANCE_DATE, ' ||
    'GAL_PROJECT.PRJ_CUSTOMER_ORDER_REF, ' ||
    'GAL_PROJECT.PRJ_CUSTOMER_ORDER_DATE, ' ||
    'GAL_PROJECT.PRJ_CUSTOMER_DELIVERY_DATE, ' ||
    'GAL_PROJECT.PRJ_SALE_PRICE, ' ||
    'GAL_PROJECT.PRJ_INTERNAL, ' ||
    'GAL_PROJECT.PRJ_FORECAST, ' ||
    'GAL_PROJECT.PRJ_CODE_GROUP_1, ' ||
    'GAL_PROJECT.PRJ_CODE_GROUP_2, ' ||
    'GAL_PROJECT.PRJ_CODE_GROUP_3, ' ||
    'GAL_PROJECT.PRJ_CODE_CONSOLIDATION_1, ' ||
    'GAL_PROJECT.PRJ_CODE_CONSOLIDATION_2, ' ||
    'GAL_PROJECT.PRJ_CODE_CLASSIFICATION, ' ||
    'GAL_PROJECT.PRJ_PRODUCT_IDENFITICATION, ' ||
    'GAL_COST_CENTER.DIC_GAL_ANA_GROUP_ID, ' ||
    'COM_DIC_FUNCTIONS.GETDICODESCR (''DIC_GAL_ANA_GROUP'',GAL_COST_CENTER.DIC_GAL_ANA_GROUP_ID) DIC_GAL_ANA_GROUP_WORDING, ' ||
    'GAL_COST_CENTER.GCC_CODE GAL_COST_CENTER_ID, ' ||
    'GAL_COST_CENTER.GCC_WORDING, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_BUDGET_QUANTITY, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_BUDGET_AMOUNT, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_COL1_QUANTITY, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_COL1_AMOUNT, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_COL2_QUANTITY, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_COL2_AMOUNT, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_COL3_QUANTITY, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_COL3_AMOUNT, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_COL4_QUANTITY, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_COL4_AMOUNT, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_COL5_QUANTITY, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_COL5_AMOUNT, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_REMAINING_QUANTITY, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_REMAINING_AMOUNT, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_TOTAL_QUANTITY, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_TOTAL_AMOUNT, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_MARGIN_QUANTITY, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_MARGIN_AMOUNT, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_MARGIN_QUANTITY*100/decode(GAL_SPENDING_CONSOLIDATED.GSP_BUDGET_QUANTITY,0,null,GAL_SPENDING_CONSOLIDATED.GSP_BUDGET_QUANTITY) GSP_PERC_MARGIN_QUANTITY, ' ||
    'GAL_SPENDING_CONSOLIDATED.GSP_MARGIN_AMOUNT*100/decode(GAL_SPENDING_CONSOLIDATED.GSP_BUDGET_AMOUNT,0,null,GAL_SPENDING_CONSOLIDATED.GSP_BUDGET_AMOUNT) GSP_PERC_MARGIN_AMOUNT  ' ||
    'FROM ' ||
    'PAC_PERSON, ' ||
    'HRM_PERSON, ' ||
    'GAL_COST_CENTER, ' ||
    'GAL_SPENDING_CONSOLIDATED, ' ||
    'GAL_PROJECT ' ||
    'WHERE ' ||
    'GAL_COST_CENTER.GAL_COST_CENTER_ID (+) = GAL_SPENDING_CONSOLIDATED.GAL_COST_CENTER_ID AND ' ||
    'PAC_PERSON.PAC_PERSON_ID (+) =GAL_PROJECT.PAC_CUSTOM_PARTNER_ID AND ' ||
    'HRM_PERSON.HRM_PERSON_ID (+) =GAL_PROJECT.HRM_PROJECT_PERSON_ID AND ' ||
    'GAL_SPENDING_CONSOLIDATED.GAL_PROJECT_ID (+) =GAL_PROJECT.GAL_PROJECT_ID AND ' ||
    'GAL_SPENDING_CONSOLIDATED.GAL_BUDGET_ID IS NULL ';

  if procparam_0 is not null then
    s_sql_gal_project  := s_sql_gal_project || procparam_0;
  end if;

  open aRefCursor for s_sql_gal_project;
end RPT_GAL_SPENDING_GENERATE_FOR;
