--------------------------------------------------------
--  DDL for Procedure RPT_ACT_DET_PAYMENT_LET
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACT_DET_PAYMENT_LET" (
  aRefCursor  in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, PARAMETER_0 in     NUMBER
)
is
/**
* description used for report ACR_REC_IMPUTATION_DET and ACR_PAY_IMPUTATION_DET.

* @author jliu 19 Dec.2007
* @lastupdate 12 Feb 2009
* @public
* @param PARAMETER_0    ACT_PART_IMPUTATION_ID
*/

BEGIN
open aRefCursor for
SELECT
FIN.PC_CURR_ID,
IMP.IMF_TYPE,
IMP.IMF_AMOUNT_LC_D,
IMP.IMF_AMOUNT_LC_C,
IMP.IMF_AMOUNT_FC_D,
IMP.IMF_AMOUNT_FC_C,
IMP.ACT_DET_PAYMENT_ID,
IMP.ACS_FINANCIAL_CURRENCY_ID,
IMP.ACS_ACS_FINANCIAL_CURRENCY_ID,
IMP.C_GENRE_TRANSACTION,
IMP.ACT_PART_IMPUTATION_ID
FROM
    ACS_FINANCIAL_CURRENCY     FIN,
    ACT_FINANCIAL_IMPUTATION   IMP
WHERE
IMP.C_GENRE_TRANSACTION = '1'
AND (IMP.ACT_DET_PAYMENT_ID IS NULL)
AND IMP.IMF_TYPE <> 'VAT'
AND IMP.ACT_PART_IMPUTATION_ID = PARAMETER_0
AND IMP.ACS_FINANCIAL_CURRENCY_ID = FIN.ACS_FINANCIAL_CURRENCY_ID
;
END RPT_ACT_DET_PAYMENT_LET;
