--------------------------------------------------------
--  DDL for Procedure RPT_DOC_STOCK_SITUATION_SUB
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_DOC_STOCK_SITUATION_SUB" (
      arefcursor      IN OUT   crystal_cursor_types.dualcursortyp,
      PARAMETER_1     IN           VARCHAR2
   )
IS
/**
*Description
 Used for the reports

 Group 2 - PORTFOLIO BY PRODUCT
 DOC_CUST_ORDER_PORT_GOOD_BATCH
 DOC_CUST_CONSIG_PORT_GOOD_BATCH
 DOC_CUST_DELIVERY_PORT_GOOD_BATCH
 DOC_SUPPL_ORDER_PORT_GOOD_BATCH
 DOC_SUPPL_DELIVERY_PORT_GOOD_BATCH

*@created PNA 1 Jun 2007
*@lastUpdate 19 Feb 2009
*@public
*@param PARAMETER_1 : GCO_GOOD_ID
*/

BEGIN
OPEN AREFCURSOR
FOR
SELECT
LOC.STM_LOCATION_ID,
LOC.LOC_DESCRIPTION,
STO.STO_DESCRIPTION,
STO.C_ACCESS_METHOD,
SPO.GCO_GOOD_ID,
SPO.SPO_STOCK_QUANTITY,
SPO.SPO_ASSIGN_QUANTITY,
SPO.SPO_PROVISORY_INPUT,
SPO.SPO_PROVISORY_OUTPUT,
SPO.SPO_AVAILABLE_QUANTITY
FROM
STM_STOCK STO,
STM_LOCATION LOC,
STM_STOCK_POSITION SPO
WHERE
SPO.STM_STOCK_ID = STO.STM_STOCK_ID
AND SPO.STM_LOCATION_ID = LOC.STM_LOCATION_ID
AND STO.C_ACCESS_METHOD <> 'PRIVATE'
AND SPO.GCO_GOOD_ID = TO_NUMBER(PARAMETER_1);

END RPT_DOC_STOCK_SITUATION_SUB;
