--------------------------------------------------------
--  DDL for Procedure RPT_ACT_MGM_RECAP_SUB
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACT_MGM_RECAP_SUB" (
  aRefCursor             in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, PARAMETER_1            in     VARCHAR2
, PROCUSER_LANID         in     pcs.pc_lang.lanid%type
)
/**
* description used for report act_mgm_recap.rpt,sub report of act_journal_mgm.rpt

* @author jliu 18 nov 2008
* @lastupdate 12 Feb 2009
* @public
* @PARAM PARAMETER_1    ACT_JOURNAL_ID
*/
is

VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;


begin

pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;

open aRefCursor for
SELECT
CDA_ACC.ACC_NUMBER CDA_ACC_NUMBER,
CPN_ACC.ACC_NUMBER CPN_ACC_NUMBER,
PF_ACC.ACC_NUMBER PF_ACC_NUMBER,
QTY_ACC.ACC_NUMBER QTY_ACC_NUMBER,
CUR_MB.CURRENCY CURRENCY_MB,
CUR_ME.CURRENCY CURRENCY_ME,
IMP.ACS_CDA_ACCOUNT_ID,
IMP.ACS_CPN_ACCOUNT_ID,
IMP.ACS_PF_ACCOUNT_ID,
IMP.ACS_QTY_UNIT_ID,
IMP.ACS_ACS_FINANCIAL_CURRENCY_ID,
IMP.IMM_AMOUNT_LC_D,
IMP.IMM_AMOUNT_LC_C,
IMP.ACS_FINANCIAL_CURRENCY_ID,
IMP.IMM_AMOUNT_FC_D,
IMP.IMM_AMOUNT_FC_C,
IMP.IMM_QUANTITY_D,
IMP.IMM_QUANTITY_C
FROM
ACS_ACCOUNT CDA_ACC,
ACS_ACCOUNT CPN_ACC,
ACS_ACCOUNT PF_ACC,
ACS_ACCOUNT QTY_ACC,
ACS_FINANCIAL_CURRENCY FUR_MB,
ACS_FINANCIAL_CURRENCY FUR_ME,
PCS.PC_CURR CUR_MB,
PCS.PC_CURR CUR_ME,
V_ACT_REP_MGM_IMPUTATION IMP
WHERE
IMP.ACS_CDA_ACCOUNT_ID = CDA_ACC.ACS_ACCOUNT_ID(+)
AND IMP.ACS_FINANCIAL_CURRENCY_ID = FUR_ME.ACS_FINANCIAL_CURRENCY_ID
AND FUR_ME.PC_CURR_ID = CUR_ME.PC_CURR_ID
AND IMP.ACS_ACS_FINANCIAL_CURRENCY_ID = FUR_MB.ACS_FINANCIAL_CURRENCY_ID
AND FUR_MB.PC_CURR_ID = CUR_MB.PC_CURR_ID
AND IMP.ACS_CPN_ACCOUNT_ID = CPN_ACC.ACS_ACCOUNT_ID
AND IMP.ACS_QTY_UNIT_ID = QTY_ACC.ACS_ACCOUNT_ID(+)
AND IMP.ACS_PF_ACCOUNT_ID= PF_ACC.ACS_ACCOUNT_ID(+)
AND IMP.ACT_JOURNAL_ID = TO_NUMBER(PARAMETER_1)
AND IMP.C_SUB_SET = 'CPN'
;
END RPT_ACT_MGM_RECAP_SUB;
