--------------------------------------------------------
--  DDL for Procedure RPT_ACT_FIN_IMP_CUMUL_REC
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACT_FIN_IMP_CUMUL_REC" (
  aRefCursor    in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, date_to       in     VARCHAR2
, PARAMETER_0   in     NUMBER
, PARAMETER_7   in     VARCHAR2
, PARAMETER_8   in     VARCHAR2
, PARAMETER_9   in     VARCHAR2
, PARAMETER_12  in     VARCHAR2
, PARAMETER_17  in     VARCHAR2 -- Division list
, PARAMETER_18  in     VARCHAR2
, PARAMETER_19  in     VARCHAR2
, PARAMETER_20  in     VARCHAR2
, PARAMETER_21  in     VARCHAR2
)
is
/**
/**
*DESCRIPTION
  USED FOR REPORT  ACR_REC_IMPUTATION_DET (SS_REPORT V_ACT_FINANCIAL_IMPUTATION_CUMUL)
 * Replace the procedure ACT_FIN_IMP_CUMUL_REC_RPT
*author JLI / PYB
*lastUpdate 2007-12-19 - 2008-09-30
*version 2007
*public
*/
BEGIN
open aRefCursor for
SELECT
CAT.C_TYPE_CATALOGUE,
FIN.FIN_COLLECTIVE,
CUR.FIN_LOCAL_CURRENCY,
PCR.CURRENCY,
PCR2.CURRENCY CURRENCY_LC,
V_IMP.IMF_AMOUNT_LC_D,
V_IMP.IMF_AMOUNT_LC_C,
V_IMP.IMF_AMOUNT_FC_D,
V_IMP.IMF_AMOUNT_FC_C,
V_IMP.IMF_TRANSACTION_DATE,
V_IMP.ACS_FINANCIAL_CURRENCY_ID,
V_IMP.ACS_AUXILIARY_ACCOUNT_ID,
V_IMP.ACS_ACS_FINANCIAL_CURRENCY_ID,
V_IMP.C_ETAT_JOURNAL,
V_IMP.ACT_FINANCIAL_IMPUTATION_ID,
PRD.C_TYPE_PERIOD
FROM
    ACJ_CATALOGUE_DOCUMENT CAT,
    ACS_AUX_ACCOUNT_S_FIN_CURR AUX,
    ACS_FINANCIAL_ACCOUNT FIN,
    ACS_FINANCIAL_CURRENCY CUR,
    ACS_FINANCIAL_CURRENCY CUL,
    ACT_DOCUMENT DOC,
    PCS.PC_CURR PCR,
    PCS.PC_CURR PCR2,
    V_ACT_REC_IMP_REPORT V_IMP,
    ACS_PERIOD PRD,
    ACS_AUX_ACCOUNT_S_FIN_CURR AUX_S,
    THE (SELECT CAST(DOC_DOCUMENT_LIST_FUNCTIONS.IN_LIST(PARAMETER_17) AS CHAR_TABLE_TYPE) FROM DUAL) DIVISION_ACCOUNT_ID_LIST
WHERE
V_IMP.ACT_DOCUMENT_ID = DOC.ACT_DOCUMENT_ID(+)
AND DOC.ACJ_CATALOGUE_DOCUMENT_ID = CAT.ACJ_CATALOGUE_DOCUMENT_ID(+)
AND V_IMP.ACS_FINANCIAL_ACCOUNT_ID = FIN.ACS_FINANCIAL_ACCOUNT_ID(+)
AND V_IMP.ACS_FINANCIAL_CURRENCY_ID = CUR.ACS_FINANCIAL_CURRENCY_ID(+)
AND CUR.PC_CURR_ID = PCR.PC_CURR_ID(+)
AND V_IMP.ACS_AUXILIARY_ACCOUNT_ID = AUX.ACS_AUXILIARY_ACCOUNT_ID(+)
AND V_IMP.ACS_FINANCIAL_ACCOUNT_ID = AUX.ACS_FINANCIAL_CURRENCY_ID(+)
AND V_IMP.ACS_ACS_FINANCIAL_CURRENCY_ID = CUL.ACS_FINANCIAL_CURRENCY_ID(+)
AND CUL.PC_CURR_ID = PCR2.PC_CURR_ID
AND FIN.FIN_COLLECTIVE = 1
AND V_IMP.ACS_PERIOD_ID = PRD.ACS_PERIOD_ID
AND AUX_S.ACS_AUXILIARY_ACCOUNT_ID = V_IMP.ACS_AUXILIARY_ACCOUNT_ID
AND AUX_S.ACS_FINANCIAL_CURRENCY_ID = V_IMP.ACS_FINANCIAL_CURRENCY_ID
AND V_IMP.IMF_TRANSACTION_DATE <= TO_DATE(date_to,'yyyyMMdd')
AND ((PARAMETER_7='1' AND V_IMP.C_ETAT_JOURNAL = 'BRO')
    OR (PARAMETER_8='1' AND V_IMP.C_ETAT_JOURNAL = 'PROV')
    OR (PARAMETER_9='1' AND V_IMP.C_ETAT_JOURNAL = 'DEF'))
AND (PARAMETER_17 = '#' OR V_IMP.ACS_DIVISION_ACCOUNT_ID = DIVISION_ACCOUNT_ID_LIST.COLUMN_VALUE)
AND ((PARAMETER_18 ='1' AND V_IMP.C_TYPE_CUMUL = 'EXT')
     OR (PARAMETER_19 ='1' AND  V_IMP.C_TYPE_CUMUL ='INT')
     OR (PARAMETER_20 ='1' AND V_IMP.C_TYPE_CUMUL ='PRE')
     OR (PARAMETER_21='1' AND V_IMP.C_TYPE_CUMUL ='ENG'))
AND ((PARAMETER_12 = '1')
    OR((PARAMETER_12 <>'1') AND (CAT.C_TYPE_CATALOGUE IS NULL))
    OR((PARAMETER_12 <>'1') AND NOT(CAT.C_TYPE_CATALOGUE IS NULL) AND CAT.C_TYPE_CATALOGUE <>'9'))
AND V_IMP.ACS_AUXILIARY_ACCOUNT_ID = PARAMETER_0
;
END RPT_ACT_FIN_IMP_CUMUL_REC ;
