--------------------------------------------------------
--  DDL for Procedure RPT_ASA_RECORD_FORM3_II_DIAG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ASA_RECORD_FORM3_II_DIAG" (
   AREFCURSOR      IN OUT   CRYSTAL_CURSOR_TYPES.DUALCURSORTYP,
   PARAMETER_0     IN       VARCHAR2,
   COMPANY_OWNER   IN       PCS.PC_COMP.COM_NAME%TYPE,
   PROCUSER_LANID   IN       PCS.PC_LANG.LANID%TYPE
)
IS
/*
* description used for report ASA_RECORD_FORM3_II

*@created VHA 06.09.2011
*@version
*@public
*@param PARAMETER_0: ASA_RECORD.ASA_RECORD_ID
*/
   VPC_LANG_ID   PCS.PC_LANG.PC_LANG_ID%TYPE;

BEGIN
   PCS.PC_I_LIB_SESSION.SETLANID (PROCUSER_LANID);
   VPC_LANG_ID := PCS.PC_I_LIB_SESSION.GETUSERLANGID;

   OPEN AREFCURSOR FOR
      SELECT DIA.ASA_DIAGNOSTICS_ID,
                  DIA.ASA_RECORD_ID,
                  DIA.C_ASA_CONTEXT,
                  COM_FUNCTIONS.GETDESCODEDESCR('C_ASA_CONTEXT', DIA.C_ASA_CONTEXT, VPC_LANG_ID) DIA_CONTEXT_DESCR,
                  DIA.DIC_DIAGNOSTICS_TYPE_ID,
                  COM_DIC_FUNCTIONS.GETDICODESCR('DIC_DIAGNOSTICS_TYPE', DIA.DIC_DIAGNOSTICS_TYPE_ID, VPC_LANG_ID) DIA_TYPE_DESCR,
                  DIA.DIC_OPERATOR_ID,
                  COM_DIC_FUNCTIONS.GETDICODESCR('DIC_OPERATOR_ID', DIA.DIC_OPERATOR_ID, VPC_LANG_ID) DIA_OPERATOR_DESCR,
                  DIA.DIA_SEQUENCE,
                  DIA.DIA_DIAGNOSTICS_TEXT,
                  DIA.A_DATECRE,
                  DIA.A_DATEMOD,
                  DIA.A_IDCRE,
                  DIA.A_IDMOD,
                  DIA.A_RECLEVEL,
                  DIA.A_RECSTATUS,
                  DIA.A_CONFIRM
      FROM ASA_DIAGNOSTICS DIA
      WHERE DIA.ASA_RECORD_ID = TO_NUMBER(PARAMETER_0);


END RPT_ASA_RECORD_FORM3_II_DIAG;
