--------------------------------------------------------
--  DDL for Procedure RPT_FAM_SUMMARY_SUB
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_FAM_SUMMARY_SUB" (
  aRefCursor     in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, PARAMETER_0    in     varchar2
, PROCUSER_LANID in     pcs.pc_lang.lanid%type
)
is
/**
  Used for sub report of FAM_JOURNAL
  @author OJO.
  @lastUpdate
  @version 2003.
  @public
  @param PARAMETER_0    Titre de la liste.
*/
  VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;

begin
  pcs.PC_I_LIB_SESSION.setLanId(procuser_lanid);
  VPC_LANG_ID  := pcs.PC_I_LIB_SESSION.GetUserLangId;

OPEN aRefCursor FOR
SELECT
FUR.FIN_LOCAL_CURRENCY,
FIM.FIM_AMOUNT_LC_D,
FIM.FIM_AMOUNT_LC_C,
FIM.FIM_AMOUNT_FC_D,
FIM.FIM_AMOUNT_FC_C,
FIM.FIM_EXCHANGE_RATE,
FIM.C_FAM_TRANSACTION_TYP,
JOU.FAM_JOURNAL_ID,
VAL.VAL_KEY,
VAL.VAL_DESCR,
CUR.CURRENCY
FROM
ACS_FINANCIAL_CURRENCY FUR,
ACS_FINANCIAL_YEAR YEA,
FAM_CATALOGUE CAT,
FAM_DOCUMENT FDT,
FAM_FIXED_ASSETS FIX,
FAM_FIXED_ASSETS_CATEG TEG,
FAM_IMPUTATION FIM,
FAM_JOURNAL JOU,
FAM_MANAGED_VALUE VAL,
FAM_VAL_IMPUTATION VIM,
PCS.PC_CURR CUR
WHERE
JOU.FAM_JOURNAL_ID = TO_NUMBER(PARAMETER_0)
AND FDT.FAM_DOCUMENT_ID = FIM.FAM_DOCUMENT_ID(+)
AND FIM.FAM_IMPUTATION_ID = VIM.FAM_IMPUTATION_ID(+)
AND VIM.FAM_MANAGED_VALUE_ID = VAL.FAM_MANAGED_VALUE_ID(+)
AND FIM.ACS_FINANCIAL_CURRENCY_ID = FUR.ACS_FINANCIAL_CURRENCY_ID
AND FUR.PC_CURR_ID = CUR.PC_CURR_ID
AND FIM.FAM_FIXED_ASSETS_ID = FIX.FAM_FIXED_ASSETS_ID(+)
AND FIM.FAM_FIXED_ASSETS_CATEG_ID = TEG.FAM_FIXED_ASSETS_CATEG_ID
AND FDT.FAM_CATALOGUE_ID = CAT.FAM_CATALOGUE_ID(+)
AND FDT.FAM_JOURNAL_ID = JOU.FAM_JOURNAL_ID
AND JOU.ACS_FINANCIAL_YEAR_ID = YEA.ACS_FINANCIAL_YEAR_ID

;
end RPT_FAM_SUMMARY_SUB;
