--------------------------------------------------------
--  DDL for Procedure RPT_ACT_JOURNAL_AUX
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACT_JOURNAL_AUX" (
  aRefCursor     in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, aJOU_NUMBER_From       in     varchar2
, aJOU_NUMBER_To         in     varchar2
, aACS_FINANCIAL_YEAR_ID in     varchar2
, PARAMETER_0            in     varchar2
, PROCUSER_LANID         in     pcs.pc_lang.lanid%type
)
/**
* description used for report ACT_JOURNAL_AUX

* @author jliu 18 nov 2008
* @lastupdate 12 Feb 2009
* @public
* @PARAM PARAMETER_0     C_SUB_SET
*/

is

VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;


begin
if (aJOU_NUMBER_From is not null) and (Length(Trim(aJOU_NUMBER_From)) > 0) then
    ACR_FUNCTIONS.JOU_NUMBER1 := aJOU_NUMBER_From;
  else
    ACR_FUNCTIONS.JOU_NUMBER1 := ' ';
  end if;
  if (aJOU_NUMBER_To is not null) and (Length(Trim(aJOU_NUMBER_To)) > 0) then
    ACR_FUNCTIONS.JOU_NUMBER2 := aJOU_NUMBER_To;
  end if;
  if (aACS_FINANCIAL_YEAR_ID is not null) and (Length(Trim(aACS_FINANCIAL_YEAR_ID)) > 0) then
    ACR_FUNCTIONS.FIN_YEAR_ID := aACS_FINANCIAL_YEAR_ID;
  end if;

pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;

open aRefCursor for
SELECT
DES.PC_LANG_ID,
DES.DES_DESCRIPTION_SUMMARY,
FUR_ME.PC_CURR_ID ME_CURR_ID,
FUR_MB.PC_CURR_ID MB_CURR_ID,
ATD.ACT_DOCUMENT_ID,
ATD.ACT_JOB_ID,
ATD.DOC_NUMBER,
ATD.DOC_DOCUMENT_DATE,
DIS.ACS_DIVISION_ACCOUNT_ID,
PAR.ACT_PART_IMPUTATION_ID,
PAR.PAR_DOCUMENT,
PAR.PAC_CUSTOM_PARTNER_ID,
PAR.PAC_SUPPLIER_PARTNER_ID,
PAR.DOC_DATE_DELIVERY,
CUR_MB.CURRENCY MB_CURRENCY,
CUR_ME.CURRENCY ME_CURRENCY,
PTJ.ACT_FINANCIAL_IMPUTATION_ID,
PTJ.ACT_DOCUMENT_ID,
PTJ.ACS_FINANCIAL_ACCOUNT_ID,
PTJ.IMF_PRIMARY,
PTJ.IMF_DESCRIPTION,
PTJ.IMF_AMOUNT_LC_D,
PTJ.IMF_AMOUNT_LC_C,
PTJ.IMF_AMOUNT_FC_D,
PTJ.IMF_AMOUNT_FC_C,
PTJ.IMF_EXCHANGE_RATE,
PTJ.IMF_VALUE_DATE,
PTJ.ACS_TAX_CODE_ID,
PTJ.IMF_TRANSACTION_DATE,
PTJ.ACS_AUXILIARY_ACCOUNT_ID,
JOU.ACT_JOURNAL_ID,
JOU.PC_USER_ID,
JOU.JOU_DESCRIPTION,
JOU.JOU_NUMBER,
JOU.ACS_FINANCIAL_YEAR_ID,
JOU.C_ETAT_JOURNAL,
JOU.C_SUB_SET,
ACS_FUNCTION.GetAccountNumber(PTJ.ACS_AUXILIARY_ACCOUNT_ID) AUX_ACC_NUMBER,
ACS_FUNCTION.GetAccountNumber(DIS.ACS_DIVISION_ACCOUNT_ID) DIV_ACC_NUMBER,
ACS_FUNCTION.GetAccountNumber(PTJ.ACS_FINANCIAL_ACCOUNT_ID) ACC_NUMBER,
ACS_FUNCTION.GetAccountNumber(PTJ.ACS_TAX_CODE_ID) TAX_ACC_NUMBER
FROM
V_ACT_IMPUTATION_JOU PTJ,
ACS_DESCRIPTION DES,
ACT_FINANCIAL_DISTRIBUTION DIS,
ACT_DOCUMENT ATD,
V_ACT_JOURNAL JOU,
ACS_FINANCIAL_CURRENCY FUR_MB,
ACS_FINANCIAL_CURRENCY FUR_ME,
PCS.PC_CURR CUR_MB,
PCS.PC_CURR CUR_ME,
ACT_PART_IMPUTATION PAR
WHERE
PTJ.ACS_AUXILIARY_ACCOUNT_ID = DES.ACS_ACCOUNT_ID(+)
AND PTJ.ACT_FINANCIAL_IMPUTATION_ID = DIS.ACT_FINANCIAL_IMPUTATION_ID(+)
AND PTJ.ACT_DOCUMENT_ID = ATD.ACT_DOCUMENT_ID
AND ATD.ACT_JOURNAL_ID = JOU.ACT_JOURNAL_ID
AND PTJ.ACS_FINANCIAL_CURRENCY_ID = FUR_ME.ACS_FINANCIAL_CURRENCY_ID(+)
AND PTJ.ACS_ACS_FINANCIAL_CURRENCY_ID = FUR_MB.ACS_FINANCIAL_CURRENCY_ID(+)
AND FUR_ME.PC_CURR_ID = CUR_ME.PC_CURR_ID(+)
AND FUR_MB.PC_CURR_ID = CUR_MB.PC_CURR_ID(+)
AND PTJ.ACT_PART_IMPUTATION_ID = PAR.ACT_PART_IMPUTATION_ID(+)
AND (JOU.C_SUB_SET = PARAMETER_0 OR PARAMETER_0 IS NULL)
AND (DES.PC_LANG_ID IS NULL OR DES.PC_LANG_ID = VPC_LANG_ID)
;
END RPT_ACT_JOURNAL_AUX;
