--------------------------------------------------------
--  DDL for Procedure RPT_ACT_ARGMT_SUB
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACT_ARGMT_SUB" (
  aRefCursor             in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, PARAMETER_0            in     varchar2
, PROCUSER_LANID         in     pcs.pc_lang.lanid%type
)
is
/**
* description used for sub report of ACT_ARRANGEMENT

* @author JLI  16 Sep 2009
* modified PNA 22.02.2010
* Published VHA 07 Sept 2011
* public
* @param PARAMETER_0   ACT_EXPIRY_ID
*/


VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;

BEGIN

pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;


open aRefCursor for
SELECT  ACC.ACC_NUMBER,
        MET.PME_SBVR,
        EXY.EXP_CALC_NET,
        EXY.EXP_BVR_CODE,
        EXY.EXP_REF_BVR,
        EXY.EXP_AMOUNT_LC,
        PLT.DPO_DESCR,
        ADR.ADD_ADDRESS1,
        ADR.ADD_FORMAT,
        PER.PER_NAME,
        PER.PER_FORENAME,
        PER.PER_ACTIVITY,
        BAK.BAN_NAME1,
        BAK.BAN_ZIP,
        BAK.BAN_CITY
FROM    ACS_FIN_ACC_S_PAYMENT SPA,
        ACS_ACCOUNT ACC,
        ACS_FINANCIAL_ACCOUNT FCC,
        ACS_PAYMENT_METHOD MET,
        ACT_DOCUMENT ATD,
        ACT_EXPIRY EXY,
        ACT_PART_IMPUTATION PAR,
        DIC_PERSON_POLITNESS PLT,
        PAC_ADDRESS ADR,
        PAC_CUSTOM_PARTNER CUS,
        PAC_PERSON PER,
        PCS.PC_BANK BAK
WHERE   EXY.ACT_DOCUMENT_ID = ATD.ACT_DOCUMENT_ID
  AND   EXY.ACT_PART_IMPUTATION_ID = PAR.ACT_PART_IMPUTATION_ID
  AND   PAR.PAC_CUSTOM_PARTNER_ID = CUS.PAC_CUSTOM_PARTNER_ID
  AND   CUS.PAC_CUSTOM_PARTNER_ID = PER.PAC_PERSON_ID
  AND   PER.PAC_PERSON_ID = ADR.PAC_PERSON_ID
  AND   PER.DIC_PERSON_POLITNESS_ID = PLT.DIC_PERSON_POLITNESS_ID(+)
  AND   CUS.ACS_AUXILIARY_ACCOUNT_ID = ACC.ACS_ACCOUNT_ID
  AND   EXY.ACS_FIN_ACC_S_PAYMENT_ID = SPA.ACS_FIN_ACC_S_PAYMENT_ID(+)
  AND   SPA.ACS_PAYMENT_METHOD_ID = MET.ACS_PAYMENT_METHOD_ID(+)
  AND   SPA.ACS_FINANCIAL_ACCOUNT_ID = FCC.ACS_FINANCIAL_ACCOUNT_ID(+)
  AND   FCC.PC_BANK_ID = BAK.PC_BANK_ID(+)
  AND   EXY.EXP_CALC_NET = 1
  AND   ADR.ADD_PRINCIPAL=1
  AND   EXY.ACT_EXPIRY_ID = PARAMETER_0;
END RPT_ACT_ARGMT_SUB;
