--------------------------------------------------------
--  DDL for Procedure RPT_ACT_DET_PAYMENT_SUB
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACT_DET_PAYMENT_SUB" (
  aRefCursor    in out CRYSTAL_CURSOR_TYPES.DualCursorTyp,
  PARAMETER_0   in     varchar2
)
is
/**
* description used for report ACR_REC_IMPUTATION_DET and ACR_PAY_IMPUTATION_DET.

* @author jliu 19 Dec.2007
* @lastupdate 12 Feb 2009
* @public
* @param PARAMETER_0    ACT_PART_IMPUTATION_ID
*/

BEGIN
open aRefCursor for
SELECT
FIN.PC_CURR_ID,
FIN.FIN_LOCAL_CURRENCY,
PAY.ACT_PART_IMPUTATION_ID,
PAY.DET_PAIED_LC,
PAY.DET_PAIED_FC,
PAY.DET_CHARGES_LC,
PAY.DET_CHARGES_FC,
PAY.DET_DISCOUNT_LC,
PAY.DET_DISCOUNT_FC,
PAY.DET_DEDUCTION_LC,
PAY.DET_DEDUCTION_FC,
PAY.DET_DIFF_EXCHANGE,
DOC.DOC_NUMBER,
IMP.PAR_DOCUMENT,
PAY.ACT_DET_PAYMENT_ID
FROM
    ACS_FINANCIAL_CURRENCY FIN,
    ACT_DET_PAYMENT        PAY,
    ACT_DOCUMENT           DOC,
    ACT_PART_IMPUTATION    IMP,
    ACT_EXPIRY             EXP
WHERE
PAY.ACT_EXPIRY_ID = EXP.ACT_EXPIRY_ID
AND EXP.ACT_PART_IMPUTATION_ID = IMP.ACT_PART_IMPUTATION_ID
AND IMP.ACT_DOCUMENT_ID = DOC.ACT_DOCUMENT_ID
AND IMP.ACS_FINANCIAL_CURRENCY_ID = FIN.ACS_FINANCIAL_CURRENCY_ID
AND PAY.ACT_PART_IMPUTATION_ID = to_number(PARAMETER_0)
;
END RPT_ACT_DET_PAYMENT_SUB;
