--------------------------------------------------------
--  DDL for Procedure RPT_ACT_REMINDER_LIST_SUB
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACT_REMINDER_LIST_SUB" (
  aRefCursor             in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, PARAMETER_0            in     varchar2
, PROCUSER_LANID         in     pcs.pc_lang.lanid%type
)
is
/**
* description used for sub report of ACT_REMINDER_LIST  and  ACT_REMINDER_LIST_SI

* @author JLI  16 Sep 2009
* public
* @param PARAMETER_0   ACT_JOB_ID
*/


VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;

BEGIN

pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;


open aRefCursor for
select
       JOB.ACT_JOB_ID,
       PART.PAR_REMIND_DATE,
       PART.DOC_DATE_DELIVERY,
       CAT.ACJ_CATALOGUE_DOCUMENT_ID,
       IMP.ACS_PERIOD_ID,
       REM.REM_NUMBER,
       REM.ACS_ACS_FINANCIAL_CURRENCY_ID,
       count (*) NUMBER_OF_REMINDER,
       sum(EXP.EXP_AMOUNT_LC)          AMOUNT_LC,
       sum(REM.REM_PAYABLE_AMOUNT_LC)  PAYABLE_AMOUNT_LC,
       sum(EXP.EXP_AMOUNT_FC)          AMOUNT_FC,
       sum(REM.REM_PAYABLE_AMOUNT_FC)  PAYABLE_AMOUNT_FC,
       sum(EXP.EXP_AMOUNT_EUR)         AMOUNT_EUR,
       sum(REM.REM_PAYABLE_AMOUNT_EUR) PAYABLE_AMOUNT_EUR,
       sum(REM.REM_CHARGE_AMOUNT_RC)   REM_CHARGE_AMOUNT_RC,
       sum(REM.REM_INTEREST_AMOUNT_RC) REM_INTEREST_AMOUNT_RC
from
     ACT_FINANCIAL_IMPUTATION IMP,
     ACT_PART_IMPUTATION PART,
     ACT_DOCUMENT DOC,
     ACT_EXPIRY EXP,
     ACT_REMINDER REM,
     ACT_JOB JOB,
     ACJ_CATALOGUE_DOCUMENT CAT
where
  JOB.ACT_JOB_ID = PARAMETER_0
  and CAT.C_TYPE_CATALOGUE = '8'
  and JOB.JOB_ACI_CONTROL_DATE is not null
  and IMP.IMF_PRIMARY+0 = 1
  and CAT.ACJ_CATALOGUE_DOCUMENT_ID = DOC.ACJ_CATALOGUE_DOCUMENT_ID
  and DOC.ACT_JOB_ID = JOB.ACT_JOB_ID
  and DOC.ACT_DOCUMENT_ID = PART.ACT_DOCUMENT_ID
  and PART.ACT_PART_IMPUTATION_ID = REM.ACT_PART_IMPUTATION_ID
  and DOC.ACT_DOCUMENT_ID = REM.ACT_DOCUMENT_ID
  and REM.ACT_EXPIRY_ID = EXP.ACT_EXPIRY_ID
  and EXP.ACT_DOCUMENT_ID = IMP.ACT_DOCUMENT_ID
group by
         JOB.ACT_JOB_ID,
         PART.PAR_REMIND_DATE,
         PART.DOC_DATE_DELIVERY,
         CAT.ACJ_CATALOGUE_DOCUMENT_ID,
         IMP.ACS_PERIOD_ID,
         REM.REM_NUMBER,
         REM.ACS_ACS_FINANCIAL_CURRENCY_ID
         ;
END RPT_ACT_REMINDER_LIST_SUB;
