--------------------------------------------------------
--  DDL for Procedure RPT_ACT_REMINDER_LIST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACT_REMINDER_LIST" (
  aRefCursor             in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, PARAMETER_00           in     varchar2
, PROCUSER_LANID         in     pcs.pc_lang.lanid%type
)
is
/**
* description used for report ACT_REMINDER_LIST  and  ACT_REMINDER_LIST_SI

* @author JLI  16 Sep 2009
* @lastupdate VHA 19 October 2012
* public
* @param PARAMETER_0   ACT_JOB_ID

*/


VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;

BEGIN

pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;


open aRefCursor for
SELECT
    ATD.ACT_DOCUMENT_ID ,
    ATD.ACT_JOB_ID ACT_JOB_ID_ATD,
    ATD.DOC_NUMBER DOC_NUMBER_ATD,
    ATD.DOC_DOCUMENT_DATE DOC_DOCUMENT_DATE_ATD,
    ATD_1.DOC_NUMBER DOC_NUMBER,
    ATD_1.DOC_DOCUMENT_DATE,
    (select max(IMP.IMF_NUMBER2)
       from ACT_FINANCIAL_IMPUTATION IMP
      where IMP.ACT_DOCUMENT_ID = ATD_1.ACT_DOCUMENT_ID
          and IMP.IMF_PRIMARY + 0 = 0
          and IMP.IMF_TYPE <> 'VAT') IMF_NUMBER2,
    EPY_2.EXP_ADAPTED,
    AJB.ACT_JOB_ID ACT_JOB_ID,
    AJB.JOB_DESCRIPTION,
    PAR.ACS_FINANCIAL_CURRENCY_ID,
    PAR.ACS_ACS_FINANCIAL_CURRENCY_ID,
    RED.REM_PAYABLE_AMOUNT_LC,
    RED.REM_PAYABLE_AMOUNT_FC,
    RED.REM_NUMBER,
    RPT_FUNCTIONS.FORMATADDRESSCONVERTION(ADR.PAC_ADDRESS_ID) ADD_FORMAT,
    PER.PAC_PERSON_ID,
    PER.PER_NAME,
    PER.PER_SHORT_NAME,
    CUR.CURRENCY,
    RED.REM_CHARGE_AMOUNT_RC,
    RED.REM_INTEREST_AMOUNT_RC
    FROM
    ACS_FINANCIAL_CURRENCY FUR,
    ACT_DOCUMENT ATD,
    ACT_DOCUMENT ATD_1,
    ACT_EXPIRY EPY,
    ACT_EXPIRY EPY_2,
    ACT_JOB AJB,
    ACT_PART_IMPUTATION PAR,
    ACT_PART_IMPUTATION PAR_1,
    ACT_REMINDER RED,
    PAC_ADDRESS ADR,
    PAC_CUSTOM_PARTNER CUS,
    PAC_PERSON PER,
    PCS.PC_CURR CUR
WHERE
AJB.ACT_JOB_ID = PARAMETER_00
AND ATD.ACT_JOB_ID = AJB.ACT_JOB_ID
AND RED.ACT_DOCUMENT_ID = ATD.ACT_DOCUMENT_ID
AND RED.ACT_EXPIRY_ID = EPY.ACT_EXPIRY_ID
AND EPY.ACT_PART_IMPUTATION_ID = PAR_1.ACT_PART_IMPUTATION_ID
AND PAR_1.ACT_DOCUMENT_ID = ATD_1.ACT_DOCUMENT_ID
AND RED.ACT_PART_IMPUTATION_ID = PAR.ACT_PART_IMPUTATION_ID
AND PAR.ACT_PART_IMPUTATION_ID = EPY_2.ACT_PART_IMPUTATION_ID
AND PAR.PAC_CUSTOM_PARTNER_ID = CUS.PAC_CUSTOM_PARTNER_ID
AND PAR.ACS_FINANCIAL_CURRENCY_ID = FUR.ACS_FINANCIAL_CURRENCY_ID
AND FUR.PC_CURR_ID = CUR.PC_CURR_ID
AND PAR.PAC_ADDRESS_ID = ADR.PAC_ADDRESS_ID
AND ADR.PAC_PERSON_ID = PER.PAC_PERSON_ID
;
END RPT_ACT_REMINDER_LIST;
