--------------------------------------------------------
--  DDL for Procedure RPT_ACT_MGM_DIS_RECAP_SUB
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACT_MGM_DIS_RECAP_SUB" (
  aRefCursor             in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, PARAMETER_1            in     VARCHAR2
, PROCUSER_LANID         in     pcs.pc_lang.lanid%type
)
/**
* description used for report ACT_JOURNAL_MGM

* @author jliu 18 nov 2008
* @lastupdate 12 Feb 2009
* @public
* @PARAM PARAMETER_1: ACT_JOURNAL_ID
*/
is

VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;


begin

pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;

open aRefCursor for
SELECT
CPN_ACC.ACC_NUMBER CPN_ACC_NUMBER,
PJ_ACC.ACC_NUMBER PJ_ACC_NUMBER,
QTY_ACC.ACC_NUMBER QTY_ACC_NUMBER,
CUR_MB.CURRENCY CURRENCY_MB,
CUR_ME.CURRENCY CURRENCY_ME,
ATD.ACT_ACT_JOURNAL_ID,
DIS.MGM_AMOUNT_LC_D,
DIS.MGM_AMOUNT_FC_D,
DIS.MGM_AMOUNT_LC_C,
DIS.MGM_AMOUNT_FC_C,
DIS.MGM_QUANTITY_D,
DIS.MGM_QUANTITY_C,
IMP.ACS_FINANCIAL_CURRENCY_ID,
IMP.ACS_ACS_FINANCIAL_CURRENCY_ID,
IMP.ACS_QTY_UNIT_ID,
CUR_MB.CURRENCY CURRENCY_MB,
CUR_ME.CURRENCY CURRENCY_ME
FROM
ACS_ACCOUNT CPN_ACC,
ACS_ACCOUNT PJ_ACC,
ACS_ACCOUNT QTY_ACC,
ACS_FINANCIAL_CURRENCY FUR_MB,
ACS_FINANCIAL_CURRENCY FUR_ME,
PCS.PC_CURR CUR_MB,
PCS.PC_CURR CUR_ME,
ACT_MGM_IMPUTATION IMP,
ACT_MGM_DISTRIBUTION DIS,
ACT_DOCUMENT ATD
WHERE
DIS.ACT_MGM_IMPUTATION_ID = IMP.ACT_MGM_IMPUTATION_ID
AND IMP.ACS_FINANCIAL_CURRENCY_ID = FUR_ME.ACS_FINANCIAL_CURRENCY_ID
AND FUR_ME.PC_CURR_ID = CUR_ME.PC_CURR_ID
AND IMP.ACS_ACS_FINANCIAL_CURRENCY_ID = FUR_MB.ACS_FINANCIAL_CURRENCY_ID
AND FUR_MB.PC_CURR_ID = CUR_MB.PC_CURR_ID
AND IMP.ACS_CPN_ACCOUNT_ID = CPN_ACC.ACS_ACCOUNT_ID
AND IMP.ACT_DOCUMENT_ID = ATD.ACT_DOCUMENT_ID
AND IMP.ACS_QTY_UNIT_ID = QTY_ACC.ACS_ACCOUNT_ID(+)
AND DIS.ACS_PJ_ACCOUNT_ID= PJ_ACC.ACS_ACCOUNT_ID
AND ATD.ACT_ACT_JOURNAL_ID = TO_NUMBER(PARAMETER_1)
;
END RPT_ACT_MGM_DIS_RECAP_SUB;
