--------------------------------------------------------
--  DDL for Procedure RPT_ACT_DTA_BATCH
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACT_DTA_BATCH" (
  aRefCursor  in out CRYSTAL_CURSOR_TYPES.DualCursorTyp,
  PARAMETER_0            in     varchar2
)
IS

/**
* description used for report ACT_DTA BATCH

* @author JLI  16 Sep 2009
* Modified PYB 28 Apr 2010
* public
* @param PARAMETER_0   ACT_JOB_ID

*/


BEGIN
open aRefCursor for
SELECT
FIN.FIN_ETAB_ACCOUNT,
PMM.PME_PRINCIPAL,
PMM.PME_SENDER,
DET.DET_PAIED_LC,
DET.DET_PAIED_FC,
DET.DET_TRANSACTION_TYPE,
DET.DET_SEQ_NUMBER,
DET.DET_FILE_AMOUNT,
DOC.ACT_JOB_ID,
DOC.DOC_COMMENT,
DOC.DOC_EXECUTIVE_DATE,
DOC.DOC_ESTABL_DATE,
PAR.ACS_FINANCIAL_CURRENCY_ID,
PAR.ACS_ACS_FINANCIAL_CURRENCY_ID,
BAN.BAN_NAME1,
BAN.BAN_NAME2,
BAN.BAN_ADR,
BAN.BAN_ZIP,
BAN.BAN_CITY,
CUR.CURRENCY
FROM
ACT_DOCUMENT DOC,
ACT_JOB JOB,
ACT_PART_IMPUTATION PAR,
ACT_DET_PAYMENT DET,
ACT_EXPIRY EXP,
ACS_FINANCIAL_CURRENCY AFC,
PCS.PC_CURR CUR,
ACJ_CATALOGUE_DOCUMENT CAT,
ACS_FIN_ACC_S_PAYMENT FSP,
ACS_PAYMENT_METHOD PMM,
ACS_FINANCIAL_ACCOUNT FIN,
PCS.PC_BANK BAN
WHERE
DOC.ACT_JOB_ID = JOB.ACT_JOB_ID
AND JOB.ACT_JOB_ID = PARAMETER_0
AND DOC.ACT_DOCUMENT_ID = PAR.ACT_DOCUMENT_ID
AND PAR.ACT_PART_IMPUTATION_ID = DET.ACT_PART_IMPUTATION_ID
AND DET.ACT_EXPIRY_ID = EXP.ACT_EXPIRY_ID
AND PAR.ACS_FINANCIAL_CURRENCY_ID = AFC.ACS_FINANCIAL_CURRENCY_ID
AND AFC.PC_CURR_ID = CUR.PC_CURR_ID
AND DOC.ACJ_CATALOGUE_DOCUMENT_ID = CAT.ACJ_CATALOGUE_DOCUMENT_ID
AND DOC.ACS_FIN_ACC_S_PAYMENT_ID = FSP.ACS_FIN_ACC_S_PAYMENT_ID(+)
AND FSP.ACS_PAYMENT_METHOD_ID = PMM.ACS_PAYMENT_METHOD_ID(+)
AND FSP.ACS_FINANCIAL_ACCOUNT_ID = FIN.ACS_FINANCIAL_ACCOUNT_ID(+)
AND FIN.PC_BANK_ID = BAN.PC_BANK_ID(+)
AND CAT.C_TYPE_CATALOGUE >= '3'
AND CAT.C_TYPE_CATALOGUE <= '4'
AND DET.DET_SEQ_NUMBER IS NOT NULL
;

END RPT_ACT_DTA_BATCH;
