--------------------------------------------------------
--  DDL for Procedure RPT_ACT_JOURNAL_GEN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACT_JOURNAL_GEN" (
  aRefCursor             in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, aJOU_NUMBER_From       in     varchar2
, aJOU_NUMBER_To         in     varchar2
, aACS_FINANCIAL_YEAR_ID in     varchar2
, PROCUSER_LANID         in     pcs.pc_lang.lanid%type
)
/**
* description used for report act_journal_gen.rpt

* @author jliu 18 nov 2008
* @lastupdate 12 Feb 2009
* @public
*/

is

VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;


begin
if (aJOU_NUMBER_From is not null) and (Length(Trim(aJOU_NUMBER_From)) > 0) then
    ACR_FUNCTIONS.JOU_NUMBER1 := aJOU_NUMBER_From;
  else
    ACR_FUNCTIONS.JOU_NUMBER1 := ' ';
  end if;
  if (aJOU_NUMBER_To is not null) and (Length(Trim(aJOU_NUMBER_To)) > 0) then
    ACR_FUNCTIONS.JOU_NUMBER2 := aJOU_NUMBER_To;
  end if;
  if (aACS_FINANCIAL_YEAR_ID is not null) and (Length(Trim(aACS_FINANCIAL_YEAR_ID)) > 0) then
    ACR_FUNCTIONS.FIN_YEAR_ID := aACS_FINANCIAL_YEAR_ID;
  end if;

pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;

open aRefCursor for
SELECT
FUR_MB.PC_CURR_ID MB_CURR_ID,
FUR_ME.PC_CURR_ID ME_CURR_ID,
ATD.ACT_DOCUMENT_ID,
ATD.DOC_NUMBER,
ATD.DOC_DOCUMENT_DATE,
JOB.JOB_DESCRIPTION,
PAR.ACT_PART_IMPUTATION_ID,
PAR.PAR_DOCUMENT,
CUR_MB.CURRENCY MB_CURRENCY,
CUR_ME.CURRENCY ME_CURRENCY,
USR.USE_DESCR,
V_IMU.ACT_FINANCIAL_IMPUTATION_ID,
V_IMU.ACT_DOCUMENT_ID,
V_IMU.IMF_PRIMARY,
V_IMU.IMF_DESCRIPTION,
V_IMU.IMF_AMOUNT_LC_D,
V_IMU.IMF_AMOUNT_LC_C,
V_IMU.IMF_EXCHANGE_RATE,
V_IMU.IMF_AMOUNT_FC_D,
V_IMU.IMF_AMOUNT_FC_C,
V_IMU.IMF_VALUE_DATE,
V_IMU.IMF_TRANSACTION_DATE,
V_JOU.ACT_JOURNAL_ID,
V_JOU.JOU_DESCRIPTION,
V_JOU.JOU_NUMBER,
V_JOU.ACS_FINANCIAL_YEAR_ID,
V_JOU.C_ETAT_JOURNAL,
V_JOU.C_SUB_SET,
ACC_DIS.ACC_NUMBER ACC_NUMBER_DIV,
DES_AUX.DES_DESCRIPTION_SUMMARY AUX_DESCRIPTION_SUMMARY,
ACS_FUNCTION.GetAccountNumber(V_IMU.ACS_FINANCIAL_ACCOUNT_ID) FIN_ACC_NUMBER,
ACS_FUNCTION.GetAccountNumber(V_IMU.ACS_TAX_CODE_ID) TAX_ACC_NUMBER,
ACS_FUNCTION.GetAccountNumber(V_IMU.ACS_AUXILIARY_ACCOUNT_ID) AUX_ACC_NUMBER
FROM
V_ACT_IMPUTATION_JOU V_IMU,
V_ACT_JOURNAL V_JOU,
ACT_FINANCIAL_DISTRIBUTION DIS,
ACS_ACCOUNT ACC_DIS,
ACT_DOCUMENT ATD,
ACT_PART_IMPUTATION PAR,
ACT_JOB JOB,
PCS.PC_USER USR,
ACS_FINANCIAL_YEAR YEA,
ACJ_JOB_TYPE TYP,
ACS_FINANCIAL_CURRENCY FUR_MB,
ACS_FINANCIAL_CURRENCY FUR_ME,
PCS.PC_CURR CUR_MB,
PCS.PC_CURR CUR_ME,
ACS_DESCRIPTION DES_AUX
WHERE
V_IMU.ACT_DOCUMENT_ID = ATD.ACT_DOCUMENT_ID
AND V_IMU.ACT_FINANCIAL_IMPUTATION_ID = DIS.ACT_FINANCIAL_IMPUTATION_ID(+)
AND DIS.ACS_DIVISION_ACCOUNT_ID = ACC_DIS.ACS_ACCOUNT_ID(+)
AND ATD.ACT_JOB_ID = JOB.ACT_JOB_ID
AND JOB.ACJ_JOB_TYPE_ID = TYP.ACJ_JOB_TYPE_ID
AND ATD.ACT_JOURNAL_ID = V_JOU.ACT_JOURNAL_ID
AND V_JOU.PC_USER_ID = USR.PC_USER_ID(+)
AND V_JOU.ACS_FINANCIAL_YEAR_ID = YEA.ACS_FINANCIAL_YEAR_ID
AND V_IMU.ACT_PART_IMPUTATION_ID = PAR.ACT_PART_IMPUTATION_ID(+)
AND V_IMU.ACS_ACS_FINANCIAL_CURRENCY_ID = FUR_MB.ACS_FINANCIAL_CURRENCY_ID(+)
AND FUR_MB.PC_CURR_ID = CUR_MB.PC_CURR_ID(+)
AND V_IMU.ACS_FINANCIAL_CURRENCY_ID = FUR_ME.ACS_FINANCIAL_CURRENCY_ID(+)
AND FUR_ME.PC_CURR_ID = CUR_ME.PC_CURR_ID(+)
AND V_IMU.ACS_AUXILIARY_ACCOUNT_ID = DES_AUX.ACS_ACCOUNT_ID(+)
AND DES_AUX.PC_LANG_ID(+) = VPC_LANG_ID
AND V_JOU.C_SUB_SET ='ACC'
;
END RPT_ACT_JOURNAL_GEN;
