--------------------------------------------------------
--  DDL for Procedure RPT_FAM_IMPUTATION_DET
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_FAM_IMPUTATION_DET" (
  aRefCursor  in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, PARAMETER_0 in     varchar2
, PARAMETER_1 in     varchar2
, PROCPARAM_0 in     varchar2
, PROCPARAM_1 in     varchar2
, PROCPARAM_2 in     varchar2
, PROCPARAM_3 in     varchar2
, PROCPARAM_4 in     varchar2
, PROCPARAM_5 in     varchar2
, PROCPARAM_6 in     varchar2
, PROCPARAM_7 in     varchar2
, PROCPARAM_8 in     varchar2
, PROCUSER_LANID in  pcs.pc_lang.lanid%type
)
is
/**
  Procédure stockée utilisée pour le rapport FAM_IMPUTATION_DET (Mouvements Immobilisations)

  @author SDO
  @lastUpdate
  @version 2003
  @public
  @param PARAMETER_0    Journal status=PROV (:0 = No, 1 = Yes)
  @param PARAMETER_1    Journal status=DEF  (:0 = No, 1 = Yes)
  @param PROCPARAM_0    Exercice            (FYE_NO_EXERCICE)
  @param PROCPARAM_1    Date du             (FIM_TRANSACTION_DATE)
  @param PROCPARAM_2    Date au             (FIM_TRANSACTION_DATE)
  @param PROCPARAM_3    Immobilisation du   (FIX_NUMBER)
  @param PROCPARAM_4    Immobilisation au   (FIX_NUMBER)
  @param PROCPARAM_5    Catégorie  de       (CAT_DESCR)
  @param PROCPARAM_6    Catégorie  à        (CAT_DESCR)
  @param PROCPARAM_7    Valeurs gérées      MANAGED_VALUE_ID(List)    '' = All sinon liste des ID
  @param PROCPARAM_8    Types transactions  C_FAM_TRANSACTION_TYP(List)    '' = All sinon liste des ID
*/

VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;

BEGIN
pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;

IF (PROCPARAM_0 is null) and (PROCPARAM_5 is null) and (PROCPARAM_6 is null) THEN /** Sans exercice et sans catégorie */
  open aRefCursor for
    SELECT
      FIX.FAM_FIXED_ASSETS_ID,
      FIX.FIX_NUMBER,
      FIX.FIX_SHORT_DESCR,
      FIX.FIX_LONG_DESCR,
      CAT.FAM_FIXED_ASSETS_CATEG_ID,
      CAT.CAT_DESCR,
      FIM.FAM_IMPUTATION_ID,
      FIM.C_FAM_TRANSACTION_TYP,
      PCS.PC_FUNCTIONS.GETDESCODEDESCR('C_FAM_TRANSACTION_TYP',FIM.C_FAM_TRANSACTION_TYP,VPC_LANG_ID) TRANSACTION_DESCR,
      FIM.FIM_TRANSACTION_DATE,
      FIM.FIM_VALUE_DATE,
      FIM.FIM_DESCR,
      FIM.ACS_FINANCIAL_CURRENCY_ID,
      FIM.FIM_AMOUNT_LC_D AMOUNT_LC_D,
      FIM.FIM_AMOUNT_LC_C AMOUNT_LC_C,
      FIM.ACS_ACS_FINANCIAL_CURRENCY_ID,
      FIM.FIM_AMOUNT_FC_D AMOUNT_FC_D,
      FIM.FIM_AMOUNT_FC_C AMOUNT_FC_C,
      FIM.FAM_JOURNAL_ID,
      FIM.FAM_DOCUMENT_ID,
      FJO.FJO_NUMBER,
      FJO.FJO_DESCR,
      FJO.C_JOURNAL_STATUS,
      FJO.ACS_FINANCIAL_YEAR_ID,
      FVA.FAM_MANAGED_VALUE_ID,
      FDO.FAM_DOCUMENT_ID,
      FDO.FDO_DOCUMENT_DATE,
      FDO.FDO_AMOUNT,
      FDO.FDO_INT_NUMBER,
      FDO.FDO_EXT_NUMBER,
      FDO.FAM_CATALOGUE_ID,
      VAL.VAL_KEY,
      VAL.VAL_DESCR
    FROM
      FAM_DOCUMENT            FDO,
      FAM_MANAGED_VALUE       VAL,
      FAM_VAL_IMPUTATION      FVA,
      FAM_JOURNAL             FJO,
      FAM_IMPUTATION          FIM,
      FAM_FIXED_ASSETS_CATEG  CAT,
      FAM_FIXED_ASSETS        FIX
    WHERE
      FIX.FIX_NUMBER                    >= PROCPARAM_3 AND
      FIX.FIX_NUMBER                    <= PROCPARAM_4 AND
      FIX.FAM_FIXED_ASSETS_CATEG_ID     = CAT.FAM_FIXED_ASSETS_CATEG_ID AND
      FIX.FAM_FIXED_ASSETS_ID           = FIM.FAM_FIXED_ASSETS_ID AND
      FIM.FAM_DOCUMENT_ID               = FDO.FAM_DOCUMENT_ID AND
      FIM.FAM_IMPUTATION_ID             = FVA.FAM_IMPUTATION_ID AND
      (INSTR(','||PROCPARAM_7||',', TO_CHAR(','||FVA.FAM_MANAGED_VALUE_ID||',')) > 0 OR PROCPARAM_7 is null) AND
      FIM.FAM_JOURNAL_ID                = FJO.FAM_JOURNAL_ID AND
      FIM.FIM_TRANSACTION_DATE          >= to_date(PROCPARAM_1,'YYYYMMDD') AND
      FIM.FIM_TRANSACTION_DATE          <= to_date(PROCPARAM_2,'YYYYMMDD') AND
      FVA.FAM_MANAGED_VALUE_ID          = VAL.FAM_MANAGED_VALUE_ID AND
      (INSTR(','||PROCPARAM_8||',', TO_CHAR(','||FIM.C_FAM_TRANSACTION_TYP||',')) > 0 OR PROCPARAM_8 is null) AND
      ((PARAMETER_0 ='1' AND FJO.C_JOURNAL_STATUS ='PROV')
         OR (PARAMETER_1 ='1' AND FJO.C_JOURNAL_STATUS ='DEF')
         OR (PARAMETER_1 ='0' AND  PARAMETER_0 ='0'))

      ;
ELSIF (PROCPARAM_0 is null) and (PROCPARAM_3 is null) and (PROCPARAM_4 is null) THEN /** Sans exercice et sans N° d'immobilisation */
  open aRefCursor for
    SELECT
      CAT.FAM_FIXED_ASSETS_CATEG_ID,
      CAT.CAT_DESCR,
      FIX.FAM_FIXED_ASSETS_ID,
      FIX.FIX_NUMBER,
      FIX.FIX_SHORT_DESCR,
      FIX.FIX_LONG_DESCR,
      FIM.FAM_IMPUTATION_ID,
      FIM.C_FAM_TRANSACTION_TYP,
      PCS.PC_FUNCTIONS.GETDESCODEDESCR('C_FAM_TRANSACTION_TYP',FIM.C_FAM_TRANSACTION_TYP,VPC_LANG_ID) TRANSACTION_DESCR,
      FIM.FIM_TRANSACTION_DATE,
      FIM.FIM_VALUE_DATE,
      FIM.FIM_DESCR,
      FIM.ACS_FINANCIAL_CURRENCY_ID,
      FIM.FIM_AMOUNT_LC_D AMOUNT_LC_D,
      FIM.FIM_AMOUNT_LC_C AMOUNT_LC_C,
      FIM.ACS_ACS_FINANCIAL_CURRENCY_ID,
      FIM.FIM_AMOUNT_FC_D AMOUNT_FC_D,
      FIM.FIM_AMOUNT_FC_C AMOUNT_FC_C,
      FIM.FAM_JOURNAL_ID,
      FIM.FAM_DOCUMENT_ID,
      FJO.FJO_NUMBER,
      FJO.FJO_DESCR,
      FJO.C_JOURNAL_STATUS,
      FJO.ACS_FINANCIAL_YEAR_ID,
      FVA.FAM_MANAGED_VALUE_ID,
      FDO.FAM_DOCUMENT_ID,
      FDO.FDO_DOCUMENT_DATE,
      FDO.FDO_AMOUNT,
      FDO.FDO_INT_NUMBER,
      FDO.FDO_EXT_NUMBER,
      FDO.FAM_CATALOGUE_ID,
      VAL.VAL_KEY,
      VAL.VAL_DESCR
    FROM
      FAM_DOCUMENT            FDO,
      FAM_MANAGED_VALUE       VAL,
      FAM_VAL_IMPUTATION      FVA,
      FAM_JOURNAL             FJO,
      FAM_IMPUTATION          FIM,
      FAM_FIXED_ASSETS        FIX,
      FAM_FIXED_ASSETS_CATEG  CAT
    WHERE
      CAT.CAT_DESCR                     >= PROCPARAM_5 AND
      CAT.CAT_DESCR                     <= PROCPARAM_6 AND
      FIX.FAM_FIXED_ASSETS_CATEG_ID     = CAT.FAM_FIXED_ASSETS_CATEG_ID AND
      FIX.FAM_FIXED_ASSETS_ID           = FIM.FAM_FIXED_ASSETS_ID AND
      FIM.FAM_DOCUMENT_ID               = FDO.FAM_DOCUMENT_ID AND
      FIM.FAM_IMPUTATION_ID             = FVA.FAM_IMPUTATION_ID AND
      (INSTR(','||PROCPARAM_7||',', TO_CHAR(','||FVA.FAM_MANAGED_VALUE_ID||',')) > 0 OR PROCPARAM_7 is null) AND
      FIM.FAM_JOURNAL_ID                = FJO.FAM_JOURNAL_ID AND
      FIM.FIM_TRANSACTION_DATE          >= to_date(PROCPARAM_1,'YYYYMMDD') AND
      FIM.FIM_TRANSACTION_DATE          <= to_date(PROCPARAM_2,'YYYYMMDD') AND
      FVA.FAM_MANAGED_VALUE_ID          = VAL.FAM_MANAGED_VALUE_ID AND
      (INSTR(','||PROCPARAM_8||',', TO_CHAR(','||FIM.C_FAM_TRANSACTION_TYP||',')) > 0 OR PROCPARAM_8 is null) AND
      ((PARAMETER_0 ='1' AND FJO.C_JOURNAL_STATUS ='PROV')
         OR (PARAMETER_1 ='1' AND FJO.C_JOURNAL_STATUS ='DEF')
        OR (PARAMETER_1 ='0' AND  PARAMETER_0 ='0'))

      ;
ELSIF (PROCPARAM_5 is null) and (PROCPARAM_6 is null) THEN /** Sans catégorie */
  open aRefCursor for
    SELECT
      FIX.FAM_FIXED_ASSETS_ID,
      FIX.FIX_NUMBER,
      FIX.FIX_SHORT_DESCR,
      FIX.FIX_LONG_DESCR,
      CAT.FAM_FIXED_ASSETS_CATEG_ID,
      CAT.CAT_DESCR,
      FIM.FAM_IMPUTATION_ID,
      FIM.C_FAM_TRANSACTION_TYP,
      PCS.PC_FUNCTIONS.GETDESCODEDESCR('C_FAM_TRANSACTION_TYP',FIM.C_FAM_TRANSACTION_TYP,VPC_LANG_ID) TRANSACTION_DESCR,
      FIM.FIM_TRANSACTION_DATE,
      FIM.FIM_VALUE_DATE,
      FIM.FIM_DESCR,
      FIM.ACS_FINANCIAL_CURRENCY_ID,
      FIM.FIM_AMOUNT_LC_D AMOUNT_LC_D,
      FIM.FIM_AMOUNT_LC_C AMOUNT_LC_C,
      FIM.ACS_ACS_FINANCIAL_CURRENCY_ID,
      FIM.FIM_AMOUNT_FC_D AMOUNT_FC_D,
      FIM.FIM_AMOUNT_FC_C AMOUNT_FC_C,
      FIM.FAM_JOURNAL_ID,
      FIM.FAM_DOCUMENT_ID,
      FJO.FJO_NUMBER,
      FJO.FJO_DESCR,
      FJO.C_JOURNAL_STATUS,
      FJO.ACS_FINANCIAL_YEAR_ID,
      FVA.FAM_MANAGED_VALUE_ID,
      FDO.FAM_DOCUMENT_ID,
      FDO.FDO_DOCUMENT_DATE,
      FDO.FDO_AMOUNT,
      FDO.FDO_INT_NUMBER,
      FDO.FDO_EXT_NUMBER,
      FDO.FAM_CATALOGUE_ID,
      VAL.VAL_KEY,
      VAL.VAL_DESCR
    FROM
      ACS_FINANCIAL_YEAR      FYE,
      ACS_PERIOD              PER,
      FAM_DOCUMENT            FDO,
      FAM_MANAGED_VALUE       VAL,
      FAM_VAL_IMPUTATION      FVA,
      FAM_JOURNAL             FJO,
      FAM_IMPUTATION          FIM,
      FAM_FIXED_ASSETS_CATEG  CAT,
      FAM_FIXED_ASSETS        FIX
    WHERE
      FIX.FIX_NUMBER                    >= PROCPARAM_3 AND
      FIX.FIX_NUMBER                    <= PROCPARAM_4 AND
      FIX.FAM_FIXED_ASSETS_CATEG_ID     = CAT.FAM_FIXED_ASSETS_CATEG_ID AND
      FIX.FAM_FIXED_ASSETS_ID           = FIM.FAM_FIXED_ASSETS_ID AND
      FIM.FAM_DOCUMENT_ID               = FDO.FAM_DOCUMENT_ID AND
      FIM.FAM_IMPUTATION_ID             = FVA.FAM_IMPUTATION_ID AND
      (INSTR(','||PROCPARAM_7||',', TO_CHAR(','||FVA.FAM_MANAGED_VALUE_ID||',')) > 0 OR PROCPARAM_7 is null) AND
      FIM.FIM_TRANSACTION_DATE          >= to_date(PROCPARAM_1,'YYYYMMDD') AND
      FIM.FIM_TRANSACTION_DATE          <= to_date(PROCPARAM_2,'YYYYMMDD') AND
      FIM.FAM_JOURNAL_ID                = FJO.FAM_JOURNAL_ID AND
      FVA.FAM_MANAGED_VALUE_ID          = VAL.FAM_MANAGED_VALUE_ID AND
      FIM.ACS_PERIOD_ID                 = PER.ACS_PERIOD_ID AND
      PER.ACS_FINANCIAL_YEAR_ID         = FYE.ACS_FINANCIAL_YEAR_ID AND
      FYE.FYE_NO_EXERCICE               = PROCPARAM_0 AND
      (INSTR(','||PROCPARAM_8||',', TO_CHAR(','||FIM.C_FAM_TRANSACTION_TYP||',')) > 0 OR PROCPARAM_8 is null) AND
      ((PARAMETER_0 ='1' AND FJO.C_JOURNAL_STATUS ='PROV')
         OR (PARAMETER_1 ='1' AND FJO.C_JOURNAL_STATUS ='DEF')
         OR (PARAMETER_1 ='0' AND  PARAMETER_0 ='0'))

      ;
ELSIF (PROCPARAM_3 is null) and (PROCPARAM_4 is null) THEN /** Sans immobilisation */
  open aRefCursor for
    SELECT
      CAT.FAM_FIXED_ASSETS_CATEG_ID,
      CAT.CAT_DESCR,
      FIX.FAM_FIXED_ASSETS_ID,
      FIX.FIX_NUMBER,
      FIX.FIX_SHORT_DESCR,
      FIX.FIX_LONG_DESCR,
      FIM.FAM_IMPUTATION_ID,
      FIM.C_FAM_TRANSACTION_TYP,
      PCS.PC_FUNCTIONS.GETDESCODEDESCR('C_FAM_TRANSACTION_TYP',FIM.C_FAM_TRANSACTION_TYP,VPC_LANG_ID) TRANSACTION_DESCR,
      FIM.FIM_TRANSACTION_DATE,
      FIM.FIM_VALUE_DATE,
      FIM.FIM_DESCR,
      FIM.ACS_FINANCIAL_CURRENCY_ID,
      FIM.FIM_AMOUNT_LC_D AMOUNT_LC_D,
      FIM.FIM_AMOUNT_LC_C AMOUNT_LC_C,
      FIM.ACS_ACS_FINANCIAL_CURRENCY_ID,
      FIM.FIM_AMOUNT_FC_D AMOUNT_FC_D,
      FIM.FIM_AMOUNT_FC_C AMOUNT_FC_C,
      FIM.FAM_JOURNAL_ID,
      FIM.FAM_DOCUMENT_ID,
      FJO.FJO_NUMBER,
      FJO.FJO_DESCR,
      FJO.C_JOURNAL_STATUS,
      FJO.ACS_FINANCIAL_YEAR_ID,
      FVA.FAM_MANAGED_VALUE_ID,
      FDO.FAM_DOCUMENT_ID,
      FDO.FDO_DOCUMENT_DATE,
      FDO.FDO_AMOUNT,
      FDO.FDO_INT_NUMBER,
      FDO.FDO_EXT_NUMBER,
      FDO.FAM_CATALOGUE_ID,
      VAL.VAL_KEY,
      VAL.VAL_DESCR
    FROM
      ACS_FINANCIAL_YEAR      FYE,
      ACS_PERIOD              PER,
      FAM_DOCUMENT            FDO,
      FAM_MANAGED_VALUE       VAL,
      FAM_VAL_IMPUTATION      FVA,
      FAM_JOURNAL             FJO,
      FAM_IMPUTATION          FIM,
      FAM_FIXED_ASSETS        FIX,
      FAM_FIXED_ASSETS_CATEG  CAT
    WHERE
      CAT.CAT_DESCR                     >= PROCPARAM_5 AND
      CAT.CAT_DESCR                     <= PROCPARAM_6 AND
      FIX.FAM_FIXED_ASSETS_CATEG_ID     = CAT.FAM_FIXED_ASSETS_CATEG_ID AND
      FIX.FAM_FIXED_ASSETS_ID           = FIM.FAM_FIXED_ASSETS_ID AND
      FIM.FAM_DOCUMENT_ID               = FDO.FAM_DOCUMENT_ID AND
      FIM.FAM_IMPUTATION_ID             = FVA.FAM_IMPUTATION_ID AND
      (INSTR(','||PROCPARAM_7||',', TO_CHAR(','||FVA.FAM_MANAGED_VALUE_ID||',')) > 0 OR PROCPARAM_7 is null) AND
      FIM.FAM_JOURNAL_ID                = FJO.FAM_JOURNAL_ID AND
      FIM.FIM_TRANSACTION_DATE          >= to_date(PROCPARAM_1,'YYYYMMDD') AND
      FIM.FIM_TRANSACTION_DATE          <= to_date(PROCPARAM_2,'YYYYMMDD') AND
      FVA.FAM_MANAGED_VALUE_ID          = VAL.FAM_MANAGED_VALUE_ID AND
      FIM.ACS_PERIOD_ID                 = PER.ACS_PERIOD_ID AND
      PER.ACS_FINANCIAL_YEAR_ID         = FYE.ACS_FINANCIAL_YEAR_ID AND
      FYE.FYE_NO_EXERCICE               = PROCPARAM_0 AND
      (INSTR(','||PROCPARAM_8||',', TO_CHAR(','||FIM.C_FAM_TRANSACTION_TYP||',')) > 0 OR PROCPARAM_8 is null) AND
      --((PARAMETER_0 ='1' AND PARAMETER_1 ='1' AND (FJO.C_JOURNAL_STATUS ='PROV'OR FJO.C_JOURNAL_STATUS ='DEF'))
        ((PARAMETER_0 ='1' AND FJO.C_JOURNAL_STATUS ='PROV')
         OR (PARAMETER_1 ='1' AND FJO.C_JOURNAL_STATUS ='DEF')
        OR (PARAMETER_1 ='0' AND  PARAMETER_0 ='0'))

      ;
end if;
end RPT_FAM_IMPUTATION_DET;
