--------------------------------------------------------
--  DDL for Procedure RPT_ACR_VAT_FORM_SUB_COND
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "RPT_ACR_VAT_FORM_SUB_COND" (
   AREFCURSOR       IN OUT   CRYSTAL_CURSOR_TYPES.DUALCURSORTYP,
   PROCUSER_LANID   IN       PCS.PC_LANG.LANID%TYPE,
   PARAMETER_6      IN       VARCHAR2,
   PARAMETER_7      IN       VARCHAR2,
   PARAMETER_10     IN       VARCHAR2,
   PARAMETER_11     IN       VARCHAR2,
   PARAMETER_12     IN       VARCHAR2,
   PARAMETER_13     IN       VARCHAR2,
   PARAMETER_16     IN       VARCHAR2
)
/**
*Description

 Used for subreport ACR_VAT_FORM_SUB_COND in report ACR_VAT_FORM
*@created VHAAB 29.08.2011
*@public
*@PARAM ACS_VAT_DET_ACCOUNT_ID
*@PARAM parameter_6   ACC_NUMBER(from)
*@PARAM parameter_7   ACC_NUMBER(to)
*@PARAM parameter_10  C_TYPE_CUMUL
*@PARAM parameter_11  C_TYPE_CUMUL
*@PARAM parameter_12  C_TYPE_CUMUL
*@PARAM parameter_13  C_TYPE_CUMUL
*@PARAM parameter_16  ACS_VAT_DET_ACCOUNT_ID
*/
IS
   VPC_LANG_ID   PCS.PC_LANG.PC_LANG_ID%TYPE; --user language id

BEGIN

   PCS.PC_I_LIB_SESSION.SETLANID (PROCUSER_LANID);
   VPC_LANG_ID := PCS.PC_I_LIB_SESSION.GETUSERLANGID;


OPEN AREFCURSOR FOR

      SELECT
              FIM.IMF_TRANSACTION_DATE,
              TAX.HT_LC,
              TAX.TTC_LC,
              TAX.TAX_VAT_AMOUNT_LC,
              TAX.HT_FC,
              TAX.TTC_FC,
              TAX.TAX_VAT_AMOUNT_FC,
              TAX.C_TYPE_CUMUL,
              TAX.TAX_INCLUDED_EXCLUDED,
              TAX.TAX_TMP_VAT_ENCASHMENT,
              TAX.IMF_TRANSACTION_DATE,
              TAX.TAX_RATE,
              FIM.C_GENRE_TRANSACTION,
              FIN.ACC_NUMBER ACC_NUMBER_FIN,
              FIN1.ACC_NUMBER ACC_NUMBER_FIN1,
              FUR.FIN_LOCAL_CURRENCY FIN_LOCAL_CURRENCY,
              FUR_LC.FIN_LOCAL_CURRENCY FIN_LOCAL_CURRENCY_LC,
              ACC.ACC_NUMBER ACC_NUMBER_ACC,
              ACC.ACC_INTEREST,
              DET.ACS_VAT_DET_ACCOUNT_ID,
              (SELECT PC_CURR.PC_CURR_ID
                FROM PCS.PC_CURR PC_CURR
                WHERE  FUR.PC_CURR_ID = PC_CURR.PC_CURR_ID) PC_CURR_ID,
               (SELECT PC_CURR.CURRENCY
                FROM PCS.PC_CURR PC_CURR
                WHERE  FUR.PC_CURR_ID = PC_CURR.PC_CURR_ID)  CURRENCY,
              (SELECT PC_CURR_LC.PC_CURR_ID
                FROM PCS.PC_CURR PC_CURR_LC
                WHERE  FUR_LC.PC_CURR_ID = PC_CURR_LC.PC_CURR_ID) PC_CURR_ID_LC,
              (SELECT DES_DESCRIPTION_SUMMARY FROM ACS_DESCRIPTION
                WHERE ACS_ACCOUNT_ID =  ACC.ACS_ACCOUNT_ID
                AND PC_LANG_ID = VPC_LANG_ID) DES_DESCRIPTION_SUMMARY_ACC,
              (SELECT DES_DESCRIPTION_SUMMARY
                FROM ACS_DESCRIPTION
                WHERE ACS_ACCOUNT_ID = FIN.ACS_ACCOUNT_ID
                AND PC_LANG_ID = VPC_LANG_ID) DES_DESCRIPTION_SUMMARY_FIN,
              (SELECT DES_DESCRIPTION_SUMMARY
                FROM ACS_DESCRIPTION
                WHERE ACS_ACCOUNT_ID = FIN1.ACS_ACCOUNT_ID
                AND PC_LANG_ID = VPC_LANG_ID) DES_DESCRIPTION_SUMMARY_FIN1,
              ACC.ACS_ACCOUNT_ID
      FROM
              V_ACT_DET_TAX_DATE TAX,
              V_ACT_FIN_IMPUTATION_DATE FIM,
              ACS_ACCOUNT ACC,
              ACS_ACCOUNT FIN,
              ACS_ACCOUNT FIN1,
              V_ACS_TAX_CODE TCO,
              ACS_VAT_DET_ACCOUNT DET,
              ACS_FINANCIAL_CURRENCY FUR,
              ACS_FINANCIAL_CURRENCY  FUR_LC
      WHERE
              TAX.ACT_FINANCIAL_IMPUTATION_ID = FIM.ACT_FINANCIAL_IMPUTATION_ID AND
              TAX.ACS_FINANCIAL_ACCOUNT_ID = FIN.ACS_ACCOUNT_ID (+) AND
              TAX.ACS_TAX_CODE_ID = TCO.ACS_TAX_CODE_ID AND
              TCO.ACS_VAT_DET_ACCOUNT_ID = DET.ACS_VAT_DET_ACCOUNT_ID AND
              TCO.ACS_TAX_CODE_ID = ACC.ACS_ACCOUNT_ID AND
              TCO.PC_LANG_ID = VPC_LANG_ID AND
              FIM.ACS_FINANCIAL_ACCOUNT_ID = FIN1.ACS_ACCOUNT_ID AND
               FIM.ACS_FINANCIAL_CURRENCY_ID = FUR.ACS_FINANCIAL_CURRENCY_ID AND
              FIM.ACS_ACS_FINANCIAL_CURRENCY_ID = FUR_LC.ACS_FINANCIAL_CURRENCY_ID AND
              ACC.ACC_NUMBER >= PARAMETER_6 AND
              ACC.ACC_NUMBER <= PARAMETER_7 AND
              ((PARAMETER_10 = '1' AND TAX.C_TYPE_CUMUL = 'INT')
                OR (PARAMETER_11 = '1' AND TAX.C_TYPE_CUMUL = 'EXT')
                OR (PARAMETER_12 = '1' AND TAX.C_TYPE_CUMUL = 'PRE')
                OR (PARAMETER_13 = '1' AND TAX.C_TYPE_CUMUL = 'ENG')) AND
              nvl(TAX.TAX_TMP_VAT_ENCASHMENT, 0) = 0 AND
              DET.ACS_VAT_DET_ACCOUNT_ID = TO_NUMBER(PARAMETER_16);

END RPT_ACR_VAT_FORM_SUB_COND;
