--------------------------------------------------------
--  DDL for Package Body ACR_AGED_RPT
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "ACR_AGED_RPT" 
IS

PROCEDURE ACR_AGED_CUSTOMER_RPT_PK (
  aRefCursor  in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, PROCPARAM_0   in     varchar2
, PROCPARAM_1   in     varchar2
, PROCPARAM_2   in     varchar2
, PROCPARAM_3   in     varchar2
, PROCPARAM_4   in     varchar2
, PROCPARAM_5   in     varchar2
, PROCPARAM_6   in     number
, PROCPARAM_7   in     varchar2
, PROCUSER_LANID in  pcs.pc_lang.lanid%type
)

is
/**
* Procédure stockée utilisée pour le rapport ACR_AGED_CUSTOMER (Echéanciers clients)
*/

VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;

begin
pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;

IF (PROCPARAM_3 is null) THEN
  open aRefCursor for
  SELECT
      PAR.PAR_DOCUMENT,
      PAR.PAR_BLOCKED_DOCUMENT,
      PAR.ACS_ACS_FINANCIAL_CURRENCY_ID,
         (SELECT CUB.CURRENCY
       FROM  PCS.PC_CURR CUB,
             ACS_FINANCIAL_CURRENCY CFB
       WHERE CFB.ACS_FINANCIAL_CURRENCY_ID = PAR.ACS_ACS_FINANCIAL_CURRENCY_ID AND
             CUB.PC_CURR_ID                = CFB.PC_CURR_ID) CURRENCY_MB,
      PAR.ACS_FINANCIAL_CURRENCY_ID,
      (SELECT CUB.CURRENCY
       FROM  PCS.PC_CURR CUB,
             ACS_FINANCIAL_CURRENCY CFB
       WHERE CFB.ACS_FINANCIAL_CURRENCY_ID = PAR.ACS_FINANCIAL_CURRENCY_ID AND
             CUB.PC_CURR_ID                = CFB.PC_CURR_ID) CURRENCY_ME,
      DOC.DOC_NUMBER,
      CAT.C_TYPE_CATALOGUE,
      (SELECT SUB.C_TYPE_CUMUL
       FROM   ACJ_SUB_SET_CAT SUB
       WHERE  DOC.ACJ_CATALOGUE_DOCUMENT_ID = SUB.ACJ_CATALOGUE_DOCUMENT_ID AND
              SUB.C_SUB_SET                 = 'REC') C_TYPE_CUMUL,
      EXP.ACT_EXPIRY_ID,
      EXP.ACT_DOCUMENT_ID,
      EXP.ACT_PART_IMPUTATION_ID,
      EXP.C_STATUS_EXPIRY,
      EXP.EXP_ADAPTED,
      to_char(EXP.EXP_ADAPTED,'YYYY-IW') WEEK_YEAR,
      to_char(EXP.EXP_ADAPTED,'YYYY-MM') MONTH_YEAR,
      to_char(EXP.EXP_ADAPTED,'YYYY') YEAR,
      EXP.EXP_CALCULATED,
      EXP.EXP_AMOUNT_LC,
      EXP.EXP_AMOUNT_FC,
      ACT_FUNCTIONS.DiscountAmountAfter(EXP.ACT_DOCUMENT_ID,EXP.EXP_SLICE,sysdate,1) DISCOUNT_LC,
      ACT_FUNCTIONS.DiscountAmountAfter(EXP.ACT_DOCUMENT_ID,EXP.EXP_SLICE,sysdate,0) DISCOUNT_FC,
      ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,sysdate, 1) DET_PAIED_LC,
      ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,sysdate, 0) DET_PAIED_FC,
      EXP.EXP_AMOUNT_LC - ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,sysdate,1) SOLDE_EXP_LC,
      EXP.EXP_AMOUNT_FC - ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,sysdate,0) SOLDE_EXP_FC,
      ACT_CURRENCY_EVALUATION.GetConvertAmount(EXP.EXP_AMOUNT_FC - ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,sysdate,0),PAR.ACS_FINANCIAL_CURRENCY_ID, PAR.ACS_ACS_FINANCIAL_CURRENCY_ID,sysdate,PROCPARAM_6) SOLDE_REEVAL_LC,
      EXP.EXP_SLICE,
      ACT_FUNCTIONS.LastClaimsNumber(EXP.ACT_EXPIRY_ID) LAST_CLAIMS_LEVEL,
      ACT_FUNCTIONS.LastClaimsDate(EXP.ACT_EXPIRY_ID) LAST_CLAIMS_DATE,
      EXP.ACS_FIN_ACC_S_PAYMENT_ID,
      PMM.ACS_PAYMENT_METHOD_ID,
      (SELECT PME.C_METHOD_CATEGORY
       FROM   ACS_PAYMENT_METHOD PME
       WHERE  PME.ACS_PAYMENT_METHOD_ID = PMM.ACS_PAYMENT_METHOD_ID) C_METHOD_CATEGORY,
      (SELECT DE4.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE4
       WHERE  DE4.ACS_PAYMENT_METHOD_ID  = PMM.ACS_PAYMENT_METHOD_ID AND
              DE4.PC_LANG_ID             = VPC_LANG_ID) PAYMENT_METHOD_DESCR,
      IMP.ACS_PERIOD_ID,
      IMP.IMF_TRANSACTION_DATE,
      IMP.IMF_VALUE_DATE,
      IMP.IMF_DESCRIPTION,
      IMP.ACS_FINANCIAL_ACCOUNT_ID,
      (SELECT ACF.ACC_NUMBER
       FROM   ACS_ACCOUNT ACF
       WHERE  ACF.ACS_ACCOUNT_ID = IMP.ACS_FINANCIAL_ACCOUNT_ID) ACC_NUMBER_FIN,
      (SELECT DE1.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE1
       WHERE  DE1.ACS_ACCOUNT_ID   = IMP.ACS_FINANCIAL_ACCOUNT_ID AND
              DE1.PC_LANG_ID       = VPC_LANG_ID) ACCOUNT_FIN_DESCR,
      JOU.JOU_NUMBER,
      EJO.C_ETAT_JOURNAL,
      IMP.IMF_ACS_DIVISION_ACCOUNT_ID,
      CUS.PAC_CUSTOM_PARTNER_ID,
      CUS.ACS_AUXILIARY_ACCOUNT_ID,
      CUS.C_PARTNER_CATEGORY,
      ACC.ACC_NUMBER ACC_NUMBER_AUX,
      (SELECT DE2.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE2
       WHERE  DE2.ACS_ACCOUNT_ID   = CUS.ACS_AUXILIARY_ACCOUNT_ID AND
              DE2.PC_LANG_ID       = VPC_LANG_ID) ACCOUNT_AUX_DESCR,
      ACC.ACS_SUB_SET_ID,
      (SELECT DE3.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE3
       WHERE  DE3.ACS_SUB_SET_ID   = ACC.ACS_SUB_SET_ID AND
              DE3.PC_LANG_ID       = VPC_LANG_ID) SUB_SET_DESCR,
      AUX.C_TYPE_ACCOUNT,
      PER.PER_NAME,
      PER.PER_FORENAME,
      PER.PER_SHORT_NAME,
      PER.PER_ACTIVITY,
      PER.PER_KEY1,
      (SELECT  ADR.ADD_FORMAT
       FROM    PAC_ADDRESS ADR
       WHERE   ADR.PAC_PERSON_ID = CUS.PAC_CUSTOM_PARTNER_ID AND
               ADR.ADD_PRINCIPAL = '1') ADD_FORMAT
    FROM
      PAC_PERSON                 PER,
      ACS_AUXILIARY_ACCOUNT      AUX,
      PAC_CUSTOM_PARTNER         CUS,
      ACS_FINANCIAL_ACCOUNT      FIN,
      ACT_FINANCIAL_IMPUTATION   IMP,
      ACT_ETAT_JOURNAL           EJO,
      ACT_JOURNAL                JOU,
      ACS_FIN_ACC_S_PAYMENT      PMM,
      ACT_EXPIRY                 EXP,
      ACJ_CATALOGUE_DOCUMENT     CAT,
      ACT_DOCUMENT               DOC,
      ACT_PART_IMPUTATION        PAR,
      ACS_ACCOUNT                ACC
    WHERE
      PAR.ACT_DOCUMENT_ID              = DOC.ACT_DOCUMENT_ID and
      DOC.ACJ_CATALOGUE_DOCUMENT_ID    = CAT.ACJ_CATALOGUE_DOCUMENT_ID and
      CAT.C_TYPE_CATALOGUE             <> '8' and -- Transaction de relance
      PAR.ACT_PART_IMPUTATION_ID       = EXP.ACT_PART_IMPUTATION_ID and
      EXP_CALC_NET + 0                 = 1 and
      ACT_EXPIRY_MANAGEMENT.IsExpiryOpenedAt(EXP.ACT_EXPIRY_ID,sysdate) = 1 and
      EXP.ACS_FIN_ACC_S_PAYMENT_ID     = PMM.ACS_FIN_ACC_S_PAYMENT_ID (+) and
      DOC.ACT_JOURNAL_ID               = JOU.ACT_JOURNAL_ID and
      DOC.ACT_JOURNAL_ID               = EJO.ACT_JOURNAL_ID and
      EJO.C_SUB_SET                    = 'REC' and
      EXP.ACT_PART_IMPUTATION_ID       = IMP.ACT_PART_IMPUTATION_ID and
      IMP.ACT_DET_PAYMENT_ID Is Null   and IMP.ACS_AUXILIARY_ACCOUNT_ID Is Not Null and
      IMP.ACS_FINANCIAL_ACCOUNT_ID     = FIN.ACS_FINANCIAL_ACCOUNT_ID and
      EXP.C_STATUS_EXPIRY              = 0 and
      FIN.FIN_COLLECTIVE               = 1 and
      ACC.ACC_NUMBER                   >= PROCPARAM_1 and
      ACC.ACC_NUMBER                   <= PROCPARAM_2 and
      (ACC.ACS_SUB_SET_ID              = PROCPARAM_0 or PROCPARAM_0 Is Null) and
      (INSTR(','||PROCPARAM_4||',', TO_CHAR(','||IMP.IMF_ACS_DIVISION_ACCOUNT_ID||',')) > 0 OR PROCPARAM_4 is null) and
      (INSTR(','||PROCPARAM_5||',', TO_CHAR(','||FIN.ACS_FINANCIAL_ACCOUNT_ID||',')) > 0 OR PROCPARAM_5 is null) and
      (INSTR(','||PROCPARAM_7||',', TO_CHAR(','||PAR.ACS_FINANCIAL_CURRENCY_ID||',')) > 0 OR PROCPARAM_7 is null) and
      PAR.PAC_CUSTOM_PARTNER_ID        = CUS.PAC_CUSTOM_PARTNER_ID and
      CUS.ACS_AUXILIARY_ACCOUNT_ID     = ACC.ACS_ACCOUNT_ID and
      CUS.ACS_AUXILIARY_ACCOUNT_ID     = AUX.ACS_AUXILIARY_ACCOUNT_ID and
      CUS.PAC_CUSTOM_PARTNER_ID        = PER.PAC_PERSON_ID;
ELSE
  open aRefCursor for
    SELECT
      PAR.PAR_DOCUMENT,
      PAR.PAR_BLOCKED_DOCUMENT,
      PAR.ACS_ACS_FINANCIAL_CURRENCY_ID,
         (SELECT CUB.CURRENCY
       FROM  PCS.PC_CURR CUB,
             ACS_FINANCIAL_CURRENCY CFB
       WHERE CFB.ACS_FINANCIAL_CURRENCY_ID = PAR.ACS_ACS_FINANCIAL_CURRENCY_ID AND
             CUB.PC_CURR_ID                = CFB.PC_CURR_ID) CURRENCY_MB,
      PAR.ACS_FINANCIAL_CURRENCY_ID,
      (SELECT CUB.CURRENCY
       FROM  PCS.PC_CURR CUB,
             ACS_FINANCIAL_CURRENCY CFB
       WHERE CFB.ACS_FINANCIAL_CURRENCY_ID = PAR.ACS_FINANCIAL_CURRENCY_ID AND
             CUB.PC_CURR_ID                = CFB.PC_CURR_ID) CURRENCY_ME,
      DOC.DOC_NUMBER,
      CAT.C_TYPE_CATALOGUE,
      (SELECT SUB.C_TYPE_CUMUL
       FROM   ACJ_SUB_SET_CAT SUB
       WHERE  DOC.ACJ_CATALOGUE_DOCUMENT_ID = SUB.ACJ_CATALOGUE_DOCUMENT_ID AND
              SUB.C_SUB_SET                 = 'REC') C_TYPE_CUMUL,
      EXP.ACT_EXPIRY_ID,
      EXP.ACT_DOCUMENT_ID,
      EXP.ACT_PART_IMPUTATION_ID,
      EXP.C_STATUS_EXPIRY,
      EXP.EXP_ADAPTED,
      to_char(EXP.EXP_ADAPTED,'YYYY-IW') WEEK_YEAR,
      to_char(EXP.EXP_ADAPTED,'YYYY-MM') MONTH_YEAR,
      to_char(EXP.EXP_ADAPTED,'YYYY') YEAR,
      EXP.EXP_CALCULATED,
      EXP.EXP_AMOUNT_LC,
      EXP.EXP_AMOUNT_FC,
      ACT_FUNCTIONS.DiscountAmountAfter(EXP.ACT_DOCUMENT_ID,EXP.EXP_SLICE,to_date(PROCPARAM_3,'YYYYMMDD'),1) DISCOUNT_LC,
      ACT_FUNCTIONS.DiscountAmountAfter(EXP.ACT_DOCUMENT_ID,EXP.EXP_SLICE,to_date(PROCPARAM_3,'YYYYMMDD'),0) DISCOUNT_FC,
      ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,to_date(PROCPARAM_3,'YYYYMMDD'), 1) DET_PAIED_LC,
      ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,to_date(PROCPARAM_3,'YYYYMMDD'), 0) DET_PAIED_FC,
      EXP.EXP_AMOUNT_LC - ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,to_date(PROCPARAM_3,'YYYYMMDD'),1) SOLDE_EXP_LC,
      EXP.EXP_AMOUNT_FC - ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,to_date(PROCPARAM_3,'YYYYMMDD'),0) SOLDE_EXP_FC,
      ACT_CURRENCY_EVALUATION.GetConvertAmount(EXP.EXP_AMOUNT_FC - ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,to_date(PROCPARAM_3,'YYYYMMDD'),0),PAR.ACS_FINANCIAL_CURRENCY_ID, PAR.ACS_ACS_FINANCIAL_CURRENCY_ID,to_date(PROCPARAM_3,'YYYYMMDD'),PROCPARAM_6) SOLDE_REEVAL_LC,
      EXP.EXP_SLICE,
      ACT_FUNCTIONS.LastClaimsNumber(EXP.ACT_EXPIRY_ID) LAST_CLAIMS_LEVEL,
      ACT_FUNCTIONS.LastClaimsDate(EXP.ACT_EXPIRY_ID) LAST_CLAIMS_DATE,
      EXP.ACS_FIN_ACC_S_PAYMENT_ID,
      PMM.ACS_PAYMENT_METHOD_ID,
      (SELECT PME.C_METHOD_CATEGORY
       FROM   ACS_PAYMENT_METHOD PME
       WHERE  PME.ACS_PAYMENT_METHOD_ID = PMM.ACS_PAYMENT_METHOD_ID) C_METHOD_CATEGORY,
      (SELECT DE4.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE4
       WHERE  DE4.ACS_PAYMENT_METHOD_ID  = PMM.ACS_PAYMENT_METHOD_ID AND
              DE4.PC_LANG_ID             = VPC_LANG_ID) PAYMENT_METHOD_DESCR,
      IMP.ACS_PERIOD_ID,
      IMP.IMF_TRANSACTION_DATE,
      IMP.IMF_VALUE_DATE,
      IMP.IMF_DESCRIPTION,
      IMP.ACS_FINANCIAL_ACCOUNT_ID,
      (SELECT ACF.ACC_NUMBER
       FROM   ACS_ACCOUNT ACF
       WHERE  ACF.ACS_ACCOUNT_ID = IMP.ACS_FINANCIAL_ACCOUNT_ID) ACC_NUMBER_FIN,
      (SELECT DE1.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE1
       WHERE  DE1.ACS_ACCOUNT_ID   = IMP.ACS_FINANCIAL_ACCOUNT_ID AND
              DE1.PC_LANG_ID       = VPC_LANG_ID) ACCOUNT_FIN_DESCR,
      JOU.JOU_NUMBER,
      EJO.C_ETAT_JOURNAL,
      IMP.IMF_ACS_DIVISION_ACCOUNT_ID,
      CUS.PAC_CUSTOM_PARTNER_ID,
      CUS.ACS_AUXILIARY_ACCOUNT_ID,
      CUS.C_PARTNER_CATEGORY,
      ACC.ACC_NUMBER ACC_NUMBER_AUX,
      (SELECT DE2.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE2
       WHERE  DE2.ACS_ACCOUNT_ID   = CUS.ACS_AUXILIARY_ACCOUNT_ID AND
              DE2.PC_LANG_ID       = VPC_LANG_ID) ACCOUNT_AUX_DESCR,
      ACC.ACS_SUB_SET_ID,
      (SELECT DE3.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE3
       WHERE  DE3.ACS_SUB_SET_ID   = ACC.ACS_SUB_SET_ID AND
              DE3.PC_LANG_ID       = VPC_LANG_ID) SUB_SET_DESCR,
      AUX.C_TYPE_ACCOUNT,
      PER.PER_NAME,
      PER.PER_FORENAME,
      PER.PER_SHORT_NAME,
      PER.PER_ACTIVITY,
      PER.PER_KEY1,
      (SELECT  ADR.ADD_FORMAT
       FROM    PAC_ADDRESS ADR
       WHERE   ADR.PAC_PERSON_ID = CUS.PAC_CUSTOM_PARTNER_ID AND
               ADR.ADD_PRINCIPAL = '1') ADD_FORMAT
    FROM
      PAC_PERSON                 PER,
      ACS_AUXILIARY_ACCOUNT      AUX,
      PAC_CUSTOM_PARTNER         CUS,
      ACS_FINANCIAL_ACCOUNT      FIN,
      ACT_FINANCIAL_IMPUTATION   IMP,
      ACT_ETAT_JOURNAL           EJO,
      ACT_JOURNAL                JOU,
      ACS_FIN_ACC_S_PAYMENT      PMM,
      ACT_EXPIRY                 EXP,
      ACJ_CATALOGUE_DOCUMENT     CAT,
      ACT_DOCUMENT               DOC,
      ACT_PART_IMPUTATION        PAR,
      ACS_ACCOUNT                ACC
    WHERE
      PAR.ACT_DOCUMENT_ID              = DOC.ACT_DOCUMENT_ID and
      DOC.ACJ_CATALOGUE_DOCUMENT_ID    = CAT.ACJ_CATALOGUE_DOCUMENT_ID and
      CAT.C_TYPE_CATALOGUE             <> '8' and -- Transaction de relance
      PAR.ACT_PART_IMPUTATION_ID       = EXP.ACT_PART_IMPUTATION_ID and
      EXP_CALC_NET + 0                 = 1 and
      ACT_EXPIRY_MANAGEMENT.IsExpiryOpenedAt(EXP.ACT_EXPIRY_ID,to_date(PROCPARAM_3,'YYYYMMDD')) = 1 and
      EXP.ACS_FIN_ACC_S_PAYMENT_ID     = PMM.ACS_FIN_ACC_S_PAYMENT_ID (+) and
      DOC.ACT_JOURNAL_ID               = JOU.ACT_JOURNAL_ID and
      DOC.ACT_JOURNAL_ID               = EJO.ACT_JOURNAL_ID and
      EJO.C_SUB_SET                    = 'REC' and
      EXP.ACT_PART_IMPUTATION_ID       = IMP.ACT_PART_IMPUTATION_ID and
      IMP.ACT_DET_PAYMENT_ID Is Null   and IMP.ACS_AUXILIARY_ACCOUNT_ID Is Not Null and
      IMP.ACS_FINANCIAL_ACCOUNT_ID     = FIN.ACS_FINANCIAL_ACCOUNT_ID and
      (IMP.IMF_TRANSACTION_DATE        <= to_date(PROCPARAM_3,'YYYYMMDD') or PROCPARAM_3 Is Null) and
      FIN.FIN_COLLECTIVE               = 1 and
      ACC.ACC_NUMBER                   >= PROCPARAM_1 and
      ACC.ACC_NUMBER                   <= PROCPARAM_2 and
      (ACC.ACS_SUB_SET_ID              = PROCPARAM_0 or PROCPARAM_0 Is Null) and
      (INSTR(','||PROCPARAM_4||',', TO_CHAR(','||IMP.IMF_ACS_DIVISION_ACCOUNT_ID||',')) > 0 OR PROCPARAM_4 is null) and
      (INSTR(','||PROCPARAM_5||',', TO_CHAR(','||FIN.ACS_FINANCIAL_ACCOUNT_ID||',')) > 0 OR PROCPARAM_5 is null) and
      (INSTR(','||PROCPARAM_7||',', TO_CHAR(','||PAR.ACS_FINANCIAL_CURRENCY_ID||',')) > 0 OR PROCPARAM_7 is null) and
      PAR.PAC_CUSTOM_PARTNER_ID        = CUS.PAC_CUSTOM_PARTNER_ID and
      CUS.ACS_AUXILIARY_ACCOUNT_ID     = ACC.ACS_ACCOUNT_ID and
      CUS.ACS_AUXILIARY_ACCOUNT_ID     = AUX.ACS_AUXILIARY_ACCOUNT_ID and
      CUS.PAC_CUSTOM_PARTNER_ID        = PER.PAC_PERSON_ID;
    end if;
end ACR_AGED_CUSTOMER_RPT_PK;

PROCEDURE ACR_AGED_SUPPLIER_RPT_PK (
  aRefCursor  in out CRYSTAL_CURSOR_TYPES.DualCursorTyp
, PROCPARAM_0   in     varchar2
, PROCPARAM_1   in     varchar2
, PROCPARAM_2   in     varchar2
, PROCPARAM_3   in     varchar2
, PROCPARAM_4   in     varchar2
, PROCPARAM_5   in     varchar2
, PROCPARAM_6   in     number
, PROCPARAM_7   in     varchar2
, PROCUSER_LANID in  pcs.pc_lang.lanid%type
)

is
/**
 * Procédure stockée utilisée pour le rapport ACR_AGED_SUPPLIER (Echéanciers fournisseurs)
*/

VPC_LANG_ID pcs.pc_lang.pc_lang_id%type;

begin
pcs.PC_I_LIB_SESSION.setLanId (procuser_lanid);
VPC_LANG_ID:= pcs.PC_I_LIB_SESSION.GetUserLangId;

IF (PROCPARAM_3 is null) THEN
  open aRefCursor for
    SELECT
      PAR.PAR_DOCUMENT,
      PAR.PAR_BLOCKED_DOCUMENT,
      PAR.ACS_ACS_FINANCIAL_CURRENCY_ID,
         (SELECT CUB.CURRENCY
       FROM  PCS.PC_CURR CUB,
             ACS_FINANCIAL_CURRENCY CFB
       WHERE CFB.ACS_FINANCIAL_CURRENCY_ID = PAR.ACS_ACS_FINANCIAL_CURRENCY_ID AND
             CUB.PC_CURR_ID                = CFB.PC_CURR_ID) CURRENCY_MB,
      PAR.ACS_FINANCIAL_CURRENCY_ID,
      (SELECT CUB.CURRENCY
       FROM  PCS.PC_CURR CUB,
             ACS_FINANCIAL_CURRENCY CFB
       WHERE CFB.ACS_FINANCIAL_CURRENCY_ID = PAR.ACS_FINANCIAL_CURRENCY_ID AND
             CUB.PC_CURR_ID                = CFB.PC_CURR_ID) CURRENCY_ME,
      DOC.DOC_NUMBER,
      CAT.C_TYPE_CATALOGUE,
      (SELECT SUB.C_TYPE_CUMUL
       FROM   ACJ_SUB_SET_CAT SUB
       WHERE  DOC.ACJ_CATALOGUE_DOCUMENT_ID = SUB.ACJ_CATALOGUE_DOCUMENT_ID AND
              SUB.C_SUB_SET                 = 'PAY') C_TYPE_CUMUL,
      EXP.ACT_EXPIRY_ID,
      EXP.ACT_DOCUMENT_ID,
      EXP.ACT_PART_IMPUTATION_ID,
      EXP.C_STATUS_EXPIRY,
      EXP.EXP_ADAPTED,
      to_char(EXP.EXP_ADAPTED,'YYYY-IW') WEEK_YEAR,
      to_char(EXP.EXP_ADAPTED,'YYYY-MM') MONTH_YEAR,
      to_char(EXP.EXP_ADAPTED,'YYYY') YEAR,
      EXP.EXP_CALCULATED,
      EXP.EXP_AMOUNT_LC,
      EXP.EXP_AMOUNT_FC,
      ACT_FUNCTIONS.DiscountAmountAfter(EXP.ACT_DOCUMENT_ID,EXP.EXP_SLICE,sysdate,1) DISCOUNT_LC,
      ACT_FUNCTIONS.DiscountAmountAfter(EXP.ACT_DOCUMENT_ID,EXP.EXP_SLICE,sysdate,0) DISCOUNT_FC,
      ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,sysdate, 1) DET_PAIED_LC,
      ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,sysdate, 0) DET_PAIED_FC,
      EXP.EXP_AMOUNT_LC - ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,sysdate,1) SOLDE_EXP_LC,
      EXP.EXP_AMOUNT_FC - ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,sysdate,0) SOLDE_EXP_FC,
      ACT_CURRENCY_EVALUATION.GetConvertAmount(EXP.EXP_AMOUNT_FC - ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,sysdate,0),PAR.ACS_FINANCIAL_CURRENCY_ID, PAR.ACS_ACS_FINANCIAL_CURRENCY_ID,sysdate,PROCPARAM_6) SOLDE_REEVAL_LC,
      EXP.EXP_SLICE,
      ACT_FUNCTIONS.LastClaimsNumber(EXP.ACT_EXPIRY_ID) LAST_CLAIMS_LEVEL,
      ACT_FUNCTIONS.LastClaimsDate(EXP.ACT_EXPIRY_ID) LAST_CLAIMS_DATE,
      EXP.ACS_FIN_ACC_S_PAYMENT_ID,
      PMM.ACS_PAYMENT_METHOD_ID,
      (SELECT PME.C_METHOD_CATEGORY
       FROM   ACS_PAYMENT_METHOD PME
       WHERE  PME.ACS_PAYMENT_METHOD_ID = PMM.ACS_PAYMENT_METHOD_ID) C_METHOD_CATEGORY,
      (SELECT DE4.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE4
       WHERE  DE4.ACS_PAYMENT_METHOD_ID  = PMM.ACS_PAYMENT_METHOD_ID AND
              DE4.PC_LANG_ID             = VPC_LANG_ID) PAYMENT_METHOD_DESCR,
      IMP.ACS_PERIOD_ID,
      IMP.IMF_TRANSACTION_DATE,
      IMP.IMF_VALUE_DATE,
      IMP.IMF_DESCRIPTION,
      IMP.ACS_FINANCIAL_ACCOUNT_ID,
      (SELECT ACF.ACC_NUMBER
       FROM   ACS_ACCOUNT ACF
       WHERE  ACF.ACS_ACCOUNT_ID = IMP.ACS_FINANCIAL_ACCOUNT_ID) ACC_NUMBER_FIN,
      (SELECT DE1.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE1
       WHERE  DE1.ACS_ACCOUNT_ID   = IMP.ACS_FINANCIAL_ACCOUNT_ID AND
              DE1.PC_LANG_ID       = VPC_LANG_ID) ACCOUNT_FIN_DESCR,
      JOU.JOU_NUMBER,
      EJO.C_ETAT_JOURNAL,
      IMP.IMF_ACS_DIVISION_ACCOUNT_ID,
      SUP.PAC_SUPPLIER_PARTNER_ID,
      SUP.ACS_AUXILIARY_ACCOUNT_ID,
      SUP.C_PARTNER_CATEGORY,
      ACC.ACC_NUMBER ACC_NUMBER_AUX,
      (SELECT DE2.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE2
       WHERE  DE2.ACS_ACCOUNT_ID   = SUP.ACS_AUXILIARY_ACCOUNT_ID AND
              DE2.PC_LANG_ID       = VPC_LANG_ID) ACCOUNT_AUX_DESCR,
      ACC.ACS_SUB_SET_ID,
      (SELECT DE3.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE3
       WHERE  DE3.ACS_SUB_SET_ID   = ACC.ACS_SUB_SET_ID AND
              DE3.PC_LANG_ID       = VPC_LANG_ID) SUB_SET_DESCR,
      AUX.C_TYPE_ACCOUNT,
      PER.PER_NAME,
      PER.PER_FORENAME,
      PER.PER_SHORT_NAME,
      PER.PER_ACTIVITY,
      PER.PER_KEY1,
      (SELECT  ADR.ADD_FORMAT
       FROM    PAC_ADDRESS ADR
       WHERE   ADR.PAC_PERSON_ID = SUP.PAC_SUPPLIER_PARTNER_ID AND
               ADR.ADD_PRINCIPAL = '1') ADD_FORMAT
    FROM
      PAC_PERSON                 PER,
      ACS_AUXILIARY_ACCOUNT      AUX,
      PAC_SUPPLIER_PARTNER       SUP,
      ACS_FINANCIAL_ACCOUNT      FIN,
      ACT_FINANCIAL_IMPUTATION   IMP,
      ACT_ETAT_JOURNAL           EJO,
      ACT_JOURNAL                JOU,
      ACS_FIN_ACC_S_PAYMENT      PMM,
      ACT_EXPIRY                 EXP,
      ACJ_CATALOGUE_DOCUMENT     CAT,
      ACT_DOCUMENT               DOC,
      ACT_PART_IMPUTATION        PAR,
      ACS_ACCOUNT                ACC
    WHERE
      PAR.ACT_DOCUMENT_ID              = DOC.ACT_DOCUMENT_ID and
      DOC.ACJ_CATALOGUE_DOCUMENT_ID    = CAT.ACJ_CATALOGUE_DOCUMENT_ID and
      CAT.C_TYPE_CATALOGUE             <> '8' and -- Transaction de relance
      PAR.ACT_PART_IMPUTATION_ID       = EXP.ACT_PART_IMPUTATION_ID and
      EXP_CALC_NET + 0                 = 1 and
      ACT_EXPIRY_MANAGEMENT.IsExpiryOpenedAt(EXP.ACT_EXPIRY_ID,sysdate) = 1 and
      EXP.ACS_FIN_ACC_S_PAYMENT_ID     = PMM.ACS_FIN_ACC_S_PAYMENT_ID (+) and
      DOC.ACT_JOURNAL_ID               = JOU.ACT_JOURNAL_ID and
      DOC.ACT_JOURNAL_ID               = EJO.ACT_JOURNAL_ID and
      EJO.C_SUB_SET                    = 'PAY' and
      EXP.ACT_PART_IMPUTATION_ID       = IMP.ACT_PART_IMPUTATION_ID and
      IMP.ACT_DET_PAYMENT_ID Is Null   and IMP.ACS_AUXILIARY_ACCOUNT_ID Is Not Null and
      IMP.ACS_FINANCIAL_ACCOUNT_ID     = FIN.ACS_FINANCIAL_ACCOUNT_ID and
      EXP.C_STATUS_EXPIRY              = 0 and
      FIN.FIN_COLLECTIVE               = 1 and
      ACC.ACC_NUMBER                   >= PROCPARAM_1 and
      ACC.ACC_NUMBER                   <= PROCPARAM_2 and
      (ACC.ACS_SUB_SET_ID              = PROCPARAM_0 or PROCPARAM_0 Is Null) and
      (INSTR(','||PROCPARAM_4||',', TO_CHAR(','||IMP.IMF_ACS_DIVISION_ACCOUNT_ID||',')) > 0 OR PROCPARAM_4 is null) and
      (INSTR(','||PROCPARAM_5||',', TO_CHAR(','||FIN.ACS_FINANCIAL_ACCOUNT_ID||',')) > 0 OR PROCPARAM_5 is null) and
      (INSTR(','||PROCPARAM_7||',', TO_CHAR(','||PAR.ACS_FINANCIAL_CURRENCY_ID||',')) > 0 OR PROCPARAM_7 is null) and
      PAR.PAC_SUPPLIER_PARTNER_ID      = SUP.PAC_SUPPLIER_PARTNER_ID and
      SUP.ACS_AUXILIARY_ACCOUNT_ID     = ACC.ACS_ACCOUNT_ID and
      SUP.ACS_AUXILIARY_ACCOUNT_ID     = AUX.ACS_AUXILIARY_ACCOUNT_ID and
      SUP.PAC_SUPPLIER_PARTNER_ID      = PER.PAC_PERSON_ID;
ELSE
  open aRefCursor for
    SELECT
      PAR.PAR_DOCUMENT,
      PAR.PAR_BLOCKED_DOCUMENT,
      PAR.ACS_ACS_FINANCIAL_CURRENCY_ID,
         (SELECT CUB.CURRENCY
       FROM  PCS.PC_CURR CUB,
             ACS_FINANCIAL_CURRENCY CFB
       WHERE CFB.ACS_FINANCIAL_CURRENCY_ID = PAR.ACS_ACS_FINANCIAL_CURRENCY_ID AND
             CUB.PC_CURR_ID                = CFB.PC_CURR_ID) CURRENCY_MB,
      PAR.ACS_FINANCIAL_CURRENCY_ID,
      (SELECT CUB.CURRENCY
       FROM  PCS.PC_CURR CUB,
             ACS_FINANCIAL_CURRENCY CFB
       WHERE CFB.ACS_FINANCIAL_CURRENCY_ID = PAR.ACS_FINANCIAL_CURRENCY_ID AND
             CUB.PC_CURR_ID                = CFB.PC_CURR_ID) CURRENCY_ME,
      DOC.DOC_NUMBER,
      CAT.C_TYPE_CATALOGUE,
      (SELECT SUB.C_TYPE_CUMUL
       FROM   ACJ_SUB_SET_CAT SUB
       WHERE  DOC.ACJ_CATALOGUE_DOCUMENT_ID = SUB.ACJ_CATALOGUE_DOCUMENT_ID AND
              SUB.C_SUB_SET                 = 'PAY') C_TYPE_CUMUL,
      EXP.ACT_EXPIRY_ID,
      EXP.ACT_DOCUMENT_ID,
      EXP.ACT_PART_IMPUTATION_ID,
      EXP.C_STATUS_EXPIRY,
      EXP.EXP_ADAPTED,
      to_char(EXP.EXP_ADAPTED,'YYYY-IW') WEEK_YEAR,
      to_char(EXP.EXP_ADAPTED,'YYYY-MM') MONTH_YEAR,
      to_char(EXP.EXP_ADAPTED,'YYYY') YEAR,
      EXP.EXP_CALCULATED,
      EXP.EXP_AMOUNT_LC,
      EXP.EXP_AMOUNT_FC,
      ACT_FUNCTIONS.DiscountAmountAfter(EXP.ACT_DOCUMENT_ID,EXP.EXP_SLICE,to_date(PROCPARAM_3,'YYYYMMDD'),1) DISCOUNT_LC,
      ACT_FUNCTIONS.DiscountAmountAfter(EXP.ACT_DOCUMENT_ID,EXP.EXP_SLICE,to_date(PROCPARAM_3,'YYYYMMDD'),0) DISCOUNT_FC,
      ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,to_date(PROCPARAM_3,'YYYYMMDD'), 1) DET_PAIED_LC,
      ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,to_date(PROCPARAM_3,'YYYYMMDD'), 0) DET_PAIED_FC,
      EXP.EXP_AMOUNT_LC - ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,to_date(PROCPARAM_3,'YYYYMMDD'),1) SOLDE_EXP_LC,
      EXP.EXP_AMOUNT_FC - ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,to_date(PROCPARAM_3,'YYYYMMDD'),0) SOLDE_EXP_FC,
      ACT_CURRENCY_EVALUATION.GetConvertAmount(EXP.EXP_AMOUNT_FC - ACT_FUNCTIONS.TotalPaymentAt(EXP.ACT_EXPIRY_ID,to_date(PROCPARAM_3,'YYYYMMDD'),0),PAR.ACS_FINANCIAL_CURRENCY_ID, PAR.ACS_ACS_FINANCIAL_CURRENCY_ID,to_date(PROCPARAM_3,'YYYYMMDD'),PROCPARAM_6) SOLDE_REEVAL_LC,
      EXP.EXP_SLICE,
      ACT_FUNCTIONS.LastClaimsNumber(EXP.ACT_EXPIRY_ID) LAST_CLAIMS_LEVEL,
      ACT_FUNCTIONS.LastClaimsDate(EXP.ACT_EXPIRY_ID) LAST_CLAIMS_DATE,
      EXP.ACS_FIN_ACC_S_PAYMENT_ID,
      PMM.ACS_PAYMENT_METHOD_ID,
      (SELECT PME.C_METHOD_CATEGORY
       FROM   ACS_PAYMENT_METHOD PME
       WHERE  PME.ACS_PAYMENT_METHOD_ID = PMM.ACS_PAYMENT_METHOD_ID) C_METHOD_CATEGORY,
      (SELECT DE4.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE4
       WHERE  DE4.ACS_PAYMENT_METHOD_ID  = PMM.ACS_PAYMENT_METHOD_ID AND
              DE4.PC_LANG_ID             = VPC_LANG_ID) PAYMENT_METHOD_DESCR,
      IMP.ACS_PERIOD_ID,
      IMP.IMF_TRANSACTION_DATE,
      IMP.IMF_VALUE_DATE,
      IMP.IMF_DESCRIPTION,
      IMP.ACS_FINANCIAL_ACCOUNT_ID,
      (SELECT ACF.ACC_NUMBER
       FROM   ACS_ACCOUNT ACF
       WHERE  ACF.ACS_ACCOUNT_ID = IMP.ACS_FINANCIAL_ACCOUNT_ID) ACC_NUMBER_FIN,
      (SELECT DE1.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE1
       WHERE  DE1.ACS_ACCOUNT_ID   = IMP.ACS_FINANCIAL_ACCOUNT_ID AND
              DE1.PC_LANG_ID       = VPC_LANG_ID) ACCOUNT_FIN_DESCR,
      JOU.JOU_NUMBER,
      EJO.C_ETAT_JOURNAL,
      IMP.IMF_ACS_DIVISION_ACCOUNT_ID,
      SUP.PAC_SUPPLIER_PARTNER_ID,
      SUP.ACS_AUXILIARY_ACCOUNT_ID,
      SUP.C_PARTNER_CATEGORY,
      ACC.ACC_NUMBER ACC_NUMBER_AUX,
      (SELECT DE2.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE2
       WHERE  DE2.ACS_ACCOUNT_ID   = SUP.ACS_AUXILIARY_ACCOUNT_ID AND
              DE2.PC_LANG_ID       = VPC_LANG_ID) ACCOUNT_AUX_DESCR,
      ACC.ACS_SUB_SET_ID,
      (SELECT DE3.DES_DESCRIPTION_SUMMARY
       FROM   ACS_DESCRIPTION DE3
       WHERE  DE3.ACS_SUB_SET_ID   = ACC.ACS_SUB_SET_ID AND
              DE3.PC_LANG_ID       = VPC_LANG_ID) SUB_SET_DESCR,
      AUX.C_TYPE_ACCOUNT,
      PER.PER_NAME,
      PER.PER_FORENAME,
      PER.PER_SHORT_NAME,
      PER.PER_ACTIVITY,
      PER.PER_KEY1,
      (SELECT  ADR.ADD_FORMAT
       FROM    PAC_ADDRESS ADR
       WHERE   ADR.PAC_PERSON_ID = SUP.PAC_SUPPLIER_PARTNER_ID AND
               ADR.ADD_PRINCIPAL = '1') ADD_FORMAT
    FROM
      PAC_PERSON                 PER,
      ACS_AUXILIARY_ACCOUNT      AUX,
      PAC_SUPPLIER_PARTNER       SUP,
      ACS_FINANCIAL_ACCOUNT      FIN,
      ACT_FINANCIAL_IMPUTATION   IMP,
      ACT_ETAT_JOURNAL           EJO,
      ACT_JOURNAL                JOU,
      ACS_FIN_ACC_S_PAYMENT      PMM,
      ACT_EXPIRY                 EXP,
      ACJ_CATALOGUE_DOCUMENT     CAT,
      ACT_DOCUMENT               DOC,
      ACT_PART_IMPUTATION        PAR,
      ACS_ACCOUNT                ACC
    WHERE
      PAR.ACT_DOCUMENT_ID              = DOC.ACT_DOCUMENT_ID and
      DOC.ACJ_CATALOGUE_DOCUMENT_ID    = CAT.ACJ_CATALOGUE_DOCUMENT_ID and
      CAT.C_TYPE_CATALOGUE             <> '8' and -- Transaction de relance
      PAR.ACT_PART_IMPUTATION_ID       = EXP.ACT_PART_IMPUTATION_ID and
      EXP_CALC_NET + 0                 = 1 and
      ACT_EXPIRY_MANAGEMENT.IsExpiryOpenedAt(EXP.ACT_EXPIRY_ID,to_date(PROCPARAM_3,'YYYYMMDD')) = 1 and
      EXP.ACS_FIN_ACC_S_PAYMENT_ID     = PMM.ACS_FIN_ACC_S_PAYMENT_ID (+) and
      DOC.ACT_JOURNAL_ID               = JOU.ACT_JOURNAL_ID and
      DOC.ACT_JOURNAL_ID               = EJO.ACT_JOURNAL_ID and
      EJO.C_SUB_SET                    = 'PAY' and
      EXP.ACT_PART_IMPUTATION_ID       = IMP.ACT_PART_IMPUTATION_ID and
      IMP.ACT_DET_PAYMENT_ID Is Null   and IMP.ACS_AUXILIARY_ACCOUNT_ID Is Not Null and
      IMP.ACS_FINANCIAL_ACCOUNT_ID     = FIN.ACS_FINANCIAL_ACCOUNT_ID and
      (IMP.IMF_TRANSACTION_DATE        <= to_date(PROCPARAM_3,'YYYYMMDD') or PROCPARAM_3 Is Null) and
      FIN.FIN_COLLECTIVE               = 1 and
      ACC.ACC_NUMBER                   >= PROCPARAM_1 and
      ACC.ACC_NUMBER                   <= PROCPARAM_2 and
      (ACC.ACS_SUB_SET_ID              = PROCPARAM_0 or PROCPARAM_0 Is Null) and
      (INSTR(','||PROCPARAM_4||',', TO_CHAR(','||IMP.IMF_ACS_DIVISION_ACCOUNT_ID||',')) > 0 OR PROCPARAM_4 is null) and
      (INSTR(','||PROCPARAM_5||',', TO_CHAR(','||FIN.ACS_FINANCIAL_ACCOUNT_ID||',')) > 0 OR PROCPARAM_5 is null) and
      (INSTR(','||PROCPARAM_7||',', TO_CHAR(','||PAR.ACS_FINANCIAL_CURRENCY_ID||',')) > 0 OR PROCPARAM_7 is null) and
      PAR.PAC_SUPPLIER_PARTNER_ID      = SUP.PAC_SUPPLIER_PARTNER_ID and
      SUP.ACS_AUXILIARY_ACCOUNT_ID     = ACC.ACS_ACCOUNT_ID and
      SUP.ACS_AUXILIARY_ACCOUNT_ID     = AUX.ACS_AUXILIARY_ACCOUNT_ID and
      SUP.PAC_SUPPLIER_PARTNER_ID      = PER.PAC_PERSON_ID;

    end if;
end ACR_AGED_SUPPLIER_RPT_PK;

END ACR_AGED_RPT;
